const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {ARCHIVE_BUDGET_BYTES, headroom} = require('../../scripts/release-readiness-metrics.cjs');

const root = path.resolve(__dirname, '..', '..');

test('package budget checkpoint reports bounded headroom', (t) => {
    const archive = path.join(root, 'package.zip');
    if (!fs.existsSync(archive)) {
        t.skip('package.zip is generated by the release build gate');
        return;
    }
    const bytes = fs.statSync(archive).size;
    // Reviewed release ceiling: 512 KiB (was 320 KiB, raised 2026-09-15).
    // SiYuan imposes no package.zip size limit and GitHub Release assets allow
    // 2 GB, so this is a self-discipline line, not a host constraint. The
    // larger ceiling keeps the checkpoint meaningful as an early-warning
    // signal instead of a ratchet that must be re-argued every few increments.
    const budget = ARCHIVE_BUDGET_BYTES;
    const remaining = headroom(budget, bytes);
    assert.ok(Number.isSafeInteger(bytes) && bytes > 0);
    assert.ok(bytes <= budget, `package.zip is ${bytes} bytes; budget is ${budget}; headroom is ${remaining} bytes`);
    if (remaining < 1024) t.diagnostic(`package budget checkpoint: ${bytes} bytes; headroom ${remaining} bytes`);
});
