const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..', '..');

test('package budget checkpoint reports bounded headroom', (t) => {
    const archive = path.join(root, 'package.zip');
    if (!fs.existsSync(archive)) {
        t.skip('package.zip is generated by the release build gate');
        return;
    }
    const bytes = fs.statSync(archive).size;
    const budget = 300 * 1024;
    const headroom = budget - bytes;
    assert.ok(Number.isSafeInteger(bytes) && bytes > 0);
    assert.ok(bytes <= budget, `package.zip is ${bytes} bytes; budget is ${budget}; headroom is ${headroom} bytes`);
    if (headroom < 1024) t.diagnostic(`package budget checkpoint: ${bytes} bytes; headroom ${headroom} bytes`);
});
