const test = require('node:test');
const assert = require('node:assert/strict');
const a = require('../src/agent-readonly-audit.js');

const read = (name = 'demo') => ({name, effects: ['localRead'], devices: ['desktop', 'mobile']});

test('constants expose bounded audit enums', () => { assert.deepEqual(a.SAFE_EFFECTS, ['localRead']); assert.equal(a.MAX_ITEMS, 32); });
test('capability names normalize', () => assert.equal(a.normalizeAgentCapabilityName('  Search-Docs '), 'search-docs'));
test('capability names bound length', () => assert.equal(a.normalizeAgentCapabilityName('x'.repeat(200)).length, 96));
test('device normalizes known value', () => assert.equal(a.normalizeAgentAuditDevice('mobile'), 'mobile'));
test('device falls back desktop', () => assert.equal(a.normalizeAgentAuditDevice('tablet'), 'desktop'));
test('status normalizes known value', () => assert.equal(a.normalizeAgentAuditStatus('timeout'), 'timeout'));
test('status falls back failed', () => assert.equal(a.normalizeAgentAuditStatus('oops'), 'failed'));
test('reason normalizes permission denied', () => assert.equal(a.normalizeAgentAuditReason('permission_denied'), 'permission_denied'));
test('reason falls back failed', () => assert.equal(a.normalizeAgentAuditReason('oops'), 'failed'));
test('effects keep local read', () => assert.deepEqual(a.normalizeAgentAuditEffects(['localRead', 'localWrite']), ['localRead']));
test('effects malformed input is empty', () => assert.deepEqual(a.normalizeAgentAuditEffects('localRead'), []));
test('devices dedupe known entries', () => assert.deepEqual(a.normalizeAgentAuditDevices(['desktop', 'desktop']), ['desktop']));
test('devices invalid list falls back all', () => assert.deepEqual(a.normalizeAgentAuditDevices(['tablet']), ['desktop', 'sidebar', 'mobile']));
test('counts clamp upper bound', () => assert.equal(a.normalizeAgentAuditCount(100), 32));
test('counts reject nonfinite', () => assert.equal(a.normalizeAgentAuditCount('nope'), 0));
test('boolean only accepts true', () => assert.equal(a.normalizeAgentAuditBoolean(1), false));
test('read-only effects accept exact localRead', () => assert.equal(a.isReadOnlyAgentEffects(['localRead']), true));
test('write effects reject read-only audit', () => assert.equal(a.isReadOnlyAgentEffects(['localWrite']), false));
test('error redaction keeps stable reason', () => assert.equal(a.redactAgentAuditError({reason: 'timeout', stack: 'secret'}), 'timeout'));
test('error redaction hides arbitrary text', () => assert.equal(a.redactAgentAuditError(new Error('secret')), 'failed'));
test('result normalization marks timeout retryable', () => assert.equal(a.normalizeAgentAuditResult({status: 'timeout'}).retryable, true));
test('result normalization bounds malformed result', () => assert.deepEqual(a.normalizeAgentAuditResult(null), {status: 'failed', reason: 'failed', retryable: true}));
test('definition audit accepts valid read-only item', () => assert.equal(a.auditAgentCapabilityDefinition(read('x')).valid, true));
test('definition audit rejects missing name', () => assert.equal(a.auditAgentCapabilityDefinition({effects: ['localRead']}).reason, 'missing_name'));
test('definition audit rejects write effect', () => assert.equal(a.auditAgentCapabilityDefinition({name: 'x', effects: ['localWrite']}).reason, 'non_read_only'));
test('definition audit accepts wrapper spec', () => assert.equal(a.auditAgentCapabilityDefinition({spec: read('x')}).valid, true));
test('definitions audit counts total', () => assert.equal(a.auditAgentCapabilityDefinitions([read('a'), read('b')]).total, 2));
test('definitions audit catches duplicate names', () => assert.equal(a.auditAgentCapabilityDefinitions([read('a'), read('a')]).duplicates, 1));
test('definitions audit caps input', () => assert.equal(a.auditAgentCapabilityDefinitions(Array.from({length: 40}, (_, i) => read(String(i)))).total, 32));
test('definitions audit malformed input is empty valid', () => assert.equal(a.auditAgentCapabilityDefinitions(null).valid, true));
test('audit summary strips item details', () => assert.deepEqual(a.summarizeAgentCapabilityAudit({valid: true, total: 2, validCount: 2, invalidCount: 0, duplicates: 0}), {valid: true, total: 2, validCount: 2, invalidCount: 0, duplicates: 0}));
test('snapshot uses version one', () => assert.equal(a.buildAgentReadOnlyAuditSnapshot({device: 'mobile'}).version, 1));
test('snapshot normalizes disposed invalidity', () => assert.equal(a.normalizeAgentReadOnlyAuditSnapshot({disposed: true, audit: {valid: true}}).audit.valid, false));
test('snapshot compatibility accepts canonical shape', () => assert.equal(a.isAgentReadOnlyAuditSnapshotCompatible(a.buildAgentReadOnlyAuditSnapshot()), true));
test('snapshot compatibility rejects unknown version', () => assert.equal(a.isAgentReadOnlyAuditSnapshotCompatible({version: 2}), false));
test('failure maps cancelled status', () => assert.deepEqual(a.buildAgentAuditFailure('cancelled'), {status: 'cancelled', reason: 'cancelled', retryable: false}));
test('failure maps permission denial nonretryable', () => assert.equal(a.buildAgentAuditFailure('permission_denied').retryable, false));
test('device matrix includes requested devices', () => assert.deepEqual(Object.keys(a.buildAgentAuditDeviceMatrix([read('x')], ['mobile'])), ['mobile']));
test('snapshot diff detects status change', () => assert.equal(a.diffAgentReadOnlyAuditSnapshots({status: 'ready'}, {status: 'timeout'}).statusChanged, true));
test('snapshot diff detects disposal', () => assert.equal(a.diffAgentReadOnlyAuditSnapshots({disposed: false}, {disposed: true}).disposedChanged, true));
test('audit events emit validity change', () => assert.equal(a.buildAgentReadOnlyAuditEvents({audit: {valid: true}}, {audit: {valid: false}})[0].type, 'validity_changed'));
test('audit events are bounded', () => assert.ok(a.buildAgentReadOnlyAuditEvents({status: 'ready'}, {status: 'failed'}).length <= 8));
test('event normalization removes duplicate events', () => assert.equal(a.normalizeAgentReadOnlyAuditEvents([{type: 'x', status: 'ready', reason: 'failed'}, {type: 'x', status: 'ready', reason: 'failed'}]).length, 1));
test('event normalization caps events', () => assert.equal(a.normalizeAgentReadOnlyAuditEvents(Array.from({length: 20}, (_, i) => ({type: String(i)}))).length, 8));
