const test = require("node:test");
const assert = require("node:assert/strict");
const model = require("../src/external-widget-model.js");

test("external catalog registers nine researched candidates", () => assert.equal(model.EXTERNAL_WIDGET_CATALOG.length, 9));
test("external catalog module ids are unique", () => {
    const ids = model.EXTERNAL_WIDGET_CATALOG.map((entry) => entry.moduleId);
    assert.equal(new Set(ids).size, ids.length);
});
test("external catalog root is immutable", () => assert.equal(Object.isFrozen(model.EXTERNAL_WIDGET_CATALOG), true));
test("external catalog entries are immutable", () => assert.ok(model.EXTERNAL_WIDGET_CATALOG.every(Object.isFrozen)));
test("external catalog platform arrays are immutable", () => assert.ok(model.EXTERNAL_WIDGET_CATALOG.every((entry) => Object.isFrozen(entry.platforms))));
test("external catalog size arrays are immutable", () => assert.ok(model.EXTERNAL_WIDGET_CATALOG.every((entry) => Object.isFrozen(entry.sizes))));
test("external categories remain fixed", () => assert.deepEqual(model.EXTERNAL_WIDGET_CATEGORIES, ["time", "weather", "trending", "holiday", "media", "activity"]));
test("external availability separates direct, setup, bridge and reference", () => assert.deepEqual(model.EXTERNAL_WIDGET_AVAILABILITY, ["builtin", "external", "conditional", "bridge", "reference"]));
test("external auth modes remain bounded", () => assert.deepEqual(model.EXTERNAL_WIDGET_AUTH, ["none", "api-key", "user-endpoint", "local-service"]));
test("external placements omit unsupported generic tablet", () => assert.equal(model.EXTERNAL_WIDGET_PLATFORMS.includes("tablet"), false));
test("external integrations remain bounded", () => assert.deepEqual(model.EXTERNAL_WIDGET_INTEGRATIONS, ["direct", "http", "local-bridge", "reference"]));

test("local time is available without network", () => {
    const item = model.findExternalWidget("external-local-time");
    assert.equal(item.availability, "builtin");
    assert.equal(item.auth, "none");
    assert.equal(item.privacy, "local-only");
});
test("Open-Meteo weather requires no API key", () => {
    const item = model.findExternalWidget("external-weather-open-meteo");
    assert.equal(item.auth, "none");
    assert.equal(item.integration, "http");
});
test("weather declares location-only privacy", () => assert.equal(model.findExternalWidget("external-weather-open-meteo").privacy, "location-only"));
test("DailyHot recommends a user endpoint", () => assert.equal(model.findExternalWidget("external-hot-news-dailyhot").auth, "user-endpoint"));
test("NewsNow recommends a user endpoint", () => assert.equal(model.findExternalWidget("external-news-newsnow").auth, "user-endpoint"));
test("holiday data requires no credentials", () => assert.equal(model.findExternalWidget("external-holiday-cn").auth, "none"));
test("TMDB is gated by an API key", () => assert.equal(model.findExternalWidget("external-movie-tmdb").auth, "api-key"));
test("Bangumi is available on all three plugin surfaces", () => assert.deepEqual(model.findExternalWidget("external-anime-bangumi").platforms, ["desktop", "sidebar", "mobile"]));
test("Bangumi is honestly labeled as a schedule", () => assert.equal(model.findExternalWidget("external-anime-bangumi").title, "每日放送"));
test("Bangumi catalog does not claim personalization", () => assert.match(model.findExternalWidget("external-anime-bangumi").description, /不宣称个性化推荐/));
test("ActivityWatch is local-service only", () => assert.equal(model.findExternalWidget("external-activitywatch-time").auth, "local-service"));
test("ActivityWatch does not claim mobile support", () => assert.equal(model.findExternalWidget("external-activitywatch-time").platforms.includes("mobile"), false));
test("native active-window probe remains reference only", () => assert.equal(model.findExternalWidget("external-active-window").availability, "reference"));

test("category normalizer keeps weather", () => assert.equal(model.normalizeExternalWidgetCategory("weather"), "weather"));
test("category normalizer safely falls back", () => assert.equal(model.normalizeExternalWidgetCategory("unknown"), "time"));
test("availability normalizer keeps bridge", () => assert.equal(model.normalizeExternalWidgetAvailability("bridge"), "bridge"));
test("availability normalizer never makes unknown sources ready", () => assert.equal(model.normalizeExternalWidgetAvailability("ready"), "reference"));
test("auth normalizer keeps api-key", () => assert.equal(model.normalizeExternalWidgetAuth("api-key"), "api-key"));
test("auth normalizer safely falls back", () => assert.equal(model.normalizeExternalWidgetAuth("oauth"), "none"));
test("integration normalizer keeps local bridge", () => assert.equal(model.normalizeExternalWidgetIntegration("local-bridge"), "local-bridge"));
test("integration normalizer safely falls back to reference", () => assert.equal(model.normalizeExternalWidgetIntegration("native"), "reference"));
test("platform normalizer deduplicates and filters", () => assert.deepEqual(model.normalizeExternalWidgetPlatforms(["desktop", "desktop", "tablet", "mobile"]), ["desktop", "mobile"]));
test("platform normalizer rejects malformed input", () => assert.deepEqual(model.normalizeExternalWidgetPlatforms("desktop"), []));
test("entry normalizer strips control characters", () => assert.equal(model.normalizeExternalWidget({title: " A\nB "}).title, "A B"));
test("entry normalizer bounds module ids", () => assert.equal(model.normalizeExternalWidget({moduleId: "x".repeat(200)}).moduleId.length, 96));
test("entry normalizer deduplicates sizes", () => assert.deepEqual(model.normalizeExternalWidget({sizes: ["small", "small", "medium"]}).sizes, ["small", "medium"]));
test("entry normalizer caps size declarations", () => assert.equal(model.normalizeExternalWidget({sizes: Array.from({length: 20}, (_, index) => `s${index}`)}).sizes.length, 8));

test("catalog listing returns defensive objects", () => {
    const listed = model.listExternalWidgetCatalog();
    listed[0].title = "changed";
    assert.notEqual(model.EXTERNAL_WIDGET_CATALOG[0].title, "changed");
});
test("catalog lookup returns null for unknown ids", () => assert.equal(model.findExternalWidget("missing"), null));
test("catalog lookup rejects malformed ids", () => assert.equal(model.findExternalWidget({}), null));
test("query filter matches provider names", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {query: "Open-Meteo"}).length, 1));
test("query filter is case insensitive", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {query: "TMDB"}).length, 1));
test("category filter selects media candidates", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {category: "media"}).length, 2));
test("availability filter selects conditional candidates", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {availability: "conditional"}).length, 1));
test("platform filter excludes desktop-only candidates on mobile", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {platform: "mobile"}).some((entry) => entry.moduleId === "external-active-window"), false));
test("malformed filter input returns empty", () => assert.deepEqual(model.filterExternalWidgets(null, {query: "time"}), []));

test("catalog summary reports all availability classes", () => assert.deepEqual(model.summarizeExternalWidgets(), {
    total: 9, builtin: 1, external: 6, conditional: 1, bridge: 0, reference: 1, needsConfiguration: 5,
}));
test("catalog summary handles malformed input", () => assert.deepEqual(model.summarizeExternalWidgets(null), {
    total: 0, builtin: 0, external: 0, conditional: 0, bridge: 0, reference: 0, needsConfiguration: 0,
}));
test("catalog grouping exposes six semantic groups", () => assert.equal(model.groupExternalWidgets().size, 6));
test("catalog grouping keeps two media providers", () => assert.equal(model.groupExternalWidgets().get("media").length, 2));

test("builtin widgets can be added immediately", () => assert.deepEqual(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-local-time")), {
    moduleId: "external-local-time", status: "builtin", canAdd: true, requiresSetup: false,
}));
test("credential widgets require setup by default", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-movie-tmdb")).status, "needs-config"));
test("configured credential widgets become ready", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-movie-tmdb"), {configured: true}).status, "ready"));
test("production local bridges can be added and configured", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-activitywatch-time")).canAdd, true));
test("reference candidates can never be added", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-active-window")).canAdd, false));
test("production feed widgets can be added before endpoint setup", () => {
    assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-hot-news-dailyhot")).canAdd, true);
    assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-news-newsnow")).canAdd, true);
});
test("production registers the ActivityWatch aggregate adapter", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /register\("external-activitywatch-time"/);
    assert.match(source, /loadActivityWatchSummary/);
    assert.match(source, /fetchActivityWatchViaKernel/);
});
test("ActivityWatch kernel proxy keeps a literal SiYuan endpoint", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /fetch\("\/api\/network\/forwardProxy"/);
    assert.match(source, /allowedActivityWatchUrl\(url\)/);
});
test("NewsNow catalog points to the maintained source repository", () => assert.equal(model.findExternalWidget("external-news-newsnow").sourceUrl, "https://github.com/ourongxing/newsnow"));

test("production registers the offline local clock adapter", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /register\("external-local-time"/);
    assert.match(source, /buildLocalTimeSnapshot/);
});
test("production clock refreshes on a single minute heartbeat", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /moduleId === "external-local-time"/);
    assert.match(source, /millisecondsToNextMinute/);
    assert.match(source, /document\.visibilityState !== "hidden"/);
});
test("production clock heartbeat is disposed with the panel", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /window\.clearTimeout\(homeClockTimer\)/);
    assert.match(source, /removeEventListener\("visibilitychange"/);
});
test("production registers and caches the Bangumi schedule adapter", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /register\("external-anime-bangumi"/);
    assert.match(source, /loadBangumiCalendar/);
    assert.match(source, /cacheTtlMs: 30 \* 60 \* 1000/);
});
test("production registers user-endpoint feed adapters without default URLs", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /registerExternalFeed\("external-hot-news-dailyhot"/);
    assert.match(source, /registerExternalFeed\("external-news-newsnow"/);
    assert.match(source, /normalizeConfiguredFeedUrl/);
    assert.match(source, /loadConfiguredFeed/);
});

test("health normalizer keeps healthy", () => assert.equal(model.normalizeExternalWidgetHealth("healthy"), "healthy"));
test("health normalizer safely falls back", () => assert.equal(model.normalizeExternalWidgetHealth("broken"), "unknown"));
test("reason normalizer strips unsafe control symbols", () => assert.equal(model.normalizeExternalWidgetReason("bad<> reason"), "bad reason"));
test("needs config state resolves configure action", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-config"}), "configure"));
test("local service state resolves start action", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-local-service"}), "start-service"));
test("reference state resolves learn action", () => assert.equal(model.resolveExternalWidgetAction({status: "reference"}), "learn-more"));
test("healthy add state resolves add action", () => assert.equal(model.resolveExternalWidgetAction({status: "builtin", canAdd: true}), "add"));
test("stale state resolves retry action", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: true}, {health: "stale"}), "retry"));
test("status label is localized fallback text", () => assert.equal(model.resolveExternalWidgetStatusLabel("needs-config"), "需要配置"));
test("unknown status label is safe", () => assert.equal(model.resolveExternalWidgetStatusLabel("x"), "状态未知"));
test("offline external state becomes unavailable", () => assert.equal(model.describeExternalWidgetStoreState(model.findExternalWidget("external-weather-open-meteo"), {health: "offline"}).status, "unavailable"));
test("described state exposes retry for errors", () => assert.equal(model.describeExternalWidgetStoreState(model.findExternalWidget("external-weather-open-meteo"), {health: "error"}).canRetry, true));
test("described state keeps setup requirement", () => assert.equal(model.describeExternalWidgetStoreState(model.findExternalWidget("external-movie-tmdb")).requiresSetup, true));
test("selectable state accepts builtin", () => assert.equal(model.isExternalWidgetSelectable({status: "builtin", canAdd: true}), true));
test("unavailable state is not selectable", () => assert.equal(model.isExternalWidgetSelectable({status: "unavailable", canAdd: true}), false));
test("reference state is not selectable", () => assert.equal(model.isExternalWidgetSelectable({status: "reference", canAdd: false}), false));
test("state summary has fixed keys", () => assert.deepEqual(Object.keys(model.summarizeExternalWidgetStates([])).sort(), ["degraded", "healthy", "needsSetup", "reference", "selectable", "total", "unavailable"].sort()));
test("state summary counts selectable and setup", () => assert.deepEqual(model.summarizeExternalWidgetStates([{status: "builtin", canAdd: true}, {status: "needs-config", requiresSetup: true}]), {total: 2, selectable: 1, needsSetup: 1, unavailable: 0, reference: 0, healthy: 0, degraded: 0}));
test("state summary counts degraded health", () => assert.equal(model.summarizeExternalWidgetStates([{health: "stale"}]).degraded, 1));
test("catalog title sort is deterministic", () => assert.equal(model.sortExternalWidgetCatalog([{title: "Z"}, {title: "A"}])[0].title, "A"));
test("catalog availability sort prioritizes builtin", () => assert.equal(model.sortExternalWidgetCatalog([{title: "A", availability: "reference"}, {title: "B", availability: "builtin"}], "availability")[0].availability, "builtin"));
test("catalog sort handles malformed input", () => assert.deepEqual(model.sortExternalWidgetCatalog(null), []));
test("guide link includes sanitized module anchor", () => assert.equal(model.buildExternalWidgetGuideLink("external-weather-open-meteo"), "docs/component-store-guide.md#external-weather-open-meteo"));
test("guide link strips unsafe anchor characters", () => assert.equal(model.buildExternalWidgetGuideLink("a/b"), "docs/component-store-guide.md#ab"));
test("setup steps explain API key", () => assert.deepEqual(model.getExternalWidgetSetupSteps(model.findExternalWidget("external-movie-tmdb")), ["填写个人 API Key", "确认网络与隐私范围"]));
test("setup steps explain local service", () => assert.deepEqual(model.getExternalWidgetSetupSteps(model.findExternalWidget("external-activitywatch-time")), ["启动本机服务并确认回环端口"]));
test("setup steps explain reference limitation", () => assert.deepEqual(model.getExternalWidgetSetupSteps(model.findExternalWidget("external-active-window")), ["启动本机服务并确认回环端口", "仅阅读技术参考，不可直接添加"]));
test("privacy normalizer keeps local only", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("local-only"), "local-only"));
test("privacy normalizer rejects unknown value", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("secret"), "unknown"));
test("state list normalizes every entry", () => assert.equal(model.normalizeExternalWidgetStateList([model.findExternalWidget("external-local-time")])[0].action, "add"));
test("state list malformed input is empty", () => assert.deepEqual(model.normalizeExternalWidgetStateList(null), []));
test("snapshot version is fixed", () => assert.equal(model.EXTERNAL_WIDGET_STATE_VERSION, 1));
test("snapshot history has bounded capacity", () => assert.equal(model.EXTERNAL_WIDGET_HISTORY_MAX, 16));
test("timestamp normalizer truncates values", () => assert.equal(model.normalizeExternalWidgetTimestamp(12.9), 12));
test("timestamp normalizer rejects negative values", () => assert.equal(model.normalizeExternalWidgetTimestamp(-1), 0));
test("snapshot builder carries module id", () => assert.equal(model.buildExternalWidgetSnapshot(model.findExternalWidget("external-local-time"), {timestamp: 42}).moduleId, "external-local-time"));
test("snapshot builder carries health", () => assert.equal(model.buildExternalWidgetSnapshot(model.findExternalWidget("external-local-time"), {health: "healthy"}).health, "healthy"));
test("snapshot normalizer fixes version", () => assert.equal(model.normalizeExternalWidgetSnapshot({version: 99}).version, 1));
test("snapshot compatibility accepts canonical shape", () => assert.equal(model.isExternalWidgetSnapshotCompatible(model.buildExternalWidgetSnapshot(model.findExternalWidget("external-local-time"))), true));
test("snapshot compatibility rejects unknown action", () => assert.equal(model.isExternalWidgetSnapshotCompatible({version: 1, moduleId: "x", health: "healthy", action: "hack"}), false));
test("snapshot serialization includes version", () => assert.match(model.serializeExternalWidgetSnapshot({moduleId: "x"}), /"version":1/));
test("snapshot parser round trips", () => assert.equal(model.parseExternalWidgetSnapshot(model.serializeExternalWidgetSnapshot({moduleId: "x", health: "healthy"})).moduleId, "x"));
test("snapshot parser isolates malformed JSON", () => assert.equal(model.parseExternalWidgetSnapshot("{bad").version, 1));
test("snapshot diff detects health change", () => assert.equal(model.diffExternalWidgetSnapshots({health: "healthy"}, {health: "stale"}).healthChanged, true));
test("snapshot diff detects no change", () => assert.equal(model.diffExternalWidgetSnapshots({health: "healthy"}, {health: "healthy"}).changed, false));
test("transition emits changed type", () => assert.equal(model.buildExternalWidgetTransition({status: "a"}, {status: "b"}).type, "changed"));
test("transition emits unchanged type", () => assert.equal(model.buildExternalWidgetTransition({status: "a"}, {status: "a"}).type, "unchanged"));
test("history normalizer keeps module snapshots", () => assert.equal(model.normalizeExternalWidgetHistory([{moduleId: "x"}]).length, 1));
test("history normalizer drops missing module ids", () => assert.deepEqual(model.normalizeExternalWidgetHistory([{health: "healthy"}]), []));
test("append history adds snapshot", () => assert.equal(model.appendExternalWidgetSnapshot([], {moduleId: "x"}).length, 1));
test("append history ignores empty snapshot", () => assert.deepEqual(model.appendExternalWidgetSnapshot([], {}), []));
test("append history keeps newest capacity", () => assert.equal(model.appendExternalWidgetSnapshot(Array.from({length: 20}, (_, i) => ({moduleId: String(i)})), {moduleId: "z"}).length, 16));
test("history trim applies requested limit", () => assert.equal(model.trimExternalWidgetHistory([{moduleId: "a"}, {moduleId: "b"}], 1).length, 1));
test("latest snapshot selects module", () => assert.equal(model.latestExternalWidgetSnapshot([{moduleId: "a"}, {moduleId: "b"}], "b").moduleId, "b"));
test("latest snapshot returns null when absent", () => assert.equal(model.latestExternalWidgetSnapshot([], "x"), null));
test("history selection filters health", () => assert.equal(model.selectExternalWidgetHistory([{moduleId: "a", health: "stale"}, {moduleId: "b", health: "healthy"}], "stale").length, 1));
test("history summary has fixed version", () => assert.equal(model.summarizeExternalWidgetHistory([]).version, 1));
test("history summary counts health", () => assert.equal(model.summarizeExternalWidgetHistory([{moduleId: "a", health: "stale"}]).counts.stale, 1));
test("snapshot merge prefers newest timestamp", () => assert.equal(model.mergeExternalWidgetSnapshots([{moduleId: "x", timestamp: 1}], [{moduleId: "x", timestamp: 2}])[0].timestamp, 2));
test("snapshot merge sorts module ids", () => assert.deepEqual(model.mergeExternalWidgetSnapshots([{moduleId: "b"}, {moduleId: "a"}]).map((x) => x.moduleId), ["a", "b"]));
test("history serialization round trips", () => assert.equal(model.parseExternalWidgetHistory(model.serializeExternalWidgetHistory([{moduleId: "x"}])).length, 1));
test("history parser rejects wrong version", () => assert.deepEqual(model.parseExternalWidgetHistory('{"version":2,"snapshots":[{"moduleId":"x"}]}'), []));
test("freshness constants remain fixed", () => assert.deepEqual(model.EXTERNAL_WIDGET_FRESHNESS, ["unknown", "fresh", "aging", "expired"]));
test("error kind constants remain fixed", () => assert.ok(model.EXTERNAL_WIDGET_ERROR_KINDS.includes("timeout")));
test("retry max is bounded", () => assert.equal(model.EXTERNAL_WIDGET_RETRY_MAX, 8));
test("health rank orders healthy highest", () => assert.ok(model.externalWidgetHealthRank("healthy") > model.externalWidgetHealthRank("stale")));
test("health comparison returns sign", () => assert.equal(model.compareExternalWidgetHealth("healthy", "error"), 1));
test("ttl clamps low values", () => assert.equal(model.normalizeExternalWidgetTtl(1), 60000));
test("ttl clamps high values", () => assert.equal(model.normalizeExternalWidgetTtl(999999999), 86400000));
test("snapshot age calculates elapsed time", () => assert.equal(model.externalWidgetSnapshotAge({timestamp: 1000}, 2000), 1000));
test("snapshot age missing timestamp is unknown", () => assert.equal(model.externalWidgetSnapshotAge({}, 2000), -1));
test("freshness marks recent snapshot fresh", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 2000, 2000), "fresh"));
test("freshness marks old snapshot expired", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 1000, 200000), "expired"));
test("retry attempt clamps max", () => assert.equal(model.normalizeExternalWidgetRetryAttempt(99), 8));
test("retry delay grows exponentially", () => assert.ok(model.externalWidgetRetryDelay(2) > model.externalWidgetRetryDelay(1)));
test("retry delay is bounded", () => assert.ok(model.externalWidgetRetryDelay(8) <= 300000));
test("stale health is retryable", () => assert.equal(model.shouldRetryExternalWidget("stale"), true));
test("healthy health is not retryable", () => assert.equal(model.shouldRetryExternalWidget("healthy"), false));
test("retry plan computes retry time", () => assert.equal(model.buildExternalWidgetRetryPlan({moduleId: "x", health: "stale", timestamp: 1}, {now: 100}).retryable, true));
test("retry plan stops at max attempt", () => assert.equal(model.buildExternalWidgetRetryPlan({moduleId: "x", health: "stale"}, {attempt: 8}).retryable, false));
test("error kind classifies timeout", () => assert.equal(model.classifyExternalWidgetError("request timeout"), "timeout"));
test("error kind classifies configuration", () => assert.equal(model.classifyExternalWidgetError("invalid api key"), "configuration"));
test("error kind classifies local service", () => assert.equal(model.classifyExternalWidgetError("ActivityWatch service unavailable"), "service"));
test("error kind defaults unknown", () => assert.equal(model.normalizeExternalWidgetErrorKind("wat"), "unknown"));
test("refresh due uses ttl", () => assert.equal(model.isExternalWidgetRefreshDue({timestamp: 1000}, 1000, 70000), true));
test("refresh next time is deterministic", () => assert.equal(model.nextExternalWidgetRefreshAt({timestamp: 1000}, 1000, 1500), 61000));
test("display snapshot keeps old healthy state on transient error", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "x", health: "healthy", timestamp: 1}, {moduleId: "x", health: "error", timestamp: 2}).health, "stale"));
test("display snapshot rejects older current state", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "x", timestamp: 2}, {moduleId: "x", timestamp: 1}).timestamp, 2));
test("snapshot health sorting is deterministic", () => assert.equal(model.sortExternalWidgetSnapshotsByHealth([{moduleId: "a", health: "error"}, {moduleId: "b", health: "healthy"}])[0].moduleId, "b"));
test("snapshot grouping exposes every health", () => assert.equal(model.groupExternalWidgetSnapshotsByHealth([]).size, model.EXTERNAL_WIDGET_HEALTH.length));
test("refresh summary counts due items", () => assert.equal(model.summarizeExternalWidgetRefresh([{moduleId: "x", timestamp: 1}], 1000, 70000).due, 1));
test("refresh summary keeps fixed version", () => assert.equal(model.summarizeExternalWidgetRefresh([]).version, 1));
test("refresh states include queued and running", () => assert.ok(model.EXTERNAL_WIDGET_REFRESH_STATES.includes("queued") && model.EXTERNAL_WIDGET_REFRESH_STATES.includes("running")));
test("refresh queue max is bounded", () => assert.equal(model.EXTERNAL_WIDGET_REFRESH_QUEUE_MAX, 16));
test("refresh state normalizer falls back idle", () => assert.equal(model.normalizeExternalWidgetRefreshState("wat"), "idle"));
test("priority clamps to range", () => assert.equal(model.normalizeExternalWidgetPriority(9), 3));
test("refresh entry keeps module id", () => assert.equal(model.normalizeExternalWidgetRefreshEntry({moduleId: "x"}).moduleId, "x"));
test("refresh queue drops malformed entries", () => assert.deepEqual(model.normalizeExternalWidgetRefreshQueue([{}]), []));
test("enqueue adds queued entry", () => assert.equal(model.enqueueExternalWidgetRefresh([], {moduleId: "x"}).length, 1));
test("enqueue deduplicates module ids", () => assert.equal(model.enqueueExternalWidgetRefresh([{moduleId: "x", priority: 1}], {moduleId: "x", priority: 2}).length, 1));
test("enqueue keeps higher priority", () => assert.equal(model.enqueueExternalWidgetRefresh([{moduleId: "x", priority: 1}], {moduleId: "x", priority: 2})[0].priority, 2));
test("dequeue selects queued entry", () => assert.equal(model.dequeueExternalWidgetRefresh([{moduleId: "x", state: "queued"}]).entry.state, "running"));
test("dequeue returns null when empty", () => assert.equal(model.dequeueExternalWidgetRefresh([]).entry, null));
test("dequeue prefers higher priority", () => assert.equal(model.dequeueExternalWidgetRefresh([{moduleId: "a", state: "queued", priority: 1}, {moduleId: "b", state: "queued", priority: 3}]).entry.moduleId, "b"));
test("update refresh entry changes state", () => assert.equal(model.updateExternalWidgetRefreshEntry([{moduleId: "x"}], "x", {state: "running"})[0].state, "running"));
test("success marker sets succeeded", () => assert.equal(model.markExternalWidgetRefreshSucceeded([{moduleId: "x"}], "x")[0].state, "succeeded"));
test("failure marker sets failed", () => assert.equal(model.markExternalWidgetRefreshFailed([{moduleId: "x"}], "x", "timeout")[0].state, "failed"));
test("cancel marker sets cancelled", () => assert.equal(model.cancelExternalWidgetRefresh([{moduleId: "x"}], "x")[0].state, "cancelled"));
test("remove refresh entry deletes module", () => assert.deepEqual(model.removeExternalWidgetRefresh([{moduleId: "x"}], "x"), []));
test("refresh state counts fixed shape", () => assert.equal(Object.keys(model.countExternalWidgetRefreshStates([])).length, model.EXTERNAL_WIDGET_REFRESH_STATES.length));
test("concurrency clamps range", () => assert.equal(model.normalizeExternalWidgetConcurrency(9), 4));
test("batch planner respects concurrency", () => assert.equal(model.planExternalWidgetRefreshBatch([{moduleId: "a", state: "queued"}, {moduleId: "b", state: "queued"}, {moduleId: "c", state: "queued"}], 2).entries.length, 2));
test("batch planner removes selected entries", () => assert.equal(model.planExternalWidgetRefreshBatch([{moduleId: "a", state: "queued"}], 1).queue.length, 0));
test("batch summary counts running", () => assert.equal(model.summarizeExternalWidgetRefreshBatch([{moduleId: "a", state: "running"}]).running, 1));
test("batch summary counts queued remainder", () => assert.equal(model.summarizeExternalWidgetRefreshBatch([], [{moduleId: "a", state: "queued"}]).queued, 1));
test("receipt marks success", () => assert.equal(model.buildExternalWidgetRefreshReceipt({moduleId: "x"}, {ok: true}).state, "succeeded"));
test("receipt marks cancellation", () => assert.equal(model.buildExternalWidgetRefreshReceipt({moduleId: "x"}, {cancelled: true}).state, "cancelled"));
test("receipt merge deduplicates", () => assert.equal(model.mergeExternalWidgetRefreshReceipts([{moduleId: "x"}, {moduleId: "x"}]).length, 1));
test("receipt merge sorts ids", () => assert.deepEqual(model.mergeExternalWidgetRefreshReceipts([{moduleId: "b"}, {moduleId: "a"}]).map((x) => x.moduleId), ["a", "b"]));
test("schedule decision accepts due snapshot", () => assert.equal(model.shouldScheduleExternalWidgetRefresh({moduleId: "x", timestamp: 1}, 1000, 70000), true));
test("schedule decision rejects fresh snapshot", () => assert.equal(model.shouldScheduleExternalWidgetRefresh({moduleId: "x", timestamp: 1000, health: "healthy"}, 100000, 2000), false));
test("clear queue keeps running entries", () => assert.equal(model.clearExternalWidgetRefreshQueue([{moduleId: "x", state: "running"}, {moduleId: "y"}]).length, 1));

// T-4177~T-4226: external catalog state, setup, snapshot and refresh edge contracts.
test("category normalizer handles null safely", () => assert.equal(model.normalizeExternalWidgetCategory(null), "time"));
test("availability normalizer handles null as reference", () => assert.equal(model.normalizeExternalWidgetAvailability(null), "reference"));
test("auth normalizer handles null as none", () => assert.equal(model.normalizeExternalWidgetAuth(null), "none"));
test("integration normalizer handles null as reference", () => assert.equal(model.normalizeExternalWidgetIntegration(null), "reference"));
test("platform normalizer removes every unsupported value", () => assert.deepEqual(model.normalizeExternalWidgetPlatforms(["tablet", "watch"]), []));
test("entry normalizer provides fixed keys", () => assert.deepEqual(Object.keys(model.normalizeExternalWidget({})).sort(), ["auth", "availability", "category", "description", "integration", "license", "moduleId", "platforms", "privacy", "providerName", "sizes", "sourceUrl", "title"].sort()));
test("entry normalizer bounds provider text", () => assert.equal(model.normalizeExternalWidget({providerName: "x".repeat(200)}).providerName.length, 128));
test("entry normalizer bounds source URL text", () => assert.equal(model.normalizeExternalWidget({sourceUrl: "x".repeat(700)}).sourceUrl.length, 512));
test("catalog query trims and lowercases", () => assert.equal(model.filterExternalWidgets([{moduleId: "x", title: "Today"}], {query: " TODAY "}).length, 1));
test("catalog category filter ignores malformed category", () => assert.equal(model.filterExternalWidgets([{moduleId: "x", category: "time"}], {category: "bad"}).length, 1));
test("catalog platform filter ignores malformed platform", () => assert.equal(model.filterExternalWidgets([{moduleId: "x", platforms: ["desktop"]}], {platform: "tablet"}).length, 1));
test("catalog summary computes custom availability counts", () => assert.deepEqual(model.summarizeExternalWidgets([{availability: "bridge", auth: "local-service"}]), {total: 1, builtin: 0, external: 0, conditional: 0, bridge: 1, reference: 0, needsConfiguration: 1}));
test("catalog grouping handles malformed entries", () => assert.equal(model.groupExternalWidgets(null).size, 0));
test("conditional state requires configuration when absent", () => assert.deepEqual(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "conditional"}), {moduleId: "x", status: "needs-config", canAdd: false, requiresSetup: true}));
test("conditional state becomes ready when configured", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "conditional"}, {configured: true}).status, "ready"));
test("bridge state requires local service when endpoint absent", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "bridge"}).status, "needs-local-service"));
test("bridge state becomes ready when endpoint available", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "bridge"}, {endpointAvailable: true}).status, "ready"));
test("reference state remains reference", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "reference"}).status, "reference"));
test("external state is directly addable", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "external"}).canAdd, true));
test("action for setup state is configure", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-config"}), "configure"));
test("action for bridge setup is start-service", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-local-service"}), "start-service"));
test("action for reference is learn-more", () => assert.equal(model.resolveExternalWidgetAction({status: "reference"}), "learn-more"));
test("action for error health is retry", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: true}, {health: "error"}), "retry"));
test("action for unavailable state is learn-more", () => assert.equal(model.resolveExternalWidgetAction({status: "unavailable", canAdd: false}), "learn-more"));
test("status label covers builtin state", () => assert.equal(model.resolveExternalWidgetStatusLabel("builtin"), "可直接使用"));
test("status label covers unavailable state", () => assert.equal(model.resolveExternalWidgetStatusLabel("unavailable"), "暂不可用"));
test("offline external state changes status only", () => { const state = model.describeExternalWidgetStoreState({moduleId: "x", availability: "external"}, {health: "offline"}); assert.equal(state.status, "unavailable"); assert.equal(state.moduleId, "x"); });
test("unknown health does not enable retry", () => assert.equal(model.describeExternalWidgetStoreState({moduleId: "x", availability: "external"}, {health: "unknown"}).canRetry, false));
test("selectable state rejects missing canAdd", () => assert.equal(model.isExternalWidgetSelectable({status: "external"}), false));
test("selectable state accepts ready state", () => assert.equal(model.isExternalWidgetSelectable({status: "ready", canAdd: true}), true));
test("state summary counts healthy entries", () => assert.equal(model.summarizeExternalWidgetStates([{health: "healthy"}]).healthy, 1));
test("state summary ignores malformed entries", () => assert.deepEqual(model.summarizeExternalWidgetStates([null, "bad"]), {total: 0, selectable: 0, needsSetup: 0, unavailable: 0, reference: 0, healthy: 0, degraded: 0}));
test("catalog title sort preserves stable ties", () => assert.deepEqual(model.sortExternalWidgetCatalog([{title: "A", moduleId: "1"}, {title: "A", moduleId: "2"}]).map((x) => x.moduleId), ["1", "2"]));
test("guide link strips query from custom base", () => assert.equal(model.buildExternalWidgetGuideLink("x", "docs/guide.md?raw=1"), "docs/guide.md#x"));
test("guide link returns cleaned base when module id empty", () => assert.equal(model.buildExternalWidgetGuideLink("", "docs/guide.md"), "docs/guide.md"));
test("setup steps include network notice for HTTP provider", () => assert.deepEqual(model.getExternalWidgetSetupSteps({integration: "http", availability: "external"}), ["确认网络与隐私范围"]));
test("setup steps are empty for local direct provider", () => assert.deepEqual(model.getExternalWidgetSetupSteps({integration: "direct", availability: "builtin", auth: "none"}), []));
test("privacy normalizer keeps preferences-only", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("preferences-only"), "preferences-only"));
test("state list carries normalized status", () => assert.equal(model.normalizeExternalWidgetStateList([{moduleId: "x", availability: "conditional"}])[0].status, "needs-config"));
test("timestamp normalizer caps huge values", () => assert.equal(model.normalizeExternalWidgetTimestamp(99999999999999), 8640000000000));
test("snapshot normalizer defaults unknown health", () => assert.equal(model.normalizeExternalWidgetSnapshot({moduleId: "x", health: "wat"}).health, "unknown"));
test("snapshot parser rejects non-object JSON safely", () => assert.equal(model.parseExternalWidgetSnapshot("[]").version, 1));
test("snapshot diff detects status change", () => assert.equal(model.diffExternalWidgetSnapshots({status: "ready"}, {status: "error"}).changed, true));
test("history trim handles malformed history", () => assert.deepEqual(model.trimExternalWidgetHistory(null, 4), []));
test("latest snapshot ignores malformed records", () => assert.equal(model.latestExternalWidgetSnapshot([null, {moduleId: "x"}], "x").moduleId, "x"));
test("snapshot merge keeps newest duplicate", () => assert.equal(model.mergeExternalWidgetSnapshots([{moduleId: "x", timestamp: 1}], [{moduleId: "x", timestamp: 3}])[0].timestamp, 3));
test("ttl normalizer uses bounded default for malformed value", () => assert.equal(model.normalizeExternalWidgetTtl("bad"), 900000));
test("refresh due rejects fresh snapshot", () => assert.equal(model.isExternalWidgetRefreshDue({timestamp: 1000}, 1000, 60000), false));
test("reason normalizer strips angle brackets", () => assert.equal(model.normalizeExternalWidgetReason("bad<> reason"), "bad reason"));
test("refresh queue update ignores unknown module", () => assert.equal(model.updateExternalWidgetRefreshEntry([{moduleId: "x"}], "y", {state: "running"})[0].state, "idle"));
test("refresh success marker preserves module id", () => assert.equal(model.markExternalWidgetRefreshSucceeded([{moduleId: "x"}], "x")[0].moduleId, "x"));
test("refresh failure marker records reason", () => assert.equal(model.markExternalWidgetRefreshFailed([{moduleId: "x"}], "x", "timeout")[0].reason, "timeout"));
test("refresh cancellation marker records cancelled state", () => assert.equal(model.cancelExternalWidgetRefresh([{moduleId: "x"}], "x")[0].state, "cancelled"));
test("refresh batch planner handles malformed queue", () => assert.deepEqual(model.planExternalWidgetRefreshBatch(null, 2).entries, []));
test("refresh receipt normalizes failed result", () => assert.equal(model.buildExternalWidgetRefreshReceipt({moduleId: "x"}, {ok: false}).state, "failed"));

// T-4232~T-4281: external widget retry, freshness, health ordering and queue lifecycle contracts.
test("health rank orders every known state", () => assert.deepEqual(model.EXTERNAL_WIDGET_HEALTH.slice().sort((a, b) => model.externalWidgetHealthRank(a) - model.externalWidgetHealthRank(b)), ["error", "offline", "stale", "unknown", "cached", "healthy"]));
test("health comparison returns zero for equal states", () => assert.equal(model.compareExternalWidgetHealth("stale", "stale"), 0));
test("health comparison ranks cached above unknown", () => assert.equal(model.compareExternalWidgetHealth("cached", "unknown"), 1));
test("health comparison normalizes malformed values", () => assert.equal(model.compareExternalWidgetHealth("bad", "unknown"), 0));
test("freshness without timestamp is unknown", () => assert.equal(model.resolveExternalWidgetFreshness({moduleId: "x"}, 60000, 1000), "unknown"));
test("freshness at ttl boundary is fresh", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 60000, 61000), "fresh"));
test("freshness just past ttl is aging", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 60000, 61001), "aging"));
test("freshness at twice ttl is aging", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 60000, 121000), "aging"));
test("freshness past twice ttl is expired", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 60000, 121001), "expired"));
test("snapshot age clamps future timestamps to zero", () => assert.equal(model.externalWidgetSnapshotAge({timestamp: 2000}, 1000), 0));
test("retry attempt normalizes negative values", () => assert.equal(model.normalizeExternalWidgetRetryAttempt(-4), 0));
test("retry attempt truncates fractional values", () => assert.equal(model.normalizeExternalWidgetRetryAttempt(2.9), 2));
test("retry attempt rejects non numeric values", () => assert.equal(model.normalizeExternalWidgetRetryAttempt("nope"), 0));
test("retry delay clamps a tiny base", () => assert.equal(model.externalWidgetRetryDelay(0, 1), 250));
test("retry delay clamps a huge base", () => assert.equal(model.externalWidgetRetryDelay(0, 999999), 30000));
test("retry delay is capped at five minutes", () => assert.equal(model.externalWidgetRetryDelay(8, 30000), 300000));
test("retry delay normalizes negative attempt", () => assert.equal(model.externalWidgetRetryDelay(-1, 1000), 1000));
test("healthy widget is not retryable at any attempt", () => assert.equal(model.shouldRetryExternalWidget("healthy", 0), false));
test("offline widget is retryable before max attempt", () => assert.equal(model.shouldRetryExternalWidget("offline", 7), true));
test("offline widget stops retrying at max attempt", () => assert.equal(model.shouldRetryExternalWidget("offline", 8), false));
test("unknown health is never retryable", () => assert.equal(model.shouldRetryExternalWidget("unknown", 0), false));
test("retry plan carries normalized module id", () => assert.equal(model.buildExternalWidgetRetryPlan({moduleId: " x ", health: "stale"}, {now: 10}).moduleId, "x"));
test("retry plan computes delay and retryAt", () => assert.deepEqual(model.buildExternalWidgetRetryPlan({moduleId: "x", health: "error"}, {attempt: 2, baseDelay: 500, now: 100}), {version: 1, moduleId: "x", attempt: 2, retryable: true, delay: 2000, retryAt: 2100}));
test("non retryable plan has zero retryAt", () => assert.equal(model.buildExternalWidgetRetryPlan({moduleId: "x", health: "healthy"}, {now: 100}).retryAt, 0));
test("retry plan clamps supplied attempt", () => assert.equal(model.buildExternalWidgetRetryPlan({health: "stale"}, {attempt: 99}).attempt, 8));
test("error classifier recognizes timed out wording", () => assert.equal(model.classifyExternalWidgetError("request timed out"), "timeout"));
test("error classifier recognizes deadline wording", () => assert.equal(model.classifyExternalWidgetError("deadline exceeded"), "timeout"));
test("error classifier recognizes api key wording", () => assert.equal(model.classifyExternalWidgetError("missing API key"), "configuration"));
test("error classifier recognizes localhost service wording", () => assert.equal(model.classifyExternalWidgetError("localhost refused connection"), "service"));
test("error classifier recognizes network wording", () => assert.equal(model.classifyExternalWidgetError("network unavailable"), "network"));
test("error classifier recognizes response wording", () => assert.equal(model.classifyExternalWidgetError("invalid JSON response"), "response"));
test("empty error classifier returns none", () => assert.equal(model.classifyExternalWidgetError(""), "none"));
test("next refresh without timestamp uses current time", () => assert.equal(model.nextExternalWidgetRefreshAt({moduleId: "x"}, 60000, 1234), 1234));
test("next refresh never returns a time before now", () => assert.equal(model.nextExternalWidgetRefreshAt({timestamp: 1}, 60000, 1234), 60001));
test("refresh due is true at exact expiry", () => assert.equal(model.isExternalWidgetRefreshDue({timestamp: 1000}, 60000, 61000), true));
test("refresh due is false one millisecond before expiry", () => assert.equal(model.isExternalWidgetRefreshDue({timestamp: 1000}, 60000, 60999), false));
test("display snapshot uses current when previous is empty", () => assert.equal(model.selectExternalWidgetDisplaySnapshot(null, {moduleId: "x", timestamp: 2}).moduleId, "x"));
test("display snapshot keeps previous for module mismatch", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "a", timestamp: 1}, {moduleId: "b", timestamp: 2}).moduleId, "a"));
test("display snapshot accepts newer healthy state", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "x", health: "stale", timestamp: 1}, {moduleId: "x", health: "healthy", timestamp: 2}).health, "healthy"));
test("display snapshot accepts equal timestamp current state", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "x", status: "old", timestamp: 2}, {moduleId: "x", status: "new", timestamp: 2}).status, "new"));
test("display snapshot does not degrade unknown previous health", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "x", health: "unknown", timestamp: 1}, {moduleId: "x", health: "error", timestamp: 2}).health, "error"));
test("health sorting puts cached before stale", () => assert.deepEqual(model.sortExternalWidgetSnapshotsByHealth([{moduleId: "s", health: "stale"}, {moduleId: "c", health: "cached"}]).map((x) => x.moduleId), ["c", "s"]));
test("health sorting uses module id tie breaker", () => assert.deepEqual(model.sortExternalWidgetSnapshotsByHealth([{moduleId: "b", health: "healthy"}, {moduleId: "a", health: "healthy"}]).map((x) => x.moduleId), ["a", "b"]));
test("health sorting drops snapshots without module id", () => assert.equal(model.sortExternalWidgetSnapshotsByHealth([{health: "healthy"}]).length, 0));
test("health groups place snapshot in normalized group", () => assert.equal(model.groupExternalWidgetSnapshotsByHealth([{moduleId: "x", health: "bad"}]).get("unknown").length, 1));
test("refresh summary counts retryable errors", () => assert.equal(model.summarizeExternalWidgetRefresh([{moduleId: "x", health: "error", timestamp: 1}], 60000, 2).retryable, 1));
test("refresh summary counts fresh snapshots", () => assert.equal(model.summarizeExternalWidgetRefresh([{moduleId: "x", timestamp: 1000}], 60000, 1001).fresh, 1));
test("refresh summary ignores snapshots without module id", () => assert.equal(model.summarizeExternalWidgetRefresh([{timestamp: 1}], 60000, 2).total, 0));
test("refresh entry defaults idle state and priority", () => assert.deepEqual(model.normalizeExternalWidgetRefreshEntry({moduleId: "x"}), {moduleId: "x", state: "idle", priority: 1, requestedAt: 0, attempt: 0, reason: ""}));
test("refresh entry clamps negative priority", () => assert.equal(model.normalizeExternalWidgetRefreshEntry({moduleId: "x", priority: -3}).priority, 0));
test("refresh entry truncates priority", () => assert.equal(model.normalizeExternalWidgetRefreshEntry({moduleId: "x", priority: 2.8}).priority, 2));
test("refresh entry bounds reason text", () => assert.equal(model.normalizeExternalWidgetRefreshEntry({moduleId: "x", reason: "r".repeat(200)}).reason.length, 96));
test("refresh queue keeps only bounded number of entries", () => assert.equal(model.normalizeExternalWidgetRefreshQueue(Array.from({length: 20}, (_, i) => ({moduleId: `m${i}`}))).length, 16));
test("refresh queue preserves first bounded entries", () => assert.equal(model.normalizeExternalWidgetRefreshQueue(Array.from({length: 20}, (_, i) => ({moduleId: `m${i}`})))[0].moduleId, "m0"));
test("enqueue trims oldest entry when queue is full", () => { const queue = Array.from({length: 16}, (_, i) => ({moduleId: `m${i}`})); assert.equal(model.enqueueExternalWidgetRefresh(queue, {moduleId: "new"})[0].moduleId, "m1"); });
test("enqueue forces queued state on new entry", () => assert.equal(model.enqueueExternalWidgetRefresh([], {moduleId: "x", state: "failed"})[0].state, "queued"));
test("enqueue keeps requested timestamp when provided", () => assert.equal(model.enqueueExternalWidgetRefresh([], {moduleId: "x", requestedAt: 123}, 999)[0].requestedAt, 123));
test("dequeue prefers earlier requested time on priority tie", () => assert.equal(model.dequeueExternalWidgetRefresh([{moduleId: "late", state: "queued", priority: 1, requestedAt: 20}, {moduleId: "early", state: "queued", priority: 1, requestedAt: 10}]).entry.moduleId, "early"));
test("dequeue leaves non queued entries in queue", () => assert.equal(model.dequeueExternalWidgetRefresh([{moduleId: "run", state: "running"}, {moduleId: "q", state: "queued"}]).queue[0].moduleId, "run"));
test("failure marker increments attempt", () => assert.equal(model.markExternalWidgetRefreshFailed([{moduleId: "x", attempt: 2}], "x")[0].attempt, 3));
test("success marker clears reason", () => assert.equal(model.markExternalWidgetRefreshSucceeded([{moduleId: "x", reason: "timeout"}], "x")[0].reason, ""));
test("cancel marker sanitizes reason", () => assert.equal(model.cancelExternalWidgetRefresh([{moduleId: "x"}], "x", "bad<> reason")[0].reason, "bad reason"));
test("state counts include every declared state", () => assert.deepEqual(Object.keys(model.countExternalWidgetRefreshStates([])), model.EXTERNAL_WIDGET_REFRESH_STATES));
test("concurrency clamps below one", () => assert.equal(model.normalizeExternalWidgetConcurrency(0), 1));
test("concurrency truncates fractional values", () => assert.equal(model.normalizeExternalWidgetConcurrency(2.9), 2));
test("concurrency defaults malformed values", () => assert.equal(model.normalizeExternalWidgetConcurrency("bad"), 2));
test("batch planner skips running entries", () => assert.deepEqual(model.planExternalWidgetRefreshBatch([{moduleId: "run", state: "running"}], 2).entries, []));
test("batch planner respects priority ordering", () => assert.deepEqual(model.planExternalWidgetRefreshBatch([{moduleId: "low", state: "queued", priority: 0}, {moduleId: "high", state: "queued", priority: 3}], 1).entries.map((x) => x.moduleId), ["high"]));
test("batch summary counts failed entries", () => assert.equal(model.summarizeExternalWidgetRefreshBatch([{moduleId: "x", state: "failed"}]).failed, 1));
test("batch summary counts cancelled entries", () => assert.equal(model.summarizeExternalWidgetRefreshBatch([{moduleId: "x", state: "cancelled"}]).cancelled, 1));
test("receipt carries attempt and normalized reason", () => assert.deepEqual(model.buildExternalWidgetRefreshReceipt({moduleId: "x", attempt: 2}, {ok: false, reason: "bad<> reason"}), {moduleId: "x", state: "failed", reason: "bad reason", attempt: 2}));
test("receipt defaults empty reason on success", () => assert.equal(model.buildExternalWidgetRefreshReceipt({moduleId: "x"}, {ok: true}).reason, ""));
test("receipt merge keeps latest duplicate", () => assert.equal(model.mergeExternalWidgetRefreshReceipts([{moduleId: "x", ok: false}, {moduleId: "x", ok: true}])[0].state, "succeeded"));
test("schedule decision accepts retryable stale snapshot", () => assert.equal(model.shouldScheduleExternalWidgetRefresh({moduleId: "x", health: "stale", timestamp: 999999}, 86400000, 1000000), true));
test("schedule decision rejects snapshot without module id", () => assert.equal(model.shouldScheduleExternalWidgetRefresh({health: "error"}, 60000, 1000), false));
test("clear queue removes queued and terminal entries", () => assert.deepEqual(model.clearExternalWidgetRefreshQueue([{moduleId: "r", state: "running"}, {moduleId: "q", state: "queued"}, {moduleId: "s", state: "succeeded"}]).map((x) => x.moduleId), ["r"]));

// T-4282~T-4331: external widget adapter observability, snapshot history and privacy/setup contracts.
test("catalog lookup trims a known module id", () => assert.equal(model.findExternalWidget(" external-local-time ").moduleId, "external-local-time"));
test("catalog lookup returns null for empty module id", () => assert.equal(model.findExternalWidget(""), null));
test("catalog listing returns normalized catalog entries", () => assert.equal(model.listExternalWidgetCatalog().length, model.EXTERNAL_WIDGET_CATALOG.length));
test("catalog listing returns detached entries", () => { const list = model.listExternalWidgetCatalog(); list[0].title = "changed"; assert.notEqual(model.listExternalWidgetCatalog()[0].title, "changed"); });
test("catalog filter matches description text", () => assert.equal(model.filterExternalWidgets([{moduleId: "x", description: "自建服务地址", title: "x"}], {query: "自建服务"}).length, 1));
test("catalog filter combines query and availability", () => assert.equal(model.filterExternalWidgets([{moduleId: "x", title: "X", availability: "external"}, {moduleId: "y", title: "X", availability: "reference"}], {query: "x", availability: "external"}).length, 1));
test("catalog filter combines category and platform", () => assert.equal(model.filterExternalWidgets([{moduleId: "x", category: "media", platforms: ["mobile"]}, {moduleId: "y", category: "media", platforms: ["desktop"]}], {category: "media", platform: "mobile"}).length, 1));
test("catalog filter accepts empty filter safely", () => assert.equal(model.filterExternalWidgets(model.listExternalWidgetCatalog(), {}).length, model.EXTERNAL_WIDGET_CATALOG.length));
test("catalog summary counts default catalog", () => assert.equal(model.summarizeExternalWidgets().total, model.EXTERNAL_WIDGET_CATALOG.length));
test("catalog summary counts credential requirements", () => assert.equal(model.summarizeExternalWidgets([{moduleId: "x", auth: "api-key"}]).needsConfiguration, 1));
test("catalog grouping preserves category map keys", () => assert.ok(model.groupExternalWidgets([{moduleId: "x", category: "media"}]).has("media")));
test("catalog grouping keeps insertion order within category", () => assert.deepEqual(model.groupExternalWidgets([{moduleId: "b", category: "media"}, {moduleId: "a", category: "media"}]).get("media").map((x) => x.moduleId), ["b", "a"]));
test("availability sorting places external after builtin", () => assert.deepEqual(model.sortExternalWidgetCatalog([{moduleId: "e", title: "E", availability: "external"}, {moduleId: "b", title: "B", availability: "builtin"}], "availability").map((x) => x.moduleId), ["b", "e"]));
test("availability sorting keeps stable ties", () => assert.deepEqual(model.sortExternalWidgetCatalog([{moduleId: "a", title: "A", availability: "external"}, {moduleId: "b", title: "B", availability: "external"}], "availability").map((x) => x.moduleId), ["a", "b"]));
test("privacy level rejects arbitrary values", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("secret"), "unknown"));
test("privacy level accepts location-only", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("location-only"), "location-only"));
test("setup steps order credentials before network notice", () => assert.deepEqual(model.getExternalWidgetSetupSteps({availability: "external", auth: "api-key", integration: "http"}), ["填写个人 API Key", "确认网络与隐私范围"]));
test("setup steps include endpoint and network requirements", () => assert.deepEqual(model.getExternalWidgetSetupSteps({availability: "external", auth: "user-endpoint", integration: "http"}), ["填写可信的自建服务地址", "确认网络与隐私范围"]));
test("setup steps include local service requirement", () => assert.deepEqual(model.getExternalWidgetSetupSteps({availability: "bridge", auth: "local-service"}), ["启动本机服务并确认回环端口"]));
test("setup steps include reference limitation last", () => assert.equal(model.getExternalWidgetSetupSteps({availability: "reference"}).at(-1), "仅阅读技术参考，不可直接添加"));
test("state list applies shared health option", () => assert.equal(model.normalizeExternalWidgetStateList([{moduleId: "x", availability: "external"}], {health: "healthy"})[0].health, "healthy"));
test("state list malformed input is empty", () => assert.deepEqual(model.normalizeExternalWidgetStateList(null), []));
test("snapshot builder carries configured readiness", () => assert.equal(model.buildExternalWidgetSnapshot({moduleId: "x", availability: "conditional"}, {configured: true}).status, "ready"));
test("snapshot builder carries timestamp", () => assert.equal(model.buildExternalWidgetSnapshot({moduleId: "x"}, {timestamp: 42}).timestamp, 42));
test("snapshot builder carries offline health", () => assert.equal(model.buildExternalWidgetSnapshot({moduleId: "x", availability: "external"}, {health: "offline"}).health, "offline"));
test("snapshot compatibility rejects missing module id", () => assert.equal(model.isExternalWidgetSnapshotCompatible({version: 1, health: "healthy", action: "add"}), false));
test("snapshot compatibility rejects oversized module id", () => assert.equal(model.isExternalWidgetSnapshotCompatible({version: 1, moduleId: "x".repeat(97), health: "healthy", action: "add"}), false));
test("snapshot compatibility rejects unknown health", () => assert.equal(model.isExternalWidgetSnapshotCompatible({version: 1, moduleId: "x", health: "wat", action: "add"}), false));
test("snapshot compatibility rejects unknown action", () => assert.equal(model.isExternalWidgetSnapshotCompatible({version: 1, moduleId: "x", health: "healthy", action: "wat"}), false));
test("snapshot serialization is deterministic", () => assert.equal(model.serializeExternalWidgetSnapshot({moduleId: "x", health: "healthy"}), model.serializeExternalWidgetSnapshot({health: "healthy", moduleId: "x"})));
test("snapshot parser normalizes valid payload", () => assert.equal(model.parseExternalWidgetSnapshot('{"version":1,"moduleId":"x","health":"healthy","action":"add"}').moduleId, "x"));
test("snapshot parser falls back for wrong version", () => assert.equal(model.parseExternalWidgetSnapshot('{"version":2,"moduleId":"x","health":"healthy","action":"add"}').moduleId, ""));
test("snapshot diff ignores timestamp-only changes", () => assert.equal(model.diffExternalWidgetSnapshots({moduleId: "x", timestamp: 1}, {moduleId: "x", timestamp: 2}).changed, false));
test("snapshot diff reports health change only", () => { const diff = model.diffExternalWidgetSnapshots({moduleId: "x", health: "healthy"}, {moduleId: "x", health: "stale"}); assert.deepEqual({changed: diff.changed, healthChanged: diff.healthChanged, statusChanged: diff.statusChanged}, {changed: true, healthChanged: true, statusChanged: false}); });
test("snapshot diff uses current module id first", () => assert.equal(model.diffExternalWidgetSnapshots({moduleId: "a"}, {moduleId: "b"}).moduleId, "b"));
test("snapshot transition marks unchanged snapshots", () => assert.equal(model.buildExternalWidgetTransition({moduleId: "x"}, {moduleId: "x"}).type, "unchanged"));
test("snapshot transition marks action changes", () => assert.equal(model.buildExternalWidgetTransition({moduleId: "x", action: "add"}, {moduleId: "x", action: "retry"}).type, "changed"));
test("history normalizer keeps only bounded newest records", () => assert.equal(model.normalizeExternalWidgetHistory(Array.from({length: 20}, (_, i) => ({moduleId: `m${i}`}))).length, 16));
test("history normalizer drops records without module id", () => assert.deepEqual(model.normalizeExternalWidgetHistory([{health: "healthy"}]), []));
test("append history ignores empty snapshot", () => assert.equal(model.appendExternalWidgetSnapshot([{moduleId: "x"}], {}).length, 1));
test("append history appends newest snapshot", () => assert.equal(model.appendExternalWidgetSnapshot([{moduleId: "x"}], {moduleId: "y"}).at(-1).moduleId, "y"));
test("append history evicts oldest record at capacity", () => { const history = Array.from({length: 16}, (_, i) => ({moduleId: `m${i}`})); assert.equal(model.appendExternalWidgetSnapshot(history, {moduleId: "new"})[0].moduleId, "m1"); });
test("trim history applies a smaller positive limit", () => assert.equal(model.trimExternalWidgetHistory([{moduleId: "a"}, {moduleId: "b"}], 1).length, 1));
test("trim history falls back to bounded default for invalid limit", () => assert.equal(model.trimExternalWidgetHistory([{moduleId: "a"}], "bad").length, 1));
test("latest history selects requested module", () => assert.equal(model.latestExternalWidgetSnapshot([{moduleId: "a"}, {moduleId: "b"}], "b").moduleId, "b"));
test("latest history returns null for missing module", () => assert.equal(model.latestExternalWidgetSnapshot([{moduleId: "a"}], "b"), null));
test("latest history without module selects final record", () => assert.equal(model.latestExternalWidgetSnapshot([{moduleId: "a"}, {moduleId: "b"}]).moduleId, "b"));
test("history selector filters by health", () => assert.deepEqual(model.selectExternalWidgetHistory([{moduleId: "a", health: "healthy"}, {moduleId: "b", health: "stale"}], "stale").map((x) => x.moduleId), ["b"]));
test("history selector applies a bounded limit", () => assert.equal(model.selectExternalWidgetHistory(Array.from({length: 5}, (_, i) => ({moduleId: `m${i}`, health: "stale"})), "stale", 2).length, 2));
test("history summary exposes latest record", () => assert.equal(model.summarizeExternalWidgetHistory([{moduleId: "x", health: "healthy"}]).latest.moduleId, "x"));
test("history summary counts each health", () => assert.equal(model.summarizeExternalWidgetHistory([{moduleId: "x", health: "healthy"}, {moduleId: "y", health: "error"}]).counts.error, 1));
test("history summary has zero latest for empty history", () => assert.equal(model.summarizeExternalWidgetHistory([]).latest, null));
test("snapshot merge accepts scalar and array inputs", () => assert.equal(model.mergeExternalWidgetSnapshots({moduleId: "x"}, [{moduleId: "y"}]).length, 2));
test("snapshot merge replaces equal timestamp with later source", () => assert.equal(model.mergeExternalWidgetSnapshots([{moduleId: "x", status: "old", timestamp: 1}], [{moduleId: "x", status: "new", timestamp: 1}])[0].status, "new"));
test("snapshot merge ignores empty module ids", () => assert.deepEqual(model.mergeExternalWidgetSnapshots({}, {moduleId: "x"}).map((x) => x.moduleId), ["x"]));
test("history serialization includes bounded snapshots", () => assert.equal(JSON.parse(model.serializeExternalWidgetHistory([{moduleId: "x"}])).version, 1));
test("history parser returns empty for malformed JSON", () => assert.deepEqual(model.parseExternalWidgetHistory("not-json"), []));
test("history parser normalizes valid snapshot list", () => assert.equal(model.parseExternalWidgetHistory('{"version":1,"snapshots":[{"moduleId":"x"}]}')[0].moduleId, "x"));

// T-4332~T-4381: external widget store state, actions, labels, privacy and diagnostics contracts.
test("store state normalizes builtin entry as directly addable", () => assert.deepEqual(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "builtin"}), {moduleId: "x", status: "builtin", canAdd: true, requiresSetup: false}));
test("store state normalizes external entry as directly addable", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "external"}).status, "external"));
test("store state conditional entry requires setup", () => assert.deepEqual(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "conditional"}), {moduleId: "x", status: "needs-config", canAdd: false, requiresSetup: true}));
test("store state conditional configured entry is ready", () => assert.deepEqual(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "conditional"}, {configured: true}), {moduleId: "x", status: "ready", canAdd: true, requiresSetup: false}));
test("store state bridge entry requires local service", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "bridge"}).status, "needs-local-service"));
test("store state bridge endpoint entry is ready", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "bridge"}, {endpointAvailable: true}).status, "ready"));
test("store state reference entry is never addable", () => assert.deepEqual(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "reference"}), {moduleId: "x", status: "reference", canAdd: false, requiresSetup: false}));
test("store state unknown availability falls back to reference", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: "x", availability: "wat"}).status, "reference"));
test("store state preserves normalized module id", () => assert.equal(model.resolveExternalWidgetStoreState({moduleId: " x "}).moduleId, "x"));
test("store action configures missing credentials", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-config", canAdd: false}), "configure"));
test("store action starts missing local service", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-local-service", canAdd: false}), "start-service"));
test("store action learns reference state", () => assert.equal(model.resolveExternalWidgetAction({status: "reference", canAdd: false}), "learn-more"));
test("store action retries explicit error", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: true}, {error: true}), "retry"));
test("store action retries stale health", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: true}, {health: "stale"}), "retry"));
test("store action retries error health", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: true}, {health: "error"}), "retry"));
test("store action adds healthy selectable state", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: true}, {health: "healthy"}), "add"));
test("store action learns non selectable state", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: false}), "learn-more"));
test("store action adds unknown status when explicitly addable", () => assert.equal(model.resolveExternalWidgetAction({status: "wat", canAdd: true}), "add"));
test("status label covers external state", () => assert.equal(model.resolveExternalWidgetStatusLabel("external"), "需联网"));
test("status label covers ready state", () => assert.equal(model.resolveExternalWidgetStatusLabel("ready"), "已就绪"));
test("status label covers config state", () => assert.equal(model.resolveExternalWidgetStatusLabel("needs-config"), "需要配置"));
test("status label covers local service state", () => assert.equal(model.resolveExternalWidgetStatusLabel("needs-local-service"), "需要本机服务"));
test("status label covers reference state", () => assert.equal(model.resolveExternalWidgetStatusLabel("reference"), "仅供参考"));
test("status label covers unavailable state", () => assert.equal(model.resolveExternalWidgetStatusLabel("unavailable"), "暂不可用"));
test("status label falls back for empty state", () => assert.equal(model.resolveExternalWidgetStatusLabel(""), "状态未知"));
test("described state exposes healthy add action", () => { const state = model.describeExternalWidgetStoreState({moduleId: "x", availability: "external"}, {health: "healthy"}); assert.deepEqual({status: state.status, action: state.action, canRetry: state.canRetry}, {status: "external", action: "add", canRetry: false}); });
test("described state exposes stale retry action", () => { const state = model.describeExternalWidgetStoreState({moduleId: "x", availability: "external"}, {health: "stale"}); assert.deepEqual({status: state.status, action: state.action, canRetry: state.canRetry}, {status: "external", action: "retry", canRetry: true}); });
test("described state exposes error retry action", () => assert.equal(model.describeExternalWidgetStoreState({moduleId: "x", availability: "external"}, {health: "error"}).action, "retry"));
test("described offline external state becomes unavailable", () => { const state = model.describeExternalWidgetStoreState({moduleId: "x", availability: "external"}, {health: "offline"}); assert.deepEqual({status: state.status, label: state.label, canRetry: state.canRetry}, {status: "unavailable", label: "暂不可用", canRetry: true}); });
test("described offline builtin state keeps builtin status", () => assert.equal(model.describeExternalWidgetStoreState({moduleId: "x", availability: "builtin"}, {health: "offline"}).status, "builtin"));
test("described state sanitizes diagnostic reason", () => assert.equal(model.describeExternalWidgetStoreState({moduleId: "x"}, {reason: "bad<> reason"}).reason, "bad reason"));
test("described state defaults unknown health", () => assert.equal(model.describeExternalWidgetStoreState({moduleId: "x"}).health, "unknown"));
test("described conditional state keeps configure precedence", () => { const state = model.describeExternalWidgetStoreState({moduleId: "x", availability: "conditional"}, {health: "stale"}); assert.deepEqual({status: state.status, action: state.action, requiresSetup: state.requiresSetup}, {status: "needs-config", action: "configure", requiresSetup: true}); });
test("described bridge state keeps start-service precedence", () => assert.equal(model.describeExternalWidgetStoreState({moduleId: "x", availability: "bridge"}, {health: "error"}).action, "start-service"));
test("selectable state accepts builtin", () => assert.equal(model.isExternalWidgetSelectable({status: "builtin", canAdd: true}), true));
test("selectable state accepts external", () => assert.equal(model.isExternalWidgetSelectable({status: "external", canAdd: true}), true));
test("selectable state accepts ready", () => assert.equal(model.isExternalWidgetSelectable({status: "ready", canAdd: true}), true));
test("selectable state rejects needs config", () => assert.equal(model.isExternalWidgetSelectable({status: "needs-config", canAdd: false}), false));
test("selectable state rejects reference even if addable", () => assert.equal(model.isExternalWidgetSelectable({status: "reference", canAdd: true}), false));
test("selectable state rejects unavailable even if addable", () => assert.equal(model.isExternalWidgetSelectable({status: "unavailable", canAdd: true}), false));
test("selectable state rejects null", () => assert.equal(model.isExternalWidgetSelectable(null), false));
test("state summary counts selectable items", () => assert.equal(model.summarizeExternalWidgetStates([{status: "external", canAdd: true}, {status: "reference", canAdd: false}]).selectable, 1));
test("state summary counts setup items", () => assert.equal(model.summarizeExternalWidgetStates([{status: "needs-config", requiresSetup: true}]).needsSetup, 1));
test("state summary counts unavailable items", () => assert.equal(model.summarizeExternalWidgetStates([{status: "unavailable"}]).unavailable, 1));
test("state summary counts reference items", () => assert.equal(model.summarizeExternalWidgetStates([{status: "reference"}]).reference, 1));
test("state summary counts healthy items", () => assert.equal(model.summarizeExternalWidgetStates([{health: "healthy"}]).healthy, 1));
test("state summary counts all degraded health values", () => assert.equal(model.summarizeExternalWidgetStates([{health: "error"}, {health: "stale"}, {health: "offline"}]).degraded, 3));
test("state summary ignores primitive values", () => assert.equal(model.summarizeExternalWidgetStates(["bad", 1, null]).total, 0));
test("guide link uses default document", () => assert.equal(model.buildExternalWidgetGuideLink("weather"), "docs/component-store-guide.md#weather"));
test("guide link sanitizes mixed-case anchor", () => assert.equal(model.buildExternalWidgetGuideLink("weather_01"), "docs/component-store-guide.md#weather01"));
test("guide link strips query and fragment", () => assert.equal(model.buildExternalWidgetGuideLink("x", "guide.md?raw=1#old"), "guide.md#x"));
test("guide link returns empty for empty base", () => assert.equal(model.buildExternalWidgetGuideLink("x", ""), ""));
test("guide link returns cleaned base when module empty", () => assert.equal(model.buildExternalWidgetGuideLink("", "guide.md?raw=1"), "guide.md"));
test("privacy level accepts none", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("none"), "none"));
test("privacy level accepts endpoint-only", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("endpoint-only"), "endpoint-only"));
test("privacy level accepts preferences-only", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("preferences-only"), "preferences-only"));
