const test = require("node:test");
const assert = require("node:assert/strict");
const model = require("../src/external-widget-model.js");

test("external catalog registers nine researched candidates", () => assert.equal(model.EXTERNAL_WIDGET_CATALOG.length, 9));
test("external catalog module ids are unique", () => {
    const ids = model.EXTERNAL_WIDGET_CATALOG.map((entry) => entry.moduleId);
    assert.equal(new Set(ids).size, ids.length);
});
test("external catalog root is immutable", () => assert.equal(Object.isFrozen(model.EXTERNAL_WIDGET_CATALOG), true));
test("external catalog entries are immutable", () => assert.ok(model.EXTERNAL_WIDGET_CATALOG.every(Object.isFrozen)));
test("external catalog platform arrays are immutable", () => assert.ok(model.EXTERNAL_WIDGET_CATALOG.every((entry) => Object.isFrozen(entry.platforms))));
test("external catalog size arrays are immutable", () => assert.ok(model.EXTERNAL_WIDGET_CATALOG.every((entry) => Object.isFrozen(entry.sizes))));
test("external categories remain fixed", () => assert.deepEqual(model.EXTERNAL_WIDGET_CATEGORIES, ["time", "weather", "trending", "holiday", "media", "activity"]));
test("external availability separates direct, setup, bridge and reference", () => assert.deepEqual(model.EXTERNAL_WIDGET_AVAILABILITY, ["builtin", "external", "conditional", "bridge", "reference"]));
test("external auth modes remain bounded", () => assert.deepEqual(model.EXTERNAL_WIDGET_AUTH, ["none", "api-key", "user-endpoint", "local-service"]));
test("external placements omit unsupported generic tablet", () => assert.equal(model.EXTERNAL_WIDGET_PLATFORMS.includes("tablet"), false));
test("external integrations remain bounded", () => assert.deepEqual(model.EXTERNAL_WIDGET_INTEGRATIONS, ["direct", "http", "local-bridge", "reference"]));

test("local time is available without network", () => {
    const item = model.findExternalWidget("external-local-time");
    assert.equal(item.availability, "builtin");
    assert.equal(item.auth, "none");
    assert.equal(item.privacy, "local-only");
});
test("Open-Meteo weather requires no API key", () => {
    const item = model.findExternalWidget("external-weather-open-meteo");
    assert.equal(item.auth, "none");
    assert.equal(item.integration, "http");
});
test("weather declares location-only privacy", () => assert.equal(model.findExternalWidget("external-weather-open-meteo").privacy, "location-only"));
test("DailyHot recommends a user endpoint", () => assert.equal(model.findExternalWidget("external-hot-news-dailyhot").auth, "user-endpoint"));
test("NewsNow recommends a user endpoint", () => assert.equal(model.findExternalWidget("external-news-newsnow").auth, "user-endpoint"));
test("holiday data requires no credentials", () => assert.equal(model.findExternalWidget("external-holiday-cn").auth, "none"));
test("TMDB is gated by an API key", () => assert.equal(model.findExternalWidget("external-movie-tmdb").auth, "api-key"));
test("Bangumi is available on all three plugin surfaces", () => assert.deepEqual(model.findExternalWidget("external-anime-bangumi").platforms, ["desktop", "sidebar", "mobile"]));
test("Bangumi is honestly labeled as a schedule", () => assert.equal(model.findExternalWidget("external-anime-bangumi").title, "每日放送"));
test("Bangumi catalog does not claim personalization", () => assert.match(model.findExternalWidget("external-anime-bangumi").description, /不宣称个性化推荐/));
test("ActivityWatch is local-service only", () => assert.equal(model.findExternalWidget("external-activitywatch-time").auth, "local-service"));
test("ActivityWatch does not claim mobile support", () => assert.equal(model.findExternalWidget("external-activitywatch-time").platforms.includes("mobile"), false));
test("native active-window probe remains reference only", () => assert.equal(model.findExternalWidget("external-active-window").availability, "reference"));

test("category normalizer keeps weather", () => assert.equal(model.normalizeExternalWidgetCategory("weather"), "weather"));
test("category normalizer safely falls back", () => assert.equal(model.normalizeExternalWidgetCategory("unknown"), "time"));
test("availability normalizer keeps bridge", () => assert.equal(model.normalizeExternalWidgetAvailability("bridge"), "bridge"));
test("availability normalizer never makes unknown sources ready", () => assert.equal(model.normalizeExternalWidgetAvailability("ready"), "reference"));
test("auth normalizer keeps api-key", () => assert.equal(model.normalizeExternalWidgetAuth("api-key"), "api-key"));
test("auth normalizer safely falls back", () => assert.equal(model.normalizeExternalWidgetAuth("oauth"), "none"));
test("integration normalizer keeps local bridge", () => assert.equal(model.normalizeExternalWidgetIntegration("local-bridge"), "local-bridge"));
test("integration normalizer safely falls back to reference", () => assert.equal(model.normalizeExternalWidgetIntegration("native"), "reference"));
test("platform normalizer deduplicates and filters", () => assert.deepEqual(model.normalizeExternalWidgetPlatforms(["desktop", "desktop", "tablet", "mobile"]), ["desktop", "mobile"]));
test("platform normalizer rejects malformed input", () => assert.deepEqual(model.normalizeExternalWidgetPlatforms("desktop"), []));
test("entry normalizer strips control characters", () => assert.equal(model.normalizeExternalWidget({title: " A\nB "}).title, "A B"));
test("entry normalizer bounds module ids", () => assert.equal(model.normalizeExternalWidget({moduleId: "x".repeat(200)}).moduleId.length, 96));
test("entry normalizer deduplicates sizes", () => assert.deepEqual(model.normalizeExternalWidget({sizes: ["small", "small", "medium"]}).sizes, ["small", "medium"]));
test("entry normalizer caps size declarations", () => assert.equal(model.normalizeExternalWidget({sizes: Array.from({length: 20}, (_, index) => `s${index}`)}).sizes.length, 8));

test("catalog listing returns defensive objects", () => {
    const listed = model.listExternalWidgetCatalog();
    listed[0].title = "changed";
    assert.notEqual(model.EXTERNAL_WIDGET_CATALOG[0].title, "changed");
});
test("catalog lookup returns null for unknown ids", () => assert.equal(model.findExternalWidget("missing"), null));
test("catalog lookup rejects malformed ids", () => assert.equal(model.findExternalWidget({}), null));
test("query filter matches provider names", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {query: "Open-Meteo"}).length, 1));
test("query filter is case insensitive", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {query: "TMDB"}).length, 1));
test("category filter selects media candidates", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {category: "media"}).length, 2));
test("availability filter selects conditional candidates", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {availability: "conditional"}).length, 1));
test("platform filter excludes desktop-only candidates on mobile", () => assert.equal(model.filterExternalWidgets(model.EXTERNAL_WIDGET_CATALOG, {platform: "mobile"}).some((entry) => entry.moduleId === "external-active-window"), false));
test("malformed filter input returns empty", () => assert.deepEqual(model.filterExternalWidgets(null, {query: "time"}), []));

test("catalog summary reports all availability classes", () => assert.deepEqual(model.summarizeExternalWidgets(), {
    total: 9, builtin: 1, external: 6, conditional: 1, bridge: 0, reference: 1, needsConfiguration: 5,
}));
test("catalog summary handles malformed input", () => assert.deepEqual(model.summarizeExternalWidgets(null), {
    total: 0, builtin: 0, external: 0, conditional: 0, bridge: 0, reference: 0, needsConfiguration: 0,
}));
test("catalog grouping exposes six semantic groups", () => assert.equal(model.groupExternalWidgets().size, 6));
test("catalog grouping keeps two media providers", () => assert.equal(model.groupExternalWidgets().get("media").length, 2));

test("builtin widgets can be added immediately", () => assert.deepEqual(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-local-time")), {
    moduleId: "external-local-time", status: "builtin", canAdd: true, requiresSetup: false,
}));
test("credential widgets require setup by default", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-movie-tmdb")).status, "needs-config"));
test("configured credential widgets become ready", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-movie-tmdb"), {configured: true}).status, "ready"));
test("production local bridges can be added and configured", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-activitywatch-time")).canAdd, true));
test("reference candidates can never be added", () => assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-active-window")).canAdd, false));
test("production feed widgets can be added before endpoint setup", () => {
    assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-hot-news-dailyhot")).canAdd, true);
    assert.equal(model.resolveExternalWidgetStoreState(model.findExternalWidget("external-news-newsnow")).canAdd, true);
});
test("production registers the ActivityWatch aggregate adapter", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /register\("external-activitywatch-time"/);
    assert.match(source, /loadActivityWatchSummary/);
    assert.match(source, /fetchActivityWatchViaKernel/);
});
test("ActivityWatch kernel proxy keeps a literal SiYuan endpoint", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /fetch\("\/api\/network\/forwardProxy"/);
    assert.match(source, /allowedActivityWatchUrl\(url\)/);
});
test("NewsNow catalog points to the maintained source repository", () => assert.equal(model.findExternalWidget("external-news-newsnow").sourceUrl, "https://github.com/ourongxing/newsnow"));

test("production registers the offline local clock adapter", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /register\("external-local-time"/);
    assert.match(source, /buildLocalTimeSnapshot/);
});
test("production clock refreshes on a single minute heartbeat", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /moduleId === "external-local-time"/);
    assert.match(source, /millisecondsToNextMinute/);
    assert.match(source, /document\.visibilityState !== "hidden"/);
});
test("production clock heartbeat is disposed with the panel", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /window\.clearTimeout\(homeClockTimer\)/);
    assert.match(source, /removeEventListener\("visibilitychange"/);
});
test("production registers and caches the Bangumi schedule adapter", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /register\("external-anime-bangumi"/);
    assert.match(source, /loadBangumiCalendar/);
    assert.match(source, /cacheTtlMs: 30 \* 60 \* 1000/);
});
test("production registers user-endpoint feed adapters without default URLs", () => {
    const fs = require("node:fs");
    const path = require("node:path");
    const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
    assert.match(source, /registerExternalFeed\("external-hot-news-dailyhot"/);
    assert.match(source, /registerExternalFeed\("external-news-newsnow"/);
    assert.match(source, /normalizeConfiguredFeedUrl/);
    assert.match(source, /loadConfiguredFeed/);
});

test("health normalizer keeps healthy", () => assert.equal(model.normalizeExternalWidgetHealth("healthy"), "healthy"));
test("health normalizer safely falls back", () => assert.equal(model.normalizeExternalWidgetHealth("broken"), "unknown"));
test("reason normalizer strips unsafe control symbols", () => assert.equal(model.normalizeExternalWidgetReason("bad<> reason"), "bad reason"));
test("needs config state resolves configure action", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-config"}), "configure"));
test("local service state resolves start action", () => assert.equal(model.resolveExternalWidgetAction({status: "needs-local-service"}), "start-service"));
test("reference state resolves learn action", () => assert.equal(model.resolveExternalWidgetAction({status: "reference"}), "learn-more"));
test("healthy add state resolves add action", () => assert.equal(model.resolveExternalWidgetAction({status: "builtin", canAdd: true}), "add"));
test("stale state resolves retry action", () => assert.equal(model.resolveExternalWidgetAction({status: "external", canAdd: true}, {health: "stale"}), "retry"));
test("status label is localized fallback text", () => assert.equal(model.resolveExternalWidgetStatusLabel("needs-config"), "需要配置"));
test("unknown status label is safe", () => assert.equal(model.resolveExternalWidgetStatusLabel("x"), "状态未知"));
test("offline external state becomes unavailable", () => assert.equal(model.describeExternalWidgetStoreState(model.findExternalWidget("external-weather-open-meteo"), {health: "offline"}).status, "unavailable"));
test("described state exposes retry for errors", () => assert.equal(model.describeExternalWidgetStoreState(model.findExternalWidget("external-weather-open-meteo"), {health: "error"}).canRetry, true));
test("described state keeps setup requirement", () => assert.equal(model.describeExternalWidgetStoreState(model.findExternalWidget("external-movie-tmdb")).requiresSetup, true));
test("selectable state accepts builtin", () => assert.equal(model.isExternalWidgetSelectable({status: "builtin", canAdd: true}), true));
test("unavailable state is not selectable", () => assert.equal(model.isExternalWidgetSelectable({status: "unavailable", canAdd: true}), false));
test("reference state is not selectable", () => assert.equal(model.isExternalWidgetSelectable({status: "reference", canAdd: false}), false));
test("state summary has fixed keys", () => assert.deepEqual(Object.keys(model.summarizeExternalWidgetStates([])).sort(), ["degraded", "healthy", "needsSetup", "reference", "selectable", "total", "unavailable"].sort()));
test("state summary counts selectable and setup", () => assert.deepEqual(model.summarizeExternalWidgetStates([{status: "builtin", canAdd: true}, {status: "needs-config", requiresSetup: true}]), {total: 2, selectable: 1, needsSetup: 1, unavailable: 0, reference: 0, healthy: 0, degraded: 0}));
test("state summary counts degraded health", () => assert.equal(model.summarizeExternalWidgetStates([{health: "stale"}]).degraded, 1));
test("catalog title sort is deterministic", () => assert.equal(model.sortExternalWidgetCatalog([{title: "Z"}, {title: "A"}])[0].title, "A"));
test("catalog availability sort prioritizes builtin", () => assert.equal(model.sortExternalWidgetCatalog([{title: "A", availability: "reference"}, {title: "B", availability: "builtin"}], "availability")[0].availability, "builtin"));
test("catalog sort handles malformed input", () => assert.deepEqual(model.sortExternalWidgetCatalog(null), []));
test("guide link includes sanitized module anchor", () => assert.equal(model.buildExternalWidgetGuideLink("external-weather-open-meteo"), "docs/component-store-guide.md#external-weather-open-meteo"));
test("guide link strips unsafe anchor characters", () => assert.equal(model.buildExternalWidgetGuideLink("a/b"), "docs/component-store-guide.md#ab"));
test("setup steps explain API key", () => assert.deepEqual(model.getExternalWidgetSetupSteps(model.findExternalWidget("external-movie-tmdb")), ["填写个人 API Key", "确认网络与隐私范围"]));
test("setup steps explain local service", () => assert.deepEqual(model.getExternalWidgetSetupSteps(model.findExternalWidget("external-activitywatch-time")), ["启动本机服务并确认回环端口"]));
test("setup steps explain reference limitation", () => assert.deepEqual(model.getExternalWidgetSetupSteps(model.findExternalWidget("external-active-window")), ["启动本机服务并确认回环端口", "仅阅读技术参考，不可直接添加"]));
test("privacy normalizer keeps local only", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("local-only"), "local-only"));
test("privacy normalizer rejects unknown value", () => assert.equal(model.resolveExternalWidgetPrivacyLevel("secret"), "unknown"));
test("state list normalizes every entry", () => assert.equal(model.normalizeExternalWidgetStateList([model.findExternalWidget("external-local-time")])[0].action, "add"));
test("state list malformed input is empty", () => assert.deepEqual(model.normalizeExternalWidgetStateList(null), []));
test("snapshot version is fixed", () => assert.equal(model.EXTERNAL_WIDGET_STATE_VERSION, 1));
test("snapshot history has bounded capacity", () => assert.equal(model.EXTERNAL_WIDGET_HISTORY_MAX, 16));
test("timestamp normalizer truncates values", () => assert.equal(model.normalizeExternalWidgetTimestamp(12.9), 12));
test("timestamp normalizer rejects negative values", () => assert.equal(model.normalizeExternalWidgetTimestamp(-1), 0));
test("snapshot builder carries module id", () => assert.equal(model.buildExternalWidgetSnapshot(model.findExternalWidget("external-local-time"), {timestamp: 42}).moduleId, "external-local-time"));
test("snapshot builder carries health", () => assert.equal(model.buildExternalWidgetSnapshot(model.findExternalWidget("external-local-time"), {health: "healthy"}).health, "healthy"));
test("snapshot normalizer fixes version", () => assert.equal(model.normalizeExternalWidgetSnapshot({version: 99}).version, 1));
test("snapshot compatibility accepts canonical shape", () => assert.equal(model.isExternalWidgetSnapshotCompatible(model.buildExternalWidgetSnapshot(model.findExternalWidget("external-local-time"))), true));
test("snapshot compatibility rejects unknown action", () => assert.equal(model.isExternalWidgetSnapshotCompatible({version: 1, moduleId: "x", health: "healthy", action: "hack"}), false));
test("snapshot serialization includes version", () => assert.match(model.serializeExternalWidgetSnapshot({moduleId: "x"}), /"version":1/));
test("snapshot parser round trips", () => assert.equal(model.parseExternalWidgetSnapshot(model.serializeExternalWidgetSnapshot({moduleId: "x", health: "healthy"})).moduleId, "x"));
test("snapshot parser isolates malformed JSON", () => assert.equal(model.parseExternalWidgetSnapshot("{bad").version, 1));
test("snapshot diff detects health change", () => assert.equal(model.diffExternalWidgetSnapshots({health: "healthy"}, {health: "stale"}).healthChanged, true));
test("snapshot diff detects no change", () => assert.equal(model.diffExternalWidgetSnapshots({health: "healthy"}, {health: "healthy"}).changed, false));
test("transition emits changed type", () => assert.equal(model.buildExternalWidgetTransition({status: "a"}, {status: "b"}).type, "changed"));
test("transition emits unchanged type", () => assert.equal(model.buildExternalWidgetTransition({status: "a"}, {status: "a"}).type, "unchanged"));
test("history normalizer keeps module snapshots", () => assert.equal(model.normalizeExternalWidgetHistory([{moduleId: "x"}]).length, 1));
test("history normalizer drops missing module ids", () => assert.deepEqual(model.normalizeExternalWidgetHistory([{health: "healthy"}]), []));
test("append history adds snapshot", () => assert.equal(model.appendExternalWidgetSnapshot([], {moduleId: "x"}).length, 1));
test("append history ignores empty snapshot", () => assert.deepEqual(model.appendExternalWidgetSnapshot([], {}), []));
test("append history keeps newest capacity", () => assert.equal(model.appendExternalWidgetSnapshot(Array.from({length: 20}, (_, i) => ({moduleId: String(i)})), {moduleId: "z"}).length, 16));
test("history trim applies requested limit", () => assert.equal(model.trimExternalWidgetHistory([{moduleId: "a"}, {moduleId: "b"}], 1).length, 1));
test("latest snapshot selects module", () => assert.equal(model.latestExternalWidgetSnapshot([{moduleId: "a"}, {moduleId: "b"}], "b").moduleId, "b"));
test("latest snapshot returns null when absent", () => assert.equal(model.latestExternalWidgetSnapshot([], "x"), null));
test("history selection filters health", () => assert.equal(model.selectExternalWidgetHistory([{moduleId: "a", health: "stale"}, {moduleId: "b", health: "healthy"}], "stale").length, 1));
test("history summary has fixed version", () => assert.equal(model.summarizeExternalWidgetHistory([]).version, 1));
test("history summary counts health", () => assert.equal(model.summarizeExternalWidgetHistory([{moduleId: "a", health: "stale"}]).counts.stale, 1));
test("snapshot merge prefers newest timestamp", () => assert.equal(model.mergeExternalWidgetSnapshots([{moduleId: "x", timestamp: 1}], [{moduleId: "x", timestamp: 2}])[0].timestamp, 2));
test("snapshot merge sorts module ids", () => assert.deepEqual(model.mergeExternalWidgetSnapshots([{moduleId: "b"}, {moduleId: "a"}]).map((x) => x.moduleId), ["a", "b"]));
test("history serialization round trips", () => assert.equal(model.parseExternalWidgetHistory(model.serializeExternalWidgetHistory([{moduleId: "x"}])).length, 1));
test("history parser rejects wrong version", () => assert.deepEqual(model.parseExternalWidgetHistory('{"version":2,"snapshots":[{"moduleId":"x"}]}'), []));
test("freshness constants remain fixed", () => assert.deepEqual(model.EXTERNAL_WIDGET_FRESHNESS, ["unknown", "fresh", "aging", "expired"]));
test("error kind constants remain fixed", () => assert.ok(model.EXTERNAL_WIDGET_ERROR_KINDS.includes("timeout")));
test("retry max is bounded", () => assert.equal(model.EXTERNAL_WIDGET_RETRY_MAX, 8));
test("health rank orders healthy highest", () => assert.ok(model.externalWidgetHealthRank("healthy") > model.externalWidgetHealthRank("stale")));
test("health comparison returns sign", () => assert.equal(model.compareExternalWidgetHealth("healthy", "error"), 1));
test("ttl clamps low values", () => assert.equal(model.normalizeExternalWidgetTtl(1), 60000));
test("ttl clamps high values", () => assert.equal(model.normalizeExternalWidgetTtl(999999999), 86400000));
test("snapshot age calculates elapsed time", () => assert.equal(model.externalWidgetSnapshotAge({timestamp: 1000}, 2000), 1000));
test("snapshot age missing timestamp is unknown", () => assert.equal(model.externalWidgetSnapshotAge({}, 2000), -1));
test("freshness marks recent snapshot fresh", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 2000, 2000), "fresh"));
test("freshness marks old snapshot expired", () => assert.equal(model.resolveExternalWidgetFreshness({timestamp: 1000}, 1000, 200000), "expired"));
test("retry attempt clamps max", () => assert.equal(model.normalizeExternalWidgetRetryAttempt(99), 8));
test("retry delay grows exponentially", () => assert.ok(model.externalWidgetRetryDelay(2) > model.externalWidgetRetryDelay(1)));
test("retry delay is bounded", () => assert.ok(model.externalWidgetRetryDelay(8) <= 300000));
test("stale health is retryable", () => assert.equal(model.shouldRetryExternalWidget("stale"), true));
test("healthy health is not retryable", () => assert.equal(model.shouldRetryExternalWidget("healthy"), false));
test("retry plan computes retry time", () => assert.equal(model.buildExternalWidgetRetryPlan({moduleId: "x", health: "stale", timestamp: 1}, {now: 100}).retryable, true));
test("retry plan stops at max attempt", () => assert.equal(model.buildExternalWidgetRetryPlan({moduleId: "x", health: "stale"}, {attempt: 8}).retryable, false));
test("error kind classifies timeout", () => assert.equal(model.classifyExternalWidgetError("request timeout"), "timeout"));
test("error kind classifies configuration", () => assert.equal(model.classifyExternalWidgetError("invalid api key"), "configuration"));
test("error kind classifies local service", () => assert.equal(model.classifyExternalWidgetError("ActivityWatch service unavailable"), "service"));
test("error kind defaults unknown", () => assert.equal(model.normalizeExternalWidgetErrorKind("wat"), "unknown"));
test("refresh due uses ttl", () => assert.equal(model.isExternalWidgetRefreshDue({timestamp: 1000}, 1000, 70000), true));
test("refresh next time is deterministic", () => assert.equal(model.nextExternalWidgetRefreshAt({timestamp: 1000}, 1000, 1500), 61000));
test("display snapshot keeps old healthy state on transient error", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "x", health: "healthy", timestamp: 1}, {moduleId: "x", health: "error", timestamp: 2}).health, "stale"));
test("display snapshot rejects older current state", () => assert.equal(model.selectExternalWidgetDisplaySnapshot({moduleId: "x", timestamp: 2}, {moduleId: "x", timestamp: 1}).timestamp, 2));
test("snapshot health sorting is deterministic", () => assert.equal(model.sortExternalWidgetSnapshotsByHealth([{moduleId: "a", health: "error"}, {moduleId: "b", health: "healthy"}])[0].moduleId, "b"));
test("snapshot grouping exposes every health", () => assert.equal(model.groupExternalWidgetSnapshotsByHealth([]).size, model.EXTERNAL_WIDGET_HEALTH.length));
test("refresh summary counts due items", () => assert.equal(model.summarizeExternalWidgetRefresh([{moduleId: "x", timestamp: 1}], 1000, 70000).due, 1));
test("refresh summary keeps fixed version", () => assert.equal(model.summarizeExternalWidgetRefresh([]).version, 1));
test("refresh states include queued and running", () => assert.ok(model.EXTERNAL_WIDGET_REFRESH_STATES.includes("queued") && model.EXTERNAL_WIDGET_REFRESH_STATES.includes("running")));
test("refresh queue max is bounded", () => assert.equal(model.EXTERNAL_WIDGET_REFRESH_QUEUE_MAX, 16));
test("refresh state normalizer falls back idle", () => assert.equal(model.normalizeExternalWidgetRefreshState("wat"), "idle"));
test("priority clamps to range", () => assert.equal(model.normalizeExternalWidgetPriority(9), 3));
test("refresh entry keeps module id", () => assert.equal(model.normalizeExternalWidgetRefreshEntry({moduleId: "x"}).moduleId, "x"));
test("refresh queue drops malformed entries", () => assert.deepEqual(model.normalizeExternalWidgetRefreshQueue([{}]), []));
test("enqueue adds queued entry", () => assert.equal(model.enqueueExternalWidgetRefresh([], {moduleId: "x"}).length, 1));
test("enqueue deduplicates module ids", () => assert.equal(model.enqueueExternalWidgetRefresh([{moduleId: "x", priority: 1}], {moduleId: "x", priority: 2}).length, 1));
test("enqueue keeps higher priority", () => assert.equal(model.enqueueExternalWidgetRefresh([{moduleId: "x", priority: 1}], {moduleId: "x", priority: 2})[0].priority, 2));
test("dequeue selects queued entry", () => assert.equal(model.dequeueExternalWidgetRefresh([{moduleId: "x", state: "queued"}]).entry.state, "running"));
test("dequeue returns null when empty", () => assert.equal(model.dequeueExternalWidgetRefresh([]).entry, null));
test("dequeue prefers higher priority", () => assert.equal(model.dequeueExternalWidgetRefresh([{moduleId: "a", state: "queued", priority: 1}, {moduleId: "b", state: "queued", priority: 3}]).entry.moduleId, "b"));
test("update refresh entry changes state", () => assert.equal(model.updateExternalWidgetRefreshEntry([{moduleId: "x"}], "x", {state: "running"})[0].state, "running"));
test("success marker sets succeeded", () => assert.equal(model.markExternalWidgetRefreshSucceeded([{moduleId: "x"}], "x")[0].state, "succeeded"));
test("failure marker sets failed", () => assert.equal(model.markExternalWidgetRefreshFailed([{moduleId: "x"}], "x", "timeout")[0].state, "failed"));
test("cancel marker sets cancelled", () => assert.equal(model.cancelExternalWidgetRefresh([{moduleId: "x"}], "x")[0].state, "cancelled"));
test("remove refresh entry deletes module", () => assert.deepEqual(model.removeExternalWidgetRefresh([{moduleId: "x"}], "x"), []));
test("refresh state counts fixed shape", () => assert.equal(Object.keys(model.countExternalWidgetRefreshStates([])).length, model.EXTERNAL_WIDGET_REFRESH_STATES.length));
test("concurrency clamps range", () => assert.equal(model.normalizeExternalWidgetConcurrency(9), 4));
test("batch planner respects concurrency", () => assert.equal(model.planExternalWidgetRefreshBatch([{moduleId: "a", state: "queued"}, {moduleId: "b", state: "queued"}, {moduleId: "c", state: "queued"}], 2).entries.length, 2));
test("batch planner removes selected entries", () => assert.equal(model.planExternalWidgetRefreshBatch([{moduleId: "a", state: "queued"}], 1).queue.length, 0));
test("batch summary counts running", () => assert.equal(model.summarizeExternalWidgetRefreshBatch([{moduleId: "a", state: "running"}]).running, 1));
test("batch summary counts queued remainder", () => assert.equal(model.summarizeExternalWidgetRefreshBatch([], [{moduleId: "a", state: "queued"}]).queued, 1));
test("receipt marks success", () => assert.equal(model.buildExternalWidgetRefreshReceipt({moduleId: "x"}, {ok: true}).state, "succeeded"));
test("receipt marks cancellation", () => assert.equal(model.buildExternalWidgetRefreshReceipt({moduleId: "x"}, {cancelled: true}).state, "cancelled"));
test("receipt merge deduplicates", () => assert.equal(model.mergeExternalWidgetRefreshReceipts([{moduleId: "x"}, {moduleId: "x"}]).length, 1));
test("receipt merge sorts ids", () => assert.deepEqual(model.mergeExternalWidgetRefreshReceipts([{moduleId: "b"}, {moduleId: "a"}]).map((x) => x.moduleId), ["a", "b"]));
test("schedule decision accepts due snapshot", () => assert.equal(model.shouldScheduleExternalWidgetRefresh({moduleId: "x", timestamp: 1}, 1000, 70000), true));
test("schedule decision rejects fresh snapshot", () => assert.equal(model.shouldScheduleExternalWidgetRefresh({moduleId: "x", timestamp: 1000, health: "healthy"}, 100000, 2000), false));
test("clear queue keeps running entries", () => assert.equal(model.clearExternalWidgetRefreshQueue([{moduleId: "x", state: "running"}, {moduleId: "y"}]).length, 1));
