const test = require('node:test');
const assert = require('node:assert/strict');
const model = require('../src/home-store-model.js');
const card = (id, overrides = {}) => ({moduleId: id, search: id, category: 'builtin', availability: 'ready', integration: 'offline', added: false, configurable: false, ...overrides});

test('batch action normalization defaults add', () => assert.equal(model.normalizeHomeStoreBatchAction('bad'), 'add'));
test('ready unadded card is eligible for add', () => assert.equal(model.isHomeStoreBatchEligible(card('a'), 'add'), true));
test('added card is skipped for add', () => assert.equal(model.isHomeStoreBatchEligible(card('a', {added: true}), 'add'), false));
test('external card is skipped for add', () => assert.equal(model.isHomeStoreBatchEligible(card('a', {availability: 'external'}), 'add'), false));
test('conditional card is skipped for add', () => assert.equal(model.isHomeStoreBatchEligible(card('a', {availability: 'conditional'}), 'add'), false));
test('added card is eligible for remove', () => assert.equal(model.isHomeStoreBatchEligible(card('a', {added: true}), 'remove'), true));
test('unadded card is skipped for remove', () => assert.equal(model.isHomeStoreBatchEligible(card('a'), 'remove'), false));
test('configurable added card is eligible for configure', () => assert.equal(model.isHomeStoreBatchEligible(card('a', {added: true, configurable: true}), 'configure'), true));
test('nonconfigurable card is skipped for configure', () => assert.equal(model.isHomeStoreBatchEligible(card('a', {added: true}), 'configure'), false));
test('partition separates eligible and skipped', () => assert.deepEqual(model.partitionHomeStoreBatchCards([card('a'), card('b', {availability: 'external'})], ['a', 'b'], 'add'), {eligible: ['a'], skipped: ['b']}));
test('partition ignores unselected cards', () => assert.deepEqual(model.partitionHomeStoreBatchCards([card('a'), card('b')], ['a'], 'add').eligible, ['a']));
test('batch result counts accepted', () => assert.deepEqual(model.buildHomeStoreBatchResult(['a'], ['b'], 'add'), {action: 'add', accepted: 1, skipped: 1, ids: ['a'], skippedIds: ['b'], ok: true}));
test('batch result text substitutes counts', () => assert.equal(model.buildHomeStoreBatchResultText({action: 'add', accepted: 2, skipped: 1}, {add: '成功 {accepted}，跳过 {skipped}'}), '成功 2，跳过 1'));
test('batch action label is localized', () => assert.equal(model.resolveHomeStoreBatchActionLabel('remove', {remove: '批量移除'}), '批量移除'));
test('batch selection hint includes skipped count', () => assert.match(model.buildHomeStoreBatchSelectionHint(['a', 'b'], [card('a'), card('b', {availability: 'external'})]).text, /跳过 1/));
test('batch focus keeps selection after partial result', () => assert.equal(model.resolveHomeStoreBatchFocusAfterResult({accepted: 1, skipped: 1}), 'selection'));
test('batch focus uses summary after success', () => assert.equal(model.resolveHomeStoreBatchFocusAfterResult({accepted: 1, skipped: 0}), 'summary'));
test('selection is retained after skipped items', () => assert.equal(model.shouldKeepHomeStoreSelectionAfterBatch({skipped: 1}), true));
test('selection clears after complete result', () => assert.equal(model.shouldKeepHomeStoreSelectionAfterBatch({skipped: 0}), false));
test('batch error normalizes values', () => assert.equal(model.normalizeHomeStoreBatchError('bad'), 'none'));
test('batch error detects failed result', () => assert.equal(model.resolveHomeStoreBatchError(0, 2), 'failed'));
test('batch error detects partial result', () => assert.equal(model.resolveHomeStoreBatchError(1, 2), 'partial'));
test('batch error detects success result', () => assert.equal(model.resolveHomeStoreBatchError(2, 0), 'none'));
test('batch receipt has stable shape', () => assert.deepEqual(model.buildHomeStoreBatchReceipt({action: 'add', accepted: 1, skipped: 0}, 'none'), {action: 'add', accepted: 1, skipped: 0, error: 'none'}));
test('batch receipt clamps malformed counts', () => assert.deepEqual(model.buildHomeStoreBatchReceipt({action: 'add', accepted: -2, skipped: 3}, 'partial'), {action: 'add', accepted: 0, skipped: 3, error: 'partial'}));
test('batch result dedupes accepted ids', () => assert.equal(model.buildHomeStoreBatchResult(['a', 'a'], [], 'add').accepted, 1));
test('batch result caps accepted ids', () => assert.equal(model.buildHomeStoreBatchResult(Array.from({length: 140}, (_, i) => `x${i}`), [], 'add').accepted, 128));
test('batch selection hint uses configure action', () => assert.equal(model.buildHomeStoreBatchSelectionHint(['a'], [card('a', {added: true, configurable: true})], 'configure').action, 'configure'));
test('batch selection hint skips missing card ids', () => assert.equal(model.buildHomeStoreBatchSelectionHint(['missing'], [card('a')]).accepted, 0));
test('batch action label falls back safely', () => assert.equal(model.resolveHomeStoreBatchActionLabel('bad'), '批量添加'));
test('batch partition handles malformed cards', () => assert.deepEqual(model.partitionHomeStoreBatchCards(null, ['a']), {eligible: [], skipped: []}));
