const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(root, "src", "index.ts"), "utf8");

test("widget store previews refresh real data and separate size selection from commit", () => {
    assert.match(source, /controller\.mount\(\);\s*const markPreviewReady = \(\) =>/);
    assert.match(source, /homeStoreApplySize/);
    assert.match(source, /homeStoreAdd/);
    assert.match(source, /tile\.dataset\.size = sizeKey/);
    assert.match(source, /sw-home-store__add/);
    assert.match(source, /selectedTile\?\.classList\.remove\("is-selected"\)/);
    assert.match(source, /sw-home-store__availability/);
    assert.match(source, /homeStoreAvailabilityConditional/);
    assert.match(source, /homeStoreTabConditional/);
    assert.match(source, /card\.dataset\.availability === availabilityFilter/);
    assert.match(source, /listModules\(device\)\.forEach/);
    assert.match(source, /sw-home-store__group/);
    assert.match(source, /grid\.classList\.toggle\("fn__none", !visible\)/);
    assert.match(source, /!added && def\.availability === "conditional"/);
    assert.match(source, /homeStoreConditionalHint/);
    assert.match(source, /addedInstance && Array\.isArray\(def\.configSchema\)/);
    assert.match(source, /sw-home-store__configure/);
    assert.match(source, /openHomeConfigForm\(addedInstance, def\.configSchema/);
    assert.match(source, /homeStoreSupportedSurfaces/);
    assert.match(source, /sw-home-store__support/);
    assert.match(source, /selectedTile = tile;\s*tile\.classList\.add\("is-selected"\)/);
    assert.match(source, /resolveWidgetCatalogState\(\[\.\.\.activeIds\], \[\.\.\.instanceByModule\.keys\(\)\]\)/);
    assert.match(source, /homeStoreProviderUnavailable/);
    assert.match(source, /sw-home-store__remove-unavailable/);
    assert.match(source, /homeModuleChangeListeners\.add\(handleModuleChange\)/);
    assert.match(source, /homeModuleChangeListeners\.delete\(handleModuleChange\)/);
    assert.match(source, /btn\.dataset\.tabFilter = tab\.category \|\| "all"/);
    assert.match(source, /addedOnly = activeTab\?\.dataset\.tabAdded === "true"/);
    assert.match(source, /card\.dataset\.added === "true"/);
    assert.match(source, /homeStoreTabAdded/);
    assert.match(source, /homeStoreNoResults/);
    assert.match(source, /let storeQuery = ""/);
    assert.match(source, /let storeTab = "all"/);
    assert.match(source, /let storeSort = "relevance"/);
    assert.match(source, /homeStoreSortLabel/);
    assert.match(source, /sortHomeStoreCards/);
    assert.match(source, /matchesHomeStoreTokens/);
    assert.match(source, /buildHomeStoreTabCounts/);
    assert.match(source, /card\.dataset\.moduleId = moduleId/);
    assert.match(source, /btn\.dataset\.tabLabel = tab\.label/);
    assert.match(source, /homeStoreGroupJournal/);
    assert.match(source, /"journal-calendar", "writing-streak"/);
    assert.match(source, /readyHeading\.dataset\.section = "ready"/);
    assert.match(source, /heading\.dataset\.section === "ready"/);
    assert.match(source, /homeStoreGroupPluginAuthor/);
    assert.match(source, /else if \(registration\.registered\) \{\s*this\.homeModuleOpens\.delete\(moduleId\)/);
    assert.match(source, /clearDeferredRefreshes\(\)/);
    assert.match(source, /panelEventCleanup\?\.\(\)/);
    assert.match(source, /field\.type === "document"/);
    assert.match(source, /this\.currentDocumentSetEntries\(\)\.slice\(0, 40\)/);
    assert.match(source, /input\.type = "date"/);
    assert.match(source, /input\.min = "1900-01-01"/);
    assert.match(source, /input:invalid, select:invalid/);
    assert.match(source, /emptyOption\.textContent = this\.i18n\.notebookPlaceholder/);
    assert.match(source, /homeConfigUnavailableValue/);
    assert.match(source, /homeConfigReset/);
    assert.match(source, /sw-home__empty-store/);
    assert.match(source, /homeEmptyOpenStore/);
    assert.match(source, /tabBar\.setAttribute\("role", "tablist"\)/);
    assert.match(source, /btn\.setAttribute\("role", "tab"\)/);
    assert.match(source, /tile\.setAttribute\("aria-pressed"/);
    assert.match(source, /homeStoreClearFilters/);
    assert.match(source, /searchInput\.focus\(\)/);
    assert.match(source, /includeState: true/);
    assert.match(source, /configuredModuleIds/);
    assert.match(source, /homeStoreResultSummary/);
    assert.match(source, /homeStoreChooseSize/);
    assert.match(source, /homeStoreStatusCurrent/);
    assert.match(source, /collapsedGroups = new Set/);
    assert.match(source, /homeStoreCollapseGroup/);
    assert.match(source, /homeStoreExpandGroup/);
    assert.match(source, /sw-home-store__remove/);
    assert.match(source, /PREVIEW_KINDS/);
    assert.match(source, /p-calendar-grid/);
});
