const test = require('node:test');
const assert = require('node:assert/strict');
const model = require('../src/home-store-model.js');

test('dependency catalog includes all non-core providers', () => assert.deepEqual(Object.keys(model.DEPENDENCY_INFO).sort(), ['checkin-summary','external-activitywatch-time','external-anime-bangumi','external-hot-news-dailyhot','external-news-newsnow','external-weather-open-meteo','journal-calendar','plugin-commands']));
test('weather dependency is external api', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').kind, 'external-api'));
test('activitywatch dependency requires local service', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').kind, 'local-service'));
test('dailyhot dependency points to install project', () => assert.match(model.resolveHomeStoreDependencyInfo('external-hot-news-dailyhot').installUrl, /github\.com/));
test('newsnow dependency points to install project', () => assert.match(model.resolveHomeStoreDependencyInfo('external-news-newsnow').projectUrl, /newsnow/));
test('holiday overlay is optional', () => assert.equal(model.resolveHomeStoreDependencyInfo('journal-calendar').required, false));
test('checkin dependency is plugin kind', () => assert.equal(model.resolveHomeStoreDependencyInfo('checkin-summary').kind, 'plugin'));
test('unknown dependency returns null', () => assert.equal(model.resolveHomeStoreDependencyInfo('missing'), null));
test('dependency notice marks required', () => assert.match(model.buildHomeStoreDependencyNotice('external-activitywatch-time').notice, /需要前置依赖/));
test('dependency notice marks optional', () => assert.match(model.buildHomeStoreDependencyNotice('journal-calendar').notice, /可选数据源/));
test('dependency notice supports labels', () => assert.match(model.buildHomeStoreDependencyNotice('external-weather-open-meteo', {required: '前置'}).notice, /^前置/));
test('dependency list filters unknown modules', () => assert.equal(model.listHomeStoreDependencies(['external-weather-open-meteo', 'missing']).length, 1));
test('dependency info is defensive copy', () => { const info = model.resolveHomeStoreDependencyInfo('external-weather-open-meteo'); info.name = 'changed'; assert.equal(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').name, 'Open-Meteo'); });
test('dependency kind normalization defaults unknown', () => assert.equal(model.normalizeHomeStoreDependencyKind('bad'), 'unknown'));
test('weather setup states no api key', () => assert.match(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').setup, /API Key/));
test('activitywatch setup states desktop restriction', () => assert.match(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').setup, /127\.0\.0\.1/));
test('dailyhot setup warns no public demo', () => assert.match(model.resolveHomeStoreDependencyInfo('external-hot-news-dailyhot').setup, /公共演示/));
test('newsnow setup requires api path', () => assert.match(model.resolveHomeStoreDependencyInfo('external-news-newsnow').setup, /api\/s/));
test('dependency platforms expose mobile restriction', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').platforms, 'desktop/sidebar'));
test('dependency network boundary is explicit', () => assert.match(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').network, /HTTPS/));
test('plugin command dependency is optional', () => assert.equal(model.resolveHomeStoreDependencyInfo('plugin-commands').required, false));
test('bangumi dependency is required', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-anime-bangumi').required, true));
test('dependency list defaults to catalog', () => assert.equal(model.listHomeStoreDependencies().length, 8));
test('notice is bounded', () => assert.ok(model.buildHomeStoreDependencyNotice('external-weather-open-meteo').notice.length < 300));
test('install url is nonempty for activitywatch', () => assert.match(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').installUrl, /^https:/));
test('project url is nonempty for holiday data', () => assert.match(model.resolveHomeStoreDependencyInfo('journal-calendar').projectUrl, /^https:/));
test('checkin notice avoids fake repository claim', () => assert.match(model.resolveHomeStoreDependencyInfo('checkin-summary').setup, /无法核实|协议/));
test('dependency info includes provider name', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-news-newsnow').name, 'NewsNow'));
test('dependency info includes setup field', () => assert.ok(model.resolveHomeStoreDependencyInfo('external-anime-bangumi').setup));
test('dependency info includes privacy network boundary', () => assert.ok(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').network));
test('optional dependency notice remains visible', () => assert.ok(model.buildHomeStoreDependencyNotice('journal-calendar')));
test('dependency list preserves requested order', () => assert.deepEqual(model.listHomeStoreDependencies(['journal-calendar','external-weather-open-meteo']).map((x) => x.moduleId), ['journal-calendar','external-weather-open-meteo']));
