const test = require('node:test');
const assert = require('node:assert/strict');
const model = require('../src/home-store-model.js');

const card = (overrides = {}) => ({search: '日记 today-journal', category: 'builtin', availability: 'ready', added: false, ...overrides});

test('store tab keys are fixed and ordered', () => assert.deepEqual(model.getHomeStoreTabKeys(), ['all', 'builtin', 'plugin', 'conditional', 'added']));
test('invalid tab falls back to all', () => assert.equal(model.normalizeHomeStoreTab('x'), 'all'));
test('device normalization falls back to desktop', () => assert.equal(model.normalizeHomeStoreDevice('tablet'), 'desktop'));
test('known devices normalize', () => assert.equal(model.normalizeHomeStoreDevice('mobile'), 'mobile'));
test('category normalization keeps builtin', () => assert.equal(model.normalizeHomeStoreCategory('builtin'), 'builtin'));
test('invalid category falls back builtin', () => assert.equal(model.normalizeHomeStoreCategory('x'), 'builtin'));
test('availability normalization keeps conditional', () => assert.equal(model.normalizeHomeStoreAvailability('conditional'), 'conditional'));
test('invalid availability falls back ready', () => assert.equal(model.normalizeHomeStoreAvailability('x'), 'ready'));
test('query normalization trims controls and case', () => assert.equal(model.normalizeHomeStoreQuery('  TODAY\n'), 'today'));
test('query normalization bounds oversized text', () => assert.equal(model.normalizeHomeStoreQuery('x'.repeat(200)).length, 128));
test('all filter is orthogonal', () => assert.deepEqual(model.resolveHomeStoreFilter('all'), {tab: 'all', category: 'all', availability: '', addedOnly: false}));
test('builtin filter selects category', () => assert.equal(model.resolveHomeStoreFilter('builtin').category, 'builtin'));
test('plugin filter selects category', () => assert.equal(model.resolveHomeStoreFilter('plugin').category, 'plugin'));
test('conditional filter does not select category', () => assert.deepEqual(model.resolveHomeStoreFilter('conditional'), {tab: 'conditional', category: 'all', availability: 'conditional', addedOnly: false}));
test('added filter selects state only', () => assert.equal(model.resolveHomeStoreFilter('added').addedOnly, true));
test('matching card accepts empty query', () => assert.equal(model.matchesHomeStoreCard(card(), '', model.resolveHomeStoreFilter('all')), true));
test('matching card finds case-insensitive text', () => assert.equal(model.matchesHomeStoreCard(card(), 'TODAY', model.resolveHomeStoreFilter('all')), true));
test('matching card rejects absent text', () => assert.equal(model.matchesHomeStoreCard(card(), 'missing', model.resolveHomeStoreFilter('all')), false));
test('matching card applies builtin filter', () => assert.equal(model.matchesHomeStoreCard(card(), '', model.resolveHomeStoreFilter('builtin')), true));
test('matching card rejects wrong category', () => assert.equal(model.matchesHomeStoreCard(card({category: 'plugin'}), '', model.resolveHomeStoreFilter('builtin')), false));
test('matching card applies conditional filter', () => assert.equal(model.matchesHomeStoreCard(card({availability: 'conditional'}), '', model.resolveHomeStoreFilter('conditional')), true));
test('matching card rejects ready under conditional filter', () => assert.equal(model.matchesHomeStoreCard(card(), '', model.resolveHomeStoreFilter('conditional')), false));
test('matching card applies added filter', () => assert.equal(model.matchesHomeStoreCard(card({added: true}), '', model.resolveHomeStoreFilter('added')), true));
test('matching card rejects unadded under added filter', () => assert.equal(model.matchesHomeStoreCard(card(), '', model.resolveHomeStoreFilter('added')), false));
test('filter returns only matches', () => assert.equal(model.filterHomeStoreCards([card(), card({search: '插件', category: 'plugin'})], '插件', model.resolveHomeStoreFilter('all')).length, 1));
test('filter malformed cards safely returns empty', () => assert.deepEqual(model.filterHomeStoreCards(null, '', model.resolveHomeStoreFilter('all')), []));
test('summary counts total visible and added', () => assert.deepEqual(model.summarizeHomeStoreCards([card(), card({added: true})], '', model.resolveHomeStoreFilter('all')), {total: 2, visible: 2, added: 1}));
test('summary respects filter', () => assert.equal(model.summarizeHomeStoreCards([card(), card({category: 'plugin'})], '', model.resolveHomeStoreFilter('builtin')).visible, 1));
test('search text combines definition and id', () => assert.match(model.buildHomeStoreSearchText({title: '标题', description: '描述'}, 'module-id'), /module-id/));
test('preview calendar kind is semantic', () => assert.equal(model.resolveHomeStorePreviewKind('journal-calendar', 'builtin'), 'calendar'));
test('preview tasks kind is semantic', () => assert.equal(model.resolveHomeStorePreviewKind('today-tasks', 'builtin'), 'tasks'));
test('offline local time preview uses stat semantics', () => assert.equal(model.resolveHomeStorePreviewKind('external-local-time', 'builtin'), 'stat'));
test('weather preview has a dedicated visual kind', () => assert.equal(model.resolveHomeStorePreviewKind('external-weather-open-meteo', 'builtin'), 'weather'));
test('Bangumi preview has a dedicated media kind', () => assert.equal(model.resolveHomeStorePreviewKind('external-anime-bangumi', 'builtin'), 'media'));
test('media preview kind survives normalization', () => assert.equal(model.normalizeHomeStorePreviewKind('media'), 'media'));
test('weather preview kind survives normalization', () => assert.equal(model.normalizeHomeStorePreviewKind('weather'), 'weather'));
test('store source info exposes Bangumi network metadata', () => assert.deepEqual(model.resolveHomeStoreSourceInfo('external-anime-bangumi'), {providerName: 'Bangumi', integration: 'http', privacy: 'none'}));
test('store source info exposes location-only weather privacy', () => assert.equal(model.resolveHomeStoreSourceInfo('external-weather-open-meteo').privacy, 'location-only'));
test('store source info returns defensive copies', () => {
    const info = model.resolveHomeStoreSourceInfo('external-local-time');
    info.providerName = 'changed';
    assert.equal(model.resolveHomeStoreSourceInfo('external-local-time').providerName, 'SiYuan runtime');
});
test('store source info rejects unknown widgets', () => assert.equal(model.resolveHomeStoreSourceInfo('missing'), null));
test('unknown plugin preview uses plugin kind', () => assert.equal(model.resolveHomeStorePreviewKind('x', 'plugin'), 'plugin'));
test('unknown builtin preview uses list kind', () => assert.equal(model.resolveHomeStorePreviewKind('x', 'builtin'), 'list'));
test('preview kind normalization rejects unknown', () => assert.equal(model.normalizeHomeStorePreviewKind('x'), 'list'));
test('card status defaults supported size', () => assert.deepEqual(model.resolveHomeStoreCardStatus(false, 'x', ['small', 'medium']), {added: false, sizeKey: 'small', status: 'not-added'}));
test('card status keeps valid current size', () => assert.equal(model.resolveHomeStoreCardStatus(true, 'medium', ['small', 'medium']).sizeKey, 'medium'));
test('size selection keeps valid current', () => assert.deepEqual(model.resolveHomeStoreSizeSelection('large', ['small', 'large']).selected, 'large'));
test('size selection falls back first option', () => assert.equal(model.resolveHomeStoreSizeSelection('x', ['small', 'large']).selected, 'small'));
test('size support accepts listed size', () => assert.equal(model.isHomeStoreSizeSupported('small', ['small']), true));
test('size support rejects unlisted size', () => assert.equal(model.isHomeStoreSizeSupported('large', ['small']), false));
test('surface normalization removes invalid and duplicate devices', () => assert.deepEqual(model.normalizeHomeStoreSupportedSurfaces(['desktop', 'desktop', 'x'], 'mobile'), ['desktop']));
test('conditional helper identifies conditional card', () => assert.equal(model.isHomeStoreConditional(card({availability: 'conditional'})), true));
test('external helper identifies external card', () => assert.equal(model.isHomeStoreExternal(card({availability: 'external'})), true));
test('section visibility requires positive count', () => assert.equal(model.shouldShowHomeStoreSection(1), true));
test('section visibility hides zero', () => assert.equal(model.shouldShowHomeStoreSection(0), false));
test('group visibility follows filtered cards', () => assert.equal(model.shouldShowHomeStoreGroup([card()], '', model.resolveHomeStoreFilter('all')), true));
test('group visibility hides unmatched cards', () => assert.equal(model.shouldShowHomeStoreGroup([card()], 'none', model.resolveHomeStoreFilter('all')), false));
test('group label trims and bounds', () => assert.equal(model.normalizeHomeStoreGroupLabel('  日记  '), '日记'));
test('group label fallback handles empty', () => assert.equal(model.normalizeHomeStoreGroupLabel('', '其他'), '其他'));
test('grouping creates keyed arrays', () => assert.equal(model.groupHomeStoreCards([1, 2], () => 'A').get('A').length, 2));
test('grouping malformed input is empty', () => assert.equal(model.groupHomeStoreCards(null, () => 'A').size, 0));
test('group ordering prefers configured order', () => assert.deepEqual(model.orderHomeStoreGroups(new Map([['B', []], ['A', []]]), ['A']), ['A', 'B']));
test('group ordering appends unknown groups', () => assert.deepEqual(model.orderHomeStoreGroups(new Map([['B', []], ['A', []]]), ['X']), ['B', 'A']));
test('dedupe keeps first module', () => assert.deepEqual(model.dedupeHomeStoreCards([{moduleId: 'a'}, {moduleId: 'a'}, {moduleId: 'b'}]).map((x) => x.moduleId), ['a', 'b']));
test('dedupe drops missing ids', () => assert.deepEqual(model.dedupeHomeStoreCards([{title: 'x'}]), []));
test('collapsed groups normalize arrays', () => assert.deepEqual([...model.normalizeHomeStoreCollapsedGroups(['A', 'A', 1])], ['A']));
test('collapsed groups normalize invalid input', () => assert.equal(model.normalizeHomeStoreCollapsedGroups(null).size, 0));
test('toggle adds group', () => assert.equal(model.toggleHomeStoreGroup([], 'A').has('A'), true));
test('toggle removes group', () => assert.equal(model.toggleHomeStoreGroup(['A'], 'A').has('A'), false));
test('added action is apply-size', () => assert.equal(model.resolveHomeStoreAction(true, false), 'apply-size'));
test('configured added action is configure', () => assert.equal(model.resolveHomeStoreAction(true, true), 'configure'));
test('unadded action is add', () => assert.equal(model.resolveHomeStoreAction(false, false), 'add'));
