const test = require('node:test');
const assert = require('node:assert/strict');
const model = require('../src/home-store-model.js');

test('dependency catalog includes all non-core providers', () => assert.deepEqual(Object.keys(model.DEPENDENCY_INFO).sort(), ['checkin-summary','external-activitywatch-time','external-anime-bangumi','external-fx-frankfurter','external-hot-news-dailyhot','external-ical-events','external-news-hackernews','external-news-newsnow','external-rss-miniflux','external-status-uptimekuma','external-weather-open-meteo','journal-calendar','plugin-commands']));
test('hacker news dependency needs no key and no setup', () => {
    const info = model.resolveHomeStoreDependencyInfo('external-news-hackernews');
    assert.equal(info.kind, 'external-api');
    assert.equal(info.required, false);
    assert.match(info.network, /内核代理/);
});
test('weather dependency is external api', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').kind, 'external-api'));
test('activitywatch dependency requires local service', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').kind, 'local-service'));
test('dailyhot dependency points to install project', () => assert.match(model.resolveHomeStoreDependencyInfo('external-hot-news-dailyhot').installUrl, /github\.com/));
test('newsnow dependency points to install project', () => assert.match(model.resolveHomeStoreDependencyInfo('external-news-newsnow').projectUrl, /newsnow/));
test('holiday overlay is optional', () => assert.equal(model.resolveHomeStoreDependencyInfo('journal-calendar').required, false));
test('checkin dependency is plugin kind', () => assert.equal(model.resolveHomeStoreDependencyInfo('checkin-summary').kind, 'plugin'));
test('unknown dependency returns null', () => assert.equal(model.resolveHomeStoreDependencyInfo('missing'), null));
test('dependency notice marks required', () => assert.match(model.buildHomeStoreDependencyNotice('external-activitywatch-time').notice, /需要前置依赖/));
test('dependency notice marks optional', () => assert.match(model.buildHomeStoreDependencyNotice('journal-calendar').notice, /可选数据源/));
test('dependency notice supports labels', () => assert.match(model.buildHomeStoreDependencyNotice('external-weather-open-meteo', {required: '前置'}).notice, /^前置/));
test('dependency list filters unknown modules', () => assert.equal(model.listHomeStoreDependencies(['external-weather-open-meteo', 'missing']).length, 1));
test('dependency info is defensive copy', () => { const info = model.resolveHomeStoreDependencyInfo('external-weather-open-meteo'); info.name = 'changed'; assert.equal(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').name, 'Open-Meteo'); });
test('dependency kind normalization defaults unknown', () => assert.equal(model.normalizeHomeStoreDependencyKind('bad'), 'unknown'));
test('weather setup states no api key', () => assert.match(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').setup, /API Key/));
test('activitywatch setup states desktop restriction', () => assert.match(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').setup, /127\.0\.0\.1/));
test('dailyhot setup warns no public demo', () => assert.match(model.resolveHomeStoreDependencyInfo('external-hot-news-dailyhot').setup, /公共演示/));
test('newsnow setup requires api path', () => assert.match(model.resolveHomeStoreDependencyInfo('external-news-newsnow').setup, /api\/s/));
test('dependency platforms expose mobile restriction', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').platforms, 'desktop/sidebar'));
test('dependency network boundary is explicit', () => assert.match(model.resolveHomeStoreDependencyInfo('external-weather-open-meteo').network, /HTTPS/));
test('plugin command dependency is optional', () => assert.equal(model.resolveHomeStoreDependencyInfo('plugin-commands').required, false));
test('bangumi dependency is required', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-anime-bangumi').required, true));
test('dependency list defaults to catalog', () => assert.equal(model.listHomeStoreDependencies().length, 13));
test('notice is bounded', () => assert.ok(model.buildHomeStoreDependencyNotice('external-weather-open-meteo').notice.length < 300));
test('install url is nonempty for activitywatch', () => assert.match(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').installUrl, /^https:/));
test('project url is nonempty for holiday data', () => assert.match(model.resolveHomeStoreDependencyInfo('journal-calendar').projectUrl, /^https:/));
test('checkin notice avoids fake repository claim', () => assert.match(model.resolveHomeStoreDependencyInfo('checkin-summary').setup, /无法核实|协议/));
test('dependency info includes provider name', () => assert.equal(model.resolveHomeStoreDependencyInfo('external-news-newsnow').name, 'NewsNow'));
test('dependency info includes setup field', () => assert.ok(model.resolveHomeStoreDependencyInfo('external-anime-bangumi').setup));
test('dependency info includes privacy network boundary', () => assert.ok(model.resolveHomeStoreDependencyInfo('external-activitywatch-time').network));
test('optional dependency notice remains visible', () => assert.ok(model.buildHomeStoreDependencyNotice('journal-calendar')));
test('dependency list preserves requested order', () => assert.deepEqual(model.listHomeStoreDependencies(['journal-calendar','external-weather-open-meteo']).map((x) => x.moduleId), ['journal-calendar','external-weather-open-meteo']));
test('dependency summary counts required and optional entries', () => { const summary = model.summarizeHomeStoreDependencies(); assert.equal(summary.total, 13); assert.equal(summary.required, 8); assert.equal(summary.optional, 5); });
test('dependency summary exposes kind histogram', () => { const summary = model.summarizeHomeStoreDependencies(); assert.equal(summary.kinds['external-api'], 4); assert.equal(summary.kinds['self-hosted-api'], 4); });
test('uptime kuma dependency is self-hosted and required', () => { const info = model.resolveHomeStoreDependencyInfo('external-status-uptimekuma'); assert.equal(info.kind, 'self-hosted-api'); assert.equal(info.required, true); });
test('frankfurter dependency needs no key and no setup', () => { const info = model.resolveHomeStoreDependencyInfo('external-fx-frankfurter'); assert.equal(info.kind, 'external-api'); assert.equal(info.required, false); assert.match(info.network, /内核代理/); });
test('dependency summary accepts a restricted module list', () => { const summary = model.summarizeHomeStoreDependencies(['journal-calendar','missing']); assert.equal(summary.total, 1); assert.equal(summary.optional, 1); });
test('dependency summary entries retain module ids', () => { const summary = model.summarizeHomeStoreDependencies(['external-weather-open-meteo']); assert.equal(summary.entries[0].moduleId, 'external-weather-open-meteo'); });
test('dependency state resolves required module', () => assert.equal(model.resolveHomeStoreDependencyState('external-weather-open-meteo'), 'required'));
test('dependency state resolves optional module', () => assert.equal(model.resolveHomeStoreDependencyState('journal-calendar'), 'optional'));
test('dependency state resolves unknown module', () => assert.equal(model.resolveHomeStoreDependencyState('missing'), 'none'));
test('dependency label uses caller labels', () => assert.equal(model.resolveHomeStoreDependencyLabel('journal-calendar', {optional: '可选'}), '可选'));
test('dependency label bounds caller labels', () => assert.equal(model.resolveHomeStoreDependencyLabel('journal-calendar', {optional: 'x'.repeat(100)}).length, 48));
test('dependency summary exposes required state', () => assert.equal(model.buildHomeStoreDependencySummary('external-activitywatch-time').state, 'required'));
test('dependency summary exposes provider name', () => assert.equal(model.buildHomeStoreDependencySummary('external-activitywatch-time').name, 'ActivityWatch'));
test('dependency summary exposes setup instructions', () => assert.match(model.buildHomeStoreDependencySummary('external-news-newsnow').setup, /api/));
test('dependency summary exposes network boundary', () => assert.match(model.buildHomeStoreDependencySummary('external-weather-open-meteo').network, /HTTPS/));
test('dependency summary exposes platforms', () => assert.equal(model.buildHomeStoreDependencySummary('external-activitywatch-time').platforms, 'desktop/sidebar'));
test('dependency summary keeps install url safe', () => assert.match(model.buildHomeStoreDependencySummary('external-weather-open-meteo').installUrl, /^https:\/\//));
test('unknown dependency summary has no install url', () => assert.equal(model.buildHomeStoreDependencySummary('missing').installUrl, ''));
