const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('store root initializes render version', () => assert.match(source, /root\.dataset\.renderVersion = "0"/));
test('store root exposes initial busy state', () => assert.match(source, /root\.setAttribute\("aria-busy", "false"\)/));
test('store render marks busy before rebuilding', () => assert.match(source, /const renderStore = \(\) => \{\s*root\.setAttribute\("aria-busy", "true"\)/));
test('store render increments version', () => assert.match(source, /root\.dataset\.renderVersion = String\(Number\(root\.dataset\.renderVersion/));
test('store records ready count', () => assert.match(source, /root\.dataset\.readyCount = String\(activeIds\.size\)/));
test('store records pending count', () => assert.match(source, /root\.dataset\.pendingCount = String\(pending\.length\)/));
test('store records visible count', () => assert.match(source, /root\.dataset\.visibleCount = String\(summary\.visible\)/));
test('store records total count', () => assert.match(source, /root\.dataset\.totalCount = String\(summary\.total\)/));
test('store records added count', () => assert.match(source, /root\.dataset\.addedCount = String\(summary\.added\)/));
test('store clears busy state after render', () => assert.match(source, /restoreStoreView\(\);\s*root\.setAttribute\("aria-busy", "false"\)/));
test('empty store clears busy state', () => assert.match(source, /root\.dataset\.pendingCount = "0";[\s\S]*?root\.setAttribute\("aria-busy", "false"\)/));
test('summary exposes ready state', () => assert.match(source, /resultSummary\.dataset\.state = "ready"/));
test('summary exposes results state', () => assert.match(source, /resultSummary\.dataset\.state = summary\.visible > 0 \? "results" : "empty"/));
test('summary state distinguishes empty results', () => assert.match(source, /: "empty"/));
test('tabs expose set size', () => assert.match(source, /btn\.setAttribute\("aria-setsize", String\(tabs\.length\)\)/));
test('tabs expose position', () => assert.match(source, /btn\.setAttribute\("aria-posinset", String\(tabIndex \+ 1\)\)/));
test('cards reference their title', () => assert.match(source, /card\.setAttribute\("aria-labelledby", title\.id\)/));
test('card status is atomic', () => assert.match(source, /status\.setAttribute\("aria-atomic", "true"\)/));
test('size group declares horizontal orientation', () => assert.match(source, /tiles\.setAttribute\("aria-orientation", "horizontal"\)/));
test('size group remains a semantic group', () => assert.match(source, /tiles\.setAttribute\("role", "group"\)/));
test('size tiles expose set size', () => assert.match(source, /tile\.setAttribute\("aria-setsize", String\(supported\.length\)\)/));
test('size tiles expose position', () => assert.match(source, /tile\.setAttribute\("aria-posinset", String\(sizeIndex \+ 1\)\)/));
test('add action records module id', () => assert.match(source, /addButton\.dataset\.moduleId = moduleId/));
test('ready heading exposes heading role', () => assert.match(source, /readyHeading\.setAttribute\("role", "heading"\)/));
test('ready heading exposes level', () => assert.match(source, /readyHeading\.setAttribute\("aria-level", "2"\)/));
test('pending heading exposes heading role', () => assert.match(source, /pendingHeading\.setAttribute\("role", "heading"\)/));
test('group heading exposes heading role', () => assert.match(source, /groupHeading\.setAttribute\("role", "heading"\)/));
test('group heading exposes level', () => assert.match(source, /groupHeading\.setAttribute\("aria-level", "3"\)/));
test('group grid records group key', () => assert.match(source, /groupGrid\.dataset\.group = label/));
test('pending cards reference their title', () => assert.match(source, /card\.setAttribute\("aria-labelledby", title\.id\)/));
test('filter empty state records state', () => assert.match(source, /filterEmptyState\.dataset\.state = "empty-filter"/));
test('focus fallback restores visible card', () => assert.match(source, /if \(!target && focusKind === "card"\)/));
test('focus fallback restores group toggle', () => assert.match(source, /if \(!target && focusKind === "group"\)/));
test('focus fallback restores search', () => assert.match(source, /target = root\.querySelector<HTMLElement>\("\.sw-home-store__search input"\)/));
test('focus kind is observable', () => assert.match(source, /root\.dataset\.focusKind = focusKind/));
test('focus value is observable', () => assert.match(source, /root\.dataset\.focusValue = focusValue/));
test('busy styling uses progress cursor', () => assert.match(css, /&\[aria-busy="true"\][\s\S]*?cursor: progress/));
test('busy styling softens summary', () => assert.match(css, /&\[aria-busy="true"\] \.sw-home-store__summary[\s\S]*?opacity: \.72/));
test('card focus has scroll margin', () => assert.match(css, /&\[data-focus-kind="card"\][\s\S]*?scroll-margin-block: 18px/));
test('heading focus has scroll margin', () => assert.match(css, /\.sw-home-store__group\[role="heading"\][\s\S]*?scroll-margin-block: 12px/));
test('size group contains inline overscroll', () => assert.match(css, /\.sw-home-store__sizes\[aria-orientation="horizontal"\][\s\S]*?overscroll-behavior-inline: contain/));
test('render state remains scoped to store root', () => assert.match(source, /root\.setAttribute\("aria-busy"/));
test('size position uses one-based index', () => assert.match(source, /sizeIndex \+ 1/));
test('tab position uses one-based index', () => assert.match(source, /tabIndex \+ 1/));
test('render version remains bounded to numeric state', () => assert.match(source, /Number\(root\.dataset\.renderVersion \|\| "0"\)/));
test('summary state remains data-driven', () => assert.match(source, /resultSummary\.dataset\.state/));
