const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const storeSource = source.slice(source.indexOf('private openHomeWidgetStore'), source.indexOf('private openSecondPanel'));
const mediaStart = css.lastIndexOf('@media (max-width: 560px) {\n    .sw-home-store');
const mediaEnd = mediaStart >= 0 ? css.indexOf('@media (max-width: 560px) and (prefers-reduced-motion: reduce)', mediaStart) : -1;
const mobile = mediaStart >= 0 ? css.slice(mediaStart, mediaEnd > mediaStart ? mediaEnd : undefined) : '';

test('mobile store media query exists', () => assert.match(css, /@media \(max-width: 560px\)/));
test('mobile store keeps compact padding', () => assert.match(mobile, /\.sw-home-store \{ padding: 10px 12px 14px; \}/));
test('mobile search wraps controls', () => assert.match(mobile, /\.sw-home-store__search \{ flex-wrap: wrap/));
test('mobile search keeps gap', () => assert.match(mobile, /\.sw-home-store__search \{[^}]*gap: 7px/));
test('mobile search input keeps flexible width', () => assert.match(mobile, /\.sw-home-store__search input \{ flex: 1 1 calc\(100% - 40px\)/));
test('mobile search input has zero minimum', () => assert.match(mobile, /\.sw-home-store__search input \{[^}]*min-width: 0/));
test('mobile sort fills half row', () => assert.match(mobile, /\.sw-home-store__search \.sw-home-store__sort,[\s\S]*?flex: 1 1 calc\(50% - 4px\)/));
test('mobile guide fills half row', () => assert.match(mobile, /\.sw-home-store__guide \{ flex: 1 1 calc\(50% - 4px\)/));
test('mobile sort removes max width', () => assert.match(mobile, /\.sw-home-store__search \.sw-home-store__sort,[\s\S]*?max-width: none/));
test('mobile search controls allow shrink', () => assert.match(mobile, /\.sw-home-store__guide \{[^}]*min-width: 0/));
test('mobile store grid is single column', () => assert.match(mobile, /\.sw-home-store__grid \{ grid-template-columns: minmax\(0, 1fr\)/));
test('mobile grid keeps zero minimum', () => assert.match(mobile, /\.sw-home-store__grid \{[^}]*min-width: 0/));
test('mobile grid keeps card gap', () => assert.match(mobile, /\.sw-home-store__grid \{[^}]*gap: 10px/));
test('mobile tabs remain horizontally scrollable', () => assert.match(mobile, /\.sw-home-store__tabs \{ overflow-x: auto/));
test('mobile tabs contain inline overscroll', () => assert.match(mobile, /\.sw-home-store__tabs \{[^}]*overscroll-behavior-inline: contain/));
test('mobile tabs use momentum scrolling', () => assert.match(mobile, /-webkit-overflow-scrolling: touch/));
test('mobile tabs keep thin scrollbar', () => assert.match(mobile, /scrollbar-width: thin/));
test('mobile tabs keep touch height', () => assert.match(mobile, /\.sw-home-store__tab \{ flex: 0 0 auto; min-height: 36px/));
test('mobile tabs preserve horizontal padding', () => assert.match(mobile, /\.sw-home-store__tab \{[^}]*padding-inline: 12px/));
test('mobile summary shares bounded width rule', () => assert.match(mobile, /\.sw-home-store__summary,[\s\S]*?\.sw-home-store__source-meta,[\s\S]*?max-width: 100%/));
test('mobile cards fill row width', () => assert.match(mobile, /\.sw-home-store__card \{ width: 100%/));
test('mobile cards cap row width', () => assert.match(mobile, /\.sw-home-store__card \{[^}]*max-width: 100%/));
test('mobile cards keep compact padding', () => assert.match(mobile, /\.sw-home-store__card \{[^}]*padding: 11px 12px/));
test('mobile card keeps bounded width', () => assert.match(mobile, /\.sw-home-store__card \{ width: 100%; max-width: 100%/));
test('mobile preview caps width', () => assert.match(mobile, /\.sw-home-store__preview \{ max-width: 100%/));
test('mobile preview clips overflow', () => assert.match(mobile, /\.sw-home-store__preview \{[^}]*overflow: hidden/));
test('mobile size row keeps action alignment', () => assert.match(mobile, /\.sw-home-store__sizes \.sw-home-store__add/));
test('mobile add action remains end aligned', () => assert.match(mobile, /\.sw-home-store__sizes \.sw-home-store__add \{ margin-inline-start: auto; \}/));
test('mobile source metadata caps width', () => assert.match(mobile, /\.sw-home-store__summary,[\s\S]*?\.sw-home-store__source-meta,[\s\S]*?max-width: 100%/));
test('mobile empty state caps width', () => assert.match(mobile, /\.sw-home-store__filter-empty \{ max-width: 100%/));
test('mobile empty state wraps text', () => assert.match(mobile, /\.sw-home-store__filter-empty \{[^}]*overflow-wrap: anywhere/));
test('mobile one-column rule is scoped to store grid', () => assert.match(mobile, /\.sw-home-store__grid/));
test('mobile tab rule is scoped to store tabs', () => assert.match(mobile, /\.sw-home-store__tab/));
test('mobile card rule is scoped to store cards', () => assert.match(mobile, /\.sw-home-store__card/));
test('mobile preview does not affect home widgets', () => assert.doesNotMatch(mobile, /\.sw-home__cell/));
test('mobile controls preserve non-positive flex basis', () => assert.match(mobile, /calc\(50% - 4px\)/));
test('mobile search keeps input clear affordance room', () => assert.match(mobile, /calc\(100% - 40px\)/));
test('mobile layout avoids fixed card pixel width', () => assert.doesNotMatch(mobile, /\.sw-home-store__card[^}]*width:\s*\d+px/));
test('mobile layout avoids horizontal grid columns', () => assert.doesNotMatch(mobile, /grid-template-columns:\s*repeat\(/));
test('mobile layout uses bounded overflow only', () => assert.match(mobile, /overflow: hidden|overflow-x: auto/));
test('mobile layout remains under narrow viewport breakpoint', () => assert.match(css, /@media \(max-width: 560px\)/));

test('mobile panel injects a dedicated mobile class', () => assert.match(source, /root\.classList\.add\("sw-home--mobile"\)/));
test('mobile panel class is guarded by device detection', () => assert.match(source, /if \(this\.isMobile\) root\.classList\.add/));
test('mobile panel uses mobile device key', () => assert.match(source, /const device = this\.isMobile \? "mobile" : "desktop"/));
test('mobile store dialog width is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(680px, 94vw\)"/));
test('mobile store dialog height is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(560px, 85vh\)"/));
test('mobile preview dialog width is bounded', () => assert.match(source, /this\.isMobile \? "min\(420px, 92vw\)"/));
test('mobile preview dialog height is bounded', () => assert.match(source, /this\.isMobile \? "min\(560px, 80vh\)"/));
test('mobile store cards use resolved size', () => assert.match(source, /device === "mobile" \? \[resolveMobileHomeSize\(declaredSizes\)\]/));
test('mobile size resolver is imported from home model', () => assert.match(source, /import \{normalizeHomeState, resolveMobileHomeSize\} from "\.\/home-model"/));
test('mobile store cards expose device support text', () => assert.match(source, /homeStoreSupportedSurfaces/));
test('mobile store root records device', () => assert.match(source, /root\.dataset\.device = device/));
test('mobile store uses region semantics', () => assert.match(source, /root\.setAttribute\("role", "region"\)/));
test('mobile store search uses search semantics', () => assert.match(source, /searchBar\.setAttribute\("role", "search"\)/));
test('mobile store searchbox uses enter key hint', () => assert.match(source, /searchInput\.setAttribute\("enterkeyhint", "search"\)/));
test('mobile store search disables autocomplete', () => assert.match(source, /searchInput\.autocomplete = "off"/));
test('mobile store tabs retain horizontal navigation', () => assert.match(source, /event\.key === "ArrowRight" \|\| event\.key === "ArrowDown"/));
test('mobile store tabs retain home navigation', () => assert.match(source, /if \(event\.key === "Home"\) next = 0/));
test('mobile store tabs retain end navigation', () => assert.match(source, /if \(event\.key === "End"\) next = buttons\.length - 1/));
test('mobile store tab navigation prevents page scroll', () => assert.match(source, /event\.preventDefault\(\);\s*activateStoreTab\(buttons\[next\]\)/));
test('mobile store cards use local focus navigation', () => assert.match(source, /root\.querySelectorAll<HTMLElement>\("\.sw-home-store__card:not\(\.fn__none\)"\)/));
test('mobile store card navigation supports vertical arrows', () => assert.match(source, /event\.key === "ArrowRight" \|\| event\.key === "ArrowDown"/));
test('mobile store card navigation supports home', () => assert.match(source, /if \(event\.key === "Home"\) next = 0/));
test('mobile store card navigation supports end', () => assert.match(source, /if \(event\.key === "End"\) next = cards\.length - 1/));
test('mobile store size controls keep touch action', () => assert.match(css, /\.sw-home-store__size[\s\S]*?touch-action: manipulation/));
test('mobile store add controls keep touch action', () => assert.match(css, /\.sw-home-store__add[\s\S]*?touch-action: manipulation/));
test('mobile store tab controls keep touch action', () => assert.match(css, /\.sw-home-store__tab[\s\S]*?touch-action: manipulation/));
test('mobile store guide keeps touch action', () => assert.match(css, /\.sw-home-store__guide[\s\S]*?touch-action: manipulation/));
test('mobile store grid keeps isolation', () => assert.match(css, /\.sw-home-store__grid[\s\S]*?isolation: isolate/));
test('mobile store cards keep border box sizing', () => assert.match(css, /\.sw-home-store__card[\s\S]*?box-sizing: border-box/));
test('mobile store cards keep minimum width zero', () => assert.match(css, /\.sw-home-store__card[\s\S]*?min-width: 0/));
test('mobile store cards keep maximum width full', () => assert.match(css, /\.sw-home-store__card[\s\S]*?max-width: 100%/));
test('mobile store summary permits arbitrary wrapping', () => assert.match(css, /\.sw-home-store__summary[\s\S]*?overflow-wrap: anywhere/));
test('mobile store source chips permit arbitrary wrapping', () => assert.match(css, /\.sw-home-store__source-chip[\s\S]*?max-width: 100%/));
test('mobile store empty result is aria hidden when inactive', () => assert.match(source, /filterEmptyState\?\.setAttribute\("aria-hidden", String\(hasVisibleCards\)\)/));
test('mobile store empty result has atomic live semantics', () => assert.match(source, /filterEmptyState\.setAttribute\("aria-atomic", "true"\)/));
test('mobile store result summary has atomic live semantics', () => assert.match(source, /resultSummary\.setAttribute\("aria-atomic", "true"\)/));
test('mobile store clear filters restores all tab', () => assert.match(source, /storeTab = "all"/));
test('mobile store clear filters restores search focus', () => assert.match(source, /applyFilter\(\);\s*searchInput\.focus\(\)/));
test('mobile store add action remains independent from size selection', () => assert.match(source, /dataset\.action = added \? "apply-size" : "add"/));
test('mobile store preview action remains a button', () => assert.match(source, /previewButton\.type = "button"/));
test('mobile store configure action remains a button', () => assert.match(source, /configButton\.type = "button"/));
test('mobile store remove action remains a button', () => assert.match(source, /removeButton\.type = "button"/));
test('mobile store does not install document-level card key handlers', () => assert.doesNotMatch(storeSource, /document\.addEventListener\("keydown"/));
test('mobile store keeps provider rescan bounded', () => assert.match(source, /window\.setTimeout\(\(\) => \{[\s\S]*?renderStore\(\);[\s\S]*?\}, 400\)/));
