const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');

test('store search row has sort control class', () => assert.match(css, /\.sw-home-store__sort/));
test('sort control has bounded minimum width', () => assert.match(css, /min-width: 106px/));
test('sort control has bounded maximum width', () => assert.match(css, /max-width: 132px/));
test('sort control has compact height', () => assert.match(css, /height: 32px/));
test('sort control has rounded corners', () => assert.match(css, /border-radius: 8px/));
test('store cards animate border changes', () => assert.match(css, /transition: border-color \.15s ease/));
test('store cards lift on desktop hover', () => assert.match(css, /transform: translateY\(-1px\)/));
test('store cards expose focus-within state', () => assert.match(css, /&:focus-within/));
test('store cards use primary focus border', () => assert.match(css, /border-color: var\(--b3-theme-primary\)/));
test('store tabs have minimum touch height', () => assert.match(css, /min-height: 40px/));
test('store tabs preserve no-wrap labels', () => assert.match(css, /white-space: nowrap/));
test('store tabs use manipulation touch action', () => assert.match(css, /touch-action: manipulation/));
test('store tabs hover has surface feedback', () => assert.match(css, /background: color-mix\(in srgb, var\(--b3-theme-primary\) 6%/));
test('store tabs have visible focus ring', () => assert.match(css, /outline: 2px solid var\(--b3-theme-primary\)/));
test('group heading has minimum height', () => assert.match(css, /\.sw-home-store__group[\s\S]*?min-height: 32px/));
test('group toggle supports touch action', () => assert.match(css, /\.sw-home-store__group-toggle[\s\S]*?touch-action: manipulation/));
test('summary reserves stable height', () => assert.match(css, /\.sw-home-store__summary[\s\S]*?min-height: 18px/));
test('mobile search row wraps', () => assert.match(css, /@media \(max-width: 560px\)[\s\S]*?\.sw-home-store__search \{[\s\S]*?flex-wrap: wrap/));
test('mobile search input gets full row', () => assert.match(css, /\.sw-home-store__search[\s\S]*?input \{ flex: 1 1 100%; \}/));
test('mobile sort control expands', () => assert.match(css, /\.sw-home-store__sort \{ flex: 1 1 46%; max-width: none; \}/));
test('mobile guide button expands', () => assert.match(css, /\.sw-home-store__guide \{ flex: 1 1 46%; min-height: 32px; \}/));
test('mobile cards disable hover lift', () => assert.match(css, /\.sw-home-store__card:hover \{ transform: none; \}/));
test('mobile tabs preserve horizontal overscroll', () => assert.match(css, /overscroll-behavior-x: contain/));
test('sort state is stored in store dialog', () => assert.match(source, /let storeSort = "relevance"/));
test('sort select uses localized label', () => assert.match(source, /homeStoreSortLabel/));
test('sort select normalizes values', () => assert.match(source, /normalizeHomeStoreSort\(sortSelect\.value\)/));
test('store render uses sort model', () => assert.match(source, /sortHomeStoreCards\(/));
test('store search uses token model', () => assert.match(source, /matchesHomeStoreTokens\(/));
test('store render computes tab counts', () => assert.match(source, /buildHomeStoreTabCounts\(/));
test('store cards expose module id dataset', () => assert.match(source, /card\.dataset\.moduleId = moduleId/));
test('store tabs preserve source labels', () => assert.match(source, /btn\.dataset\.tabLabel = tab\.label/));
