const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('store root has region semantics', () => assert.match(source, /root\.setAttribute\("role", "region"\)/));
test('store root exposes a label', () => assert.match(source, /root\.setAttribute\("aria-label", this\.i18n\.homeStoreTitle\)/));
test('store root records device', () => assert.match(source, /root\.dataset\.device = device/));
test('store root records initial active tab', () => assert.match(source, /root\.dataset\.activeTab = storeTab/));
test('store search container has search semantics', () => assert.match(source, /searchBar\.setAttribute\("role", "search"\)/));
test('store search container has a label', () => assert.match(source, /searchBar\.setAttribute\("aria-label", this\.i18n\.homeStoreSearch\)/));
test('store search input uses searchbox semantics', () => assert.match(source, /searchInput\.setAttribute\("role", "searchbox"\)/));
test('store search input disables autocomplete', () => assert.match(source, /searchInput\.autocomplete = "off"/));
test('store search input advertises keyboard intent', () => assert.match(source, /searchInput\.setAttribute\("enterkeyhint", "search"\)/));
test('store clear search records an action', () => assert.match(source, /clearSearchButton\.dataset\.action = "clear-search"/));
test('store sort records an action', () => assert.match(source, /sortSelect\.dataset\.action = "sort"/));
test('store sort records the selected sort', () => assert.match(source, /sortSelect\.dataset\.sort = storeSort/));
test('store sort controls the summary', () => assert.match(source, /sortSelect\.setAttribute\("aria-controls", "sw-home-store-result-summary"\)/));
test('store guide announces its dialog', () => assert.match(source, /guideButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('store guide records an action', () => assert.match(source, /guideButton\.dataset\.action = "open-guide"/));
test('store root records normalized query', () => assert.match(source, /root\.dataset\.query = normalizeHomeStoreQuery\(storeQuery\)/));
test('store summary is atomic', () => assert.match(source, /resultSummary\.setAttribute\("aria-atomic", "true"\)/));
test('store summary exposes visible count', () => assert.match(source, /resultSummary\.dataset\.visible = String\(summary\.visible\)/));
test('store summary exposes total count', () => assert.match(source, /resultSummary\.dataset\.total = String\(summary\.total\)/));
test('store summary exposes added count', () => assert.match(source, /resultSummary\.dataset\.added = String\(summary\.added\)/));
test('store tabs have a stable tablist id', () => assert.match(source, /tabBar\.id = "sw-home-store-tablist"/));
test('store tabs control the summary', () => assert.match(source, /btn\.setAttribute\("aria-controls", "sw-home-store-result-summary"\)/));
test('store tabs initialize counts', () => assert.match(source, /btn\.dataset\.count = "0"/));
test('store tabs update counts', () => assert.match(source, /button\.dataset\.count = String\(count\)/));
test('store tabs announce counts', () => assert.match(source, /button\.setAttribute\("aria-label", `\$\{button\.dataset\.tabLabel/));
test('store tabs describe the summary', () => assert.match(source, /button\.setAttribute\("aria-describedby", resultSummary\?\.id/));
test('store tab activation records active tab', () => assert.match(source, /root\.dataset\.activeTab = storeTab/));
test('store cards expose aria hidden state', () => assert.match(source, /card\.setAttribute\("aria-hidden", String\(!visible\)\)/));
test('store groups expose aria hidden state', () => assert.match(source, /heading\.setAttribute\("aria-hidden", String\(!visible\)\)/));
test('store grids expose collapsed aria hidden state', () => assert.match(source, /grid\.setAttribute\("aria-hidden", String\(!visible \|\| heading\.dataset\.collapsed === "true"\)\)/));
test('store empty state exposes live semantics', () => assert.match(source, /filterEmptyState\.setAttribute\("aria-live", "polite"\)/));
test('store empty state is atomic', () => assert.match(source, /filterEmptyState\.setAttribute\("aria-atomic", "true"\)/));
test('store clear filters records an action', () => assert.match(source, /clearFilters\.dataset\.action = "clear-filters"/));
test('store pending cards expose stable status', () => assert.match(source, /card\.dataset\.status = unavailable \? "unavailable" : "requires-provider"/));
test('store unavailable removal records an action', () => assert.match(source, /removeButton\.dataset\.action = "remove-unavailable"/));
test('store group headings expose accessible labels', () => assert.match(source, /groupHeading\.setAttribute\("aria-label", `\$\{label\}/));
test('store group labels are scoped', () => assert.match(source, /groupLabel\.className = "sw-home-store__group-label"/));
test('store group toggles retain a group key', () => assert.match(source, /groupToggle\.dataset\.group = label/));
test('store group toggles have tooltips', () => assert.match(source, /groupToggle\.title = groupToggle\.getAttribute\("aria-label"\)/));
test('store guide has a tooltip', () => assert.match(source, /guideButton\.title = this\.i18n\.homeStoreGuideTitle/));
test('store viewport contains overscroll', () => assert.match(css, /\.sw-home-store \{[\s\S]*?overscroll-behavior: contain/));
test('store viewport reserves scrollbar space', () => assert.match(css, /\.sw-home-store \{[\s\S]*?scrollbar-gutter: stable/));
test('empty tabs are visually de-emphasized', () => assert.match(css, /&\[data-count="0"\] \{ opacity: \.58/));
test('store group labels wrap', () => assert.match(css, /\.sw-home-store__group-label \{ min-width: 0; overflow-wrap: anywhere/));
test('hidden cards are skipped by content visibility', () => assert.match(css, /\.sw-home-store__card\[aria-hidden="true"\][\s\S]*?content-visibility: hidden/));
test('hidden empty state is visually de-emphasized', () => assert.match(css, /\.sw-home-store__filter-empty\[aria-hidden="true"\][\s\S]*?opacity: \.72/));
test('summary remains selectable', () => assert.match(css, /\.sw-home-store__summary[\s\S]*?user-select: text/));
