const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const storeUiSource = fs.readFileSync(path.join(root, 'src', 'home-store-ui.ts'), 'utf8');
const restoreBlock = (source.match(/const restoreStoreView = \(\) => \{([\s\S]*?)\n\s*\};/) || [])[1] || '';

test('store rerender captures active element', () => assert.match(storeUiSource, /const activeElement = document\.activeElement instanceof HTMLElement/));
test('store rerender captures scroll position', () => assert.match(storeUiSource, /const previousScrollTop = root\.scrollTop/));
test('store rerender checks focus ownership', () => assert.match(storeUiSource, /root\.contains\(activeElement\)/));
test('store rerender detects card focus', () => assert.match(storeUiSource, /activeElement\.closest<HTMLElement>\("\.sw-home-store__card"\)/));
test('store rerender detects tab focus', () => assert.match(storeUiSource, /activeElement\.closest<HTMLElement>\("\.sw-home-store__tab"\)/));
test('store rerender detects group focus', () => assert.match(storeUiSource, /activeElement\.closest<HTMLElement>\("\.sw-home-store__group-toggle"\)/));
test('store rerender detects search focus', () => assert.match(storeUiSource, /activeElement\.matches\("\.sw-home-store__search input"\)/));
test('store rerender detects sort focus', () => assert.match(storeUiSource,/activeElement\.matches\("\.sw-home-store__sort"\)/));
test('store rerender clears the old DOM', () => assert.match(storeUiSource, /root\.innerHTML = ""/));
test('store rerender has a restoration helper', () => assert.match(storeUiSource, /const restoreStoreView = \(\) =>/));
test('store rerender bounds scroll restoration', () => assert.match(storeUiSource, /root\.scrollTop = Math\.min\(previousScrollTop, root\.scrollHeight\)/));
test('store rerender searches visible cards', () => assert.match(storeUiSource, /root\.querySelectorAll<HTMLElement>\("\.sw-home-store__card"\)/));
test('store rerender matches card module id', () => assert.match(storeUiSource, /card\.dataset\.moduleId === focusValue/));
test('store rerender skips hidden cards', () => assert.match(storeUiSource, /!card\.classList\.contains\("fn__none"\)/));
test('store rerender searches tabs', () => assert.match(storeUiSource, /root\.querySelectorAll<HTMLElement>\("\.sw-home-store__tab"\)/));
test('store rerender matches tab key', () => assert.match(storeUiSource, /tab\.dataset\.tabKey === focusValue/));
test('store rerender searches groups', () => assert.match(storeUiSource, /root\.querySelectorAll<HTMLElement>\("\.sw-home-store__group"\)/));
test('store rerender restores group toggle', () => assert.match(storeUiSource, /querySelector<HTMLElement>\("\.sw-home-store__group-toggle"\)/));
test('store rerender restores search control', () => assert.match(storeUiSource, /root\.querySelector<HTMLElement>\("\.sw-home-store__search input"\)/));
test('store rerender restores sort control', () => assert.match(storeUiSource, /root\.querySelector<HTMLElement>\("\.sw-home-store__sort"\)/));
test('store rerender focuses without jumping scroll', () => assert.match(storeUiSource, /target\.focus\(\{preventScroll: true\}\)/));
test('empty store path restores view state', () => assert.match(storeUiSource, /root\.textContent = this\.i18n\.homeNoMoreModules;\s*restoreStoreView\(\);/));
test('normal store path restores view state', () => assert.match(storeUiSource, /applyFilter\(\);\s*restoreStoreView\(\);/));
test('sort changes rerender the store', () => assert.match(storeUiSource, /sortSelect\.addEventListener\("change", \(\) => \{ storeSort = normalizeHomeStoreSort\(sortSelect\.value\); renderStore\(\); \}\)/));
test('module changes rerender the store', () => assert.match(storeUiSource, /const handleModuleChange = \(\) => \{[\s\S]*?renderStore\(\);/));
test('provider rescan rerenders the store', () => assert.match(storeUiSource, /window\.setTimeout\(\(\) => \{[\s\S]*?renderStore\(\);/));
test('focus descriptor starts in a neutral state', () => assert.match(storeUiSource, /let focusKind = "none"/));
test('focus descriptor stores a stable value', () => assert.match(storeUiSource, /let focusValue = ""/));
test('card focus remains non-positive tabindex', () => assert.match(storeUiSource, /card\.tabIndex = -1/));
test('rerender restoration is local to the store root', () => assert.match(storeUiSource,/restoreStoreView\(\)/));
test('rerender restoration does not add network calls', () => assert.doesNotMatch(restoreBlock, /fetch\(/));
