const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const source=fs.readFileSync(path.join(root,'src','index.ts'),'utf8');const css=fs.readFileSync(path.join(root,'src','index.scss'),'utf8');
test('card status tone dataset wired',()=>assert.match(source,/card\.dataset\.statusTone = resolveHomeStoreStatusTone/));
test('card integration tone dataset wired',()=>assert.match(source,/card\.dataset\.integrationTone = resolveHomeStoreIntegrationTone/));
test('status tone model imported',()=>assert.match(source,/resolveHomeStoreStatusTone/));
test('integration tone model imported',()=>assert.match(source,/resolveHomeStoreIntegrationTone/));
test('success tone style',()=>assert.match(css,/data-status-tone="success"/));
test('warning tone style',()=>assert.match(css,/data-status-tone="warning"/));
test('info tone style',()=>assert.match(css,/data-status-tone="info"/));
test('network chip emphasis',()=>assert.match(css,/data-integration-tone="network"/));
test('local chip emphasis',()=>assert.match(css,/data-integration-tone="local"/));
test('offline chip emphasis',()=>assert.match(css,/data-integration-tone="offline"/));
test('success uses top border',()=>assert.match(css,/status-tone="success"[^}]*border-top-color/));
test('warning uses top border',()=>assert.match(css,/status-tone="warning"[^}]*border-top-color/));
test('info uses top border',()=>assert.match(css,/status-tone="info"[^}]*border-top-color/));
test('network chip is bold',()=>assert.match(css,/is-online \{ font-weight: 600/));
test('local chip is bold',()=>assert.match(css,/is-local \{ font-weight: 600/));
test('offline chip is bold',()=>assert.match(css,/is-offline \{ font-weight: 600/));
test('dataset status set after added',()=>assert.match(source,/card\.dataset\.added = added \? "true" : "false";\s*card\.dataset\.statusTone/));
test('dataset integration set after status',()=>assert.match(source,/statusTone = resolveHomeStoreStatusTone\(card\.dataset\);\s*card\.dataset\.integrationTone/));
test('status tone remains data attribute',()=>assert.match(source,/dataset\.statusTone/));
test('integration tone remains data attribute',()=>assert.match(source,/dataset\.integrationTone/));
test('tone styling uses theme variables',()=>assert.match(css,/var\(--b3-border-color\)/));
test('warning styling uses theme warning',()=>assert.match(css,/var\(--b3-theme-warning\)/));
test('info styling uses theme primary',()=>assert.match(css,/var\(--b3-theme-primary\)/));
test('tone styling avoids fixed layout',()=>assert.doesNotMatch(css,/status-tone="success"[^}]*display:/));
test('tone styling preserves card focus',()=>assert.match(css,/&:focus-visible/));
test('tone styling preserves card hover',()=>assert.match(css,/&:hover/));
test('integration tone only emphasizes chip',()=>assert.match(css,/integration-tone="network"\] \.sw-home-store__source-chip/));
test('status tone selectors are scoped to cards',()=>assert.match(css,/\.sw-home-store__card[\s\S]*data-status-tone/));
test('status tone classes do not add network calls',()=>assert.doesNotMatch(source,/statusTone.*fetch/));
test('integration tone classes do not add network calls',()=>assert.doesNotMatch(source,/integrationTone.*fetch/));
test('visual contract file is deterministic',()=>assert.ok(source.includes('resolveHomeStoreStatusTone')&&css.includes('data-status-tone')));
