const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const storeUiSource = fs.readFileSync(path.join(root, 'src', 'home-store-ui.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');
const en = fs.readFileSync(path.join(root, 'src', 'i18n', 'en.json'), 'utf8');
const zh = fs.readFileSync(path.join(root, 'src', 'i18n', 'zh-CN.json'), 'utf8');

test('preview context creates a stable scoped id', () => assert.match(storeUiSource, /const previewId = `sw-store-preview-\$\{moduleId\.replace/));
test('preview source integration is exposed on the container', () => assert.match(storeUiSource, /container\.dataset\.integration = sourceInfo\?\.integration \|\| "direct"/));
test('preview source privacy is exposed on the container', () => assert.match(storeUiSource, /container\.dataset\.privacy = sourceInfo\?\.privacy \|\| "none"/));
test('preview metadata retains the module id', () => assert.match(storeUiSource, /meta\.dataset\.moduleId = moduleId/));
test('preview metadata has an accessible label', () => assert.match(storeUiSource, /meta\.setAttribute\("aria-label", this\.i18n\.homeStoreGuideHint\)/));
test('preview chip exposes its tone', () => assert.match(storeUiSource, /chip\.dataset\.tone = tone/));
test('preview chip has an accessible label', () => assert.match(storeUiSource, /chip\.setAttribute\("aria-label", label\)/));
test('preview context exposes the selected surface', () => assert.match(storeUiSource, /homeStorePreviewSurface\.replace\("\{surface\}"/));
test('preview context exposes the selected size', () => assert.match(storeUiSource, /homeStorePreviewSize\.replace\("\{size\}"/));
test('preview context localizes desktop surface', () => assert.match(storeUiSource, /desktop: this\.i18n\.homeStoreDeviceDesktop/));
test('preview context localizes sidebar surface', () => assert.match(storeUiSource, /sidebar: this\.i18n\.homeStoreDeviceSidebar/));
test('preview context localizes mobile surface', () => assert.match(storeUiSource, /mobile: this\.i18n\.homeStoreDeviceMobile/));
test('preview body retains module id', () => assert.match(storeUiSource, /body\.dataset\.moduleId = moduleId/));
test('preview body retains device', () => assert.match(storeUiSource, /body\.dataset\.device = device/));
test('preview body retains size', () => assert.match(storeUiSource, /body\.dataset\.size = sizeKey/));
test('preview body is atomic', () => assert.match(storeUiSource, /body\.setAttribute\("aria-atomic", "true"\)/));
test('preview body starts busy', () => assert.match(storeUiSource, /body\.setAttribute\("aria-busy", "true"\)/));
test('preview body clears busy with the container', () => assert.match(storeUiSource, /body\.setAttribute\("aria-busy", "false"\)/));
test('preview body references metadata', () => assert.match(storeUiSource, /body\.setAttribute\("aria-describedby", meta\.id\)/));
test('preview body is keyboard focusable', () => assert.match(storeUiSource, /body\.tabIndex = 0/));
test('preview uses a context chip tone', () => assert.match(storeUiSource,/addMeta\(this\.i18n\.homeStorePreviewSize[\s\S]*?"context"\)/));
test('preview metadata is sticky', () => assert.match(css, /&__meta[\s\S]*?position: sticky/));
test('preview metadata stays above scrolling content', () => assert.match(css, /&__meta[\s\S]*?z-index: 2/));
test('preview metadata keeps a top inset', () => assert.match(css, /&__meta[\s\S]*?top: 0/));
test('preview metadata has a separating border', () => assert.match(css, /&__meta[\s\S]*?border-bottom: 1px solid/));
test('preview metadata uses a translucent surface', () => assert.match(css, /&__meta[\s\S]*?background: color-mix/));
test('preview metadata supports backdrop blur', () => assert.match(css, /&__meta[\s\S]*?backdrop-filter: blur/));
test('preview context chips use dashed borders', () => assert.match(css, /&\.is-context \{ border-style: dashed/));
test('preview body allows long content to wrap', () => assert.match(css, /&__body[\s\S]*?overflow-wrap: anywhere/));
test('preview body remains shrinkable in flex layouts', () => assert.match(css, /&__body[\s\S]*?min-width: 0/));
test('preview has mobile chip sizing', () => assert.match(css, /@media \(max-width: 560px\)[\s\S]*?\.sw-store-preview__meta-chip/));
test('preview has forced-colors fallback', () => assert.match(css, /@media \(forced-colors: active\)/));
test('English preview surface label exists', () => assert.match(en, /"homeStorePreviewSurface":/));
test('English preview size label exists', () => assert.match(en, /"homeStorePreviewSize":/));
test('Chinese preview surface label exists', () => assert.match(zh, /"homeStorePreviewSurface":/));
test('Chinese preview size label exists', () => assert.match(zh, /"homeStorePreviewSize":/));
