const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const storeSource = source.slice(source.indexOf('private openHomeWidgetStore'), source.indexOf('private openSecondPanel'));
const mediaStart = css.lastIndexOf('@media (max-width: 560px) {\n    .sw-home-store');
const mediaEnd = mediaStart >= 0 ? css.indexOf('@media (max-width: 560px) and (prefers-reduced-motion: reduce)', mediaStart) : -1;
const mobile = mediaStart >= 0 ? css.slice(mediaStart, mediaEnd > mediaStart ? mediaEnd : undefined) : '';

test('mobile store media query exists', () => assert.match(css, /@media \(max-width: 560px\)/));
test('mobile store keeps compact padding', () => assert.match(mobile, /\.sw-home-store \{ padding: 10px 12px 14px; \}/));
test('mobile search wraps controls', () => assert.match(mobile, /\.sw-home-store__search \{ flex-wrap: wrap/));
test('mobile search keeps gap', () => assert.match(mobile, /\.sw-home-store__search \{[^}]*gap: 7px/));
test('mobile search input keeps flexible width', () => assert.match(mobile, /\.sw-home-store__search input \{ flex: 1 1 calc\(100% - 40px\)/));
test('mobile search input has zero minimum', () => assert.match(mobile, /\.sw-home-store__search input \{[^}]*min-width: 0/));
test('mobile sort fills half row', () => assert.match(mobile, /\.sw-home-store__search \.sw-home-store__sort,[\s\S]*?flex: 1 1 calc\(50% - 4px\)/));
test('mobile guide fills half row', () => assert.match(mobile, /\.sw-home-store__guide \{ flex: 1 1 calc\(50% - 4px\)/));
test('mobile sort removes max width', () => assert.match(mobile, /\.sw-home-store__search \.sw-home-store__sort,[\s\S]*?max-width: none/));
test('mobile search controls allow shrink', () => assert.match(mobile, /\.sw-home-store__guide \{[^}]*min-width: 0/));
test('mobile store grid is single column', () => assert.match(mobile, /\.sw-home-store__grid \{ grid-template-columns: minmax\(0, 1fr\)/));
test('mobile grid keeps zero minimum', () => assert.match(mobile, /\.sw-home-store__grid \{[^}]*min-width: 0/));
test('mobile grid keeps card gap', () => assert.match(mobile, /\.sw-home-store__grid \{[^}]*gap: 10px/));
test('mobile tabs remain horizontally scrollable', () => assert.match(mobile, /\.sw-home-store__tabs \{ overflow-x: auto/));
test('mobile tabs contain inline overscroll', () => assert.match(mobile, /\.sw-home-store__tabs \{[^}]*overscroll-behavior-inline: contain/));
test('mobile tabs use momentum scrolling', () => assert.match(mobile, /-webkit-overflow-scrolling: touch/));
test('mobile tabs keep thin scrollbar', () => assert.match(mobile, /scrollbar-width: thin/));
test('mobile tabs keep touch height', () => assert.match(mobile, /\.sw-home-store__tab \{ flex: 0 0 auto; min-height: 36px/));
test('mobile tabs preserve horizontal padding', () => assert.match(mobile, /\.sw-home-store__tab \{[^}]*padding-inline: 12px/));
test('mobile summary shares bounded width rule', () => assert.match(mobile, /\.sw-home-store__summary,[\s\S]*?\.sw-home-store__source-meta,[\s\S]*?max-width: 100%/));
test('mobile cards fill row width', () => assert.match(mobile, /\.sw-home-store__card \{ width: 100%/));
test('mobile cards cap row width', () => assert.match(mobile, /\.sw-home-store__card \{[^}]*max-width: 100%/));
test('mobile cards keep compact padding', () => assert.match(mobile, /\.sw-home-store__card \{[^}]*padding: 11px 12px/));
test('mobile card keeps bounded width', () => assert.match(mobile, /\.sw-home-store__card \{ width: 100%; max-width: 100%/));
test('mobile preview caps width', () => assert.match(mobile, /\.sw-home-store__preview \{ max-width: 100%/));
test('mobile preview clips overflow', () => assert.match(mobile, /\.sw-home-store__preview \{[^}]*overflow: hidden/));
test('mobile size row keeps action alignment', () => assert.match(mobile, /\.sw-home-store__sizes \.sw-home-store__add/));
test('mobile add action remains end aligned', () => assert.match(mobile, /\.sw-home-store__sizes \.sw-home-store__add \{ margin-inline-start: auto; \}/));
test('mobile source metadata caps width', () => assert.match(mobile, /\.sw-home-store__summary,[\s\S]*?\.sw-home-store__source-meta,[\s\S]*?max-width: 100%/));
test('mobile empty state caps width', () => assert.match(mobile, /\.sw-home-store__filter-empty \{ max-width: 100%/));
test('mobile empty state wraps text', () => assert.match(mobile, /\.sw-home-store__filter-empty \{[^}]*overflow-wrap: anywhere/));
test('mobile one-column rule is scoped to store grid', () => assert.match(mobile, /\.sw-home-store__grid/));
test('mobile tab rule is scoped to store tabs', () => assert.match(mobile, /\.sw-home-store__tab/));
test('mobile card rule is scoped to store cards', () => assert.match(mobile, /\.sw-home-store__card/));
test('mobile preview does not affect home widgets', () => assert.doesNotMatch(mobile, /\.sw-home__cell/));
test('mobile controls preserve non-positive flex basis', () => assert.match(mobile, /calc\(50% - 4px\)/));
test('mobile search keeps input clear affordance room', () => assert.match(mobile, /calc\(100% - 40px\)/));
test('mobile layout avoids fixed card pixel width', () => assert.doesNotMatch(mobile, /\.sw-home-store__card[^}]*width:\s*\d+px/));
test('mobile layout avoids horizontal grid columns', () => assert.doesNotMatch(mobile, /grid-template-columns:\s*repeat\(/));
test('mobile layout uses bounded overflow only', () => assert.match(mobile, /overflow: hidden|overflow-x: auto/));
test('mobile layout remains under narrow viewport breakpoint', () => assert.match(css, /@media \(max-width: 560px\)/));

test('mobile panel injects a dedicated mobile class', () => assert.match(source, /root\.classList\.add\("sw-home--mobile"\)/));
test('mobile panel class is guarded by device detection', () => assert.match(source, /if \(this\.isMobile\) root\.classList\.add/));
test('mobile panel uses mobile device key', () => assert.match(source, /const device = this\.isMobile \? "mobile" : "desktop"/));
test('mobile store dialog width is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(680px, 94vw\)"/));
test('mobile store dialog height is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(560px, 85vh\)"/));
test('mobile preview dialog width is bounded', () => assert.match(source, /this\.isMobile \? "min\(420px, 92vw\)"/));
test('mobile preview dialog height is bounded', () => assert.match(source, /this\.isMobile \? "min\(560px, 80vh\)"/));
test('mobile store cards use resolved size', () => assert.match(source, /device === "mobile" \? \[resolveMobileHomeSize\(declaredSizes\)\]/));
test('mobile size resolver is imported from home model', () => assert.match(source, /import \{normalizeHomeState, resolveMobileHomeSize\} from "\.\/home-model"/));
test('mobile store cards expose device support text', () => assert.match(source, /homeStoreSupportedSurfaces/));
test('mobile store root records device', () => assert.match(source, /root\.dataset\.device = device/));
test('mobile store uses region semantics', () => assert.match(source, /root\.setAttribute\("role", "region"\)/));
test('mobile store search uses search semantics', () => assert.match(source, /searchBar\.setAttribute\("role", "search"\)/));
test('mobile store searchbox uses enter key hint', () => assert.match(source, /searchInput\.setAttribute\("enterkeyhint", "search"\)/));
test('mobile store search disables autocomplete', () => assert.match(source, /searchInput\.autocomplete = "off"/));
test('mobile store tabs retain horizontal navigation', () => assert.match(source, /event\.key === "ArrowRight" \|\| event\.key === "ArrowDown"/));
test('mobile store tabs retain home navigation', () => assert.match(source, /if \(event\.key === "Home"\) next = 0/));
test('mobile store tabs retain end navigation', () => assert.match(source, /if \(event\.key === "End"\) next = buttons\.length - 1/));
test('mobile store tab navigation prevents page scroll', () => assert.match(source, /event\.preventDefault\(\);\s*activateStoreTab\(buttons\[next\]\)/));
test('mobile store cards use local focus navigation', () => assert.match(source, /root\.querySelectorAll<HTMLElement>\("\.sw-home-store__card:not\(\.fn__none\)"\)/));
test('mobile store card navigation supports vertical arrows', () => assert.match(source, /event\.key === "ArrowRight" \|\| event\.key === "ArrowDown"/));
test('mobile store card navigation supports home', () => assert.match(source, /if \(event\.key === "Home"\) next = 0/));
test('mobile store card navigation supports end', () => assert.match(source, /if \(event\.key === "End"\) next = cards\.length - 1/));
test('mobile store size controls keep touch action', () => assert.match(css, /\.sw-home-store__size[\s\S]*?touch-action: manipulation/));
test('mobile store add controls keep touch action', () => assert.match(css, /\.sw-home-store__add[\s\S]*?touch-action: manipulation/));
test('mobile store tab controls keep touch action', () => assert.match(css, /\.sw-home-store__tab[\s\S]*?touch-action: manipulation/));
test('mobile store guide keeps touch action', () => assert.match(css, /\.sw-home-store__guide[\s\S]*?touch-action: manipulation/));
test('mobile store grid keeps isolation', () => assert.match(css, /\.sw-home-store__grid[\s\S]*?isolation: isolate/));
test('mobile store cards keep border box sizing', () => assert.match(css, /\.sw-home-store__card[\s\S]*?box-sizing: border-box/));
test('mobile store cards keep minimum width zero', () => assert.match(css, /\.sw-home-store__card[\s\S]*?min-width: 0/));
test('mobile store cards keep maximum width full', () => assert.match(css, /\.sw-home-store__card[\s\S]*?max-width: 100%/));
test('mobile store summary permits arbitrary wrapping', () => assert.match(css, /\.sw-home-store__summary[\s\S]*?overflow-wrap: anywhere/));
test('mobile store source chips permit arbitrary wrapping', () => assert.match(css, /\.sw-home-store__source-chip[\s\S]*?max-width: 100%/));
test('mobile store empty result is aria hidden when inactive', () => assert.match(source, /filterEmptyState\?\.setAttribute\("aria-hidden", String\(hasVisibleCards\)\)/));
test('mobile store empty result has atomic live semantics', () => assert.match(source, /filterEmptyState\.setAttribute\("aria-atomic", "true"\)/));
test('mobile store result summary has atomic live semantics', () => assert.match(source, /resultSummary\.setAttribute\("aria-atomic", "true"\)/));
test('mobile store clear filters restores all tab', () => assert.match(source, /storeTab = "all"/));
test('mobile store clear filters restores search focus', () => assert.match(source, /applyFilter\(\);\s*searchInput\.focus\(\)/));
test('mobile store add action remains independent from size selection', () => assert.match(source, /dataset\.action = added \? "apply-size" : "add"/));
test('mobile store preview action remains a button', () => assert.match(source, /previewButton\.type = "button"/));
test('mobile store configure action remains a button', () => assert.match(source, /configButton\.type = "button"/));
test('mobile store remove action remains a button', () => assert.match(source, /removeButton\.type = "button"/));
test('mobile store does not install document-level card key handlers', () => assert.doesNotMatch(storeSource, /document\.addEventListener\("keydown"/));
test('mobile store keeps provider rescan bounded', () => assert.match(source, /window\.setTimeout\(\(\) => \{[\s\S]*?renderStore\(\);[\s\S]*?\}, 400\)/));

// T-3635~T-3664: visual accessibility, touch targets, print and safe-area contracts.
test('mobile panel grid is explicitly single column', () => assert.match(css, /\.sw-home--mobile \.sw-home__grid\s*\{[\s\S]*?grid-template-columns:\s*1fr\s*!important/));
test('mobile panel cells remain full width', () => assert.match(css, /\.sw-home--mobile \.sw-home__cell\s*\{[\s\S]*?width:\s*100%/));
test('store add action has a minimum touch height', () => assert.match(css, /\.sw-home-store__add\s*\{[\s\S]*?min-height:\s*28px/));
test('store configure action has a minimum touch height', () => assert.match(css, /\.sw-home-store__configure\s*\{[\s\S]*?min-height:\s*28px/));
test('store remove action has a minimum touch height', () => assert.match(css, /\.sw-home-store__remove\s*\{[\s\S]*?min-height:\s*28px/));
test('store add action prevents label wrapping', () => assert.match(css, /\.sw-home-store__add\s*\{[\s\S]*?white-space:\s*nowrap/));
test('store configure action prevents label wrapping', () => assert.match(css, /\.sw-home-store__configure\s*\{[\s\S]*?white-space:\s*nowrap/));
test('store remove action prevents label wrapping', () => assert.match(css, /\.sw-home-store__remove\s*\{[\s\S]*?white-space:\s*nowrap/));
test('store clear search keeps manipulation touch action', () => assert.match(css, /\.sw-home-store__clear-search[\s\S]*?touch-action:\s*manipulation/));
test('store clear filters keeps manipulation touch action', () => assert.match(css, /\.sw-home-store__clear-filters[\s\S]*?touch-action:\s*manipulation/));
test('store group toggle keeps manipulation touch action', () => assert.match(css, /\.sw-home-store__group-toggle[\s\S]*?touch-action:\s*manipulation/));
test('store unavailable removal keeps manipulation touch action', () => assert.match(css, /\.sw-home-store__remove-unavailable[\s\S]*?touch-action:\s*manipulation/));
test('store reduced-motion media query exists', () => assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)/));
test('store cards disable transitions for reduced motion', () => assert.match(css, /\.sw-home-store__card,[\s\S]*?\.sw-home-store__tab\s*\{[\s\S]*?transition:\s*none\s*!important/));
test('store tabs disable transitions for reduced motion', () => assert.match(css, /\.sw-home-store__tab\s*\{[\s\S]*?transition:\s*none\s*!important/));
test('store card hover transform is disabled for reduced motion', () => assert.match(css, /\.sw-home-store__card:hover\s*\{[\s\S]*?transform:\s*none/));
test('mobile reduced motion keeps cards visible', () => assert.match(css, /@media \(max-width: 560px\) and \(prefers-reduced-motion: reduce\)[\s\S]*?content-visibility:\s*visible/));
test('mobile reduced motion limits card containment to layout', () => assert.match(css, /@media \(max-width: 560px\) and \(prefers-reduced-motion: reduce\)[\s\S]*?contain:\s*layout/));
test('forced colors media query exists', () => assert.match(css, /@media \(forced-colors:\s*active\)/));
test('forced colors preserve system color adjustment', () => assert.match(css, /forced-color-adjust:\s*auto/));
test('forced colors use Canvas background', () => assert.match(css, /background:\s*Canvas/));
test('forced colors use CanvasText foreground', () => assert.match(css, /color:\s*CanvasText/));
test('forced colors focus uses Highlight outline', () => assert.match(css, /\.sw-home-store__card:focus-visible,[\s\S]*?outline:\s*2px solid Highlight/));
test('forced colors focus outline has offset', () => assert.match(css, /outline-offset:\s*2px/));
test('forced colors active tab uses Highlight border', () => assert.match(css, /\.sw-home-store__tab\.is-active[\s\S]*?border-bottom-color:\s*Highlight/));
test('forced colors active tab uses HighlightText', () => assert.match(css, /\.sw-home-store__tab\.is-active[\s\S]*?color:\s*HighlightText/));
test('forced colors active tab uses Highlight background', () => assert.match(css, /\.sw-home-store__tab\.is-active[\s\S]*?background:\s*Highlight/));
test('print mode hides store search controls', () => assert.match(css, /@media print[\s\S]*?\.sw-home-store__search,[\s\S]*?display:\s*none\s*!important/));
test('print mode hides store tabs', () => assert.match(css, /@media print[\s\S]*?\.sw-home-store__tabs,[\s\S]*?display:\s*none\s*!important/));
test('print mode hides store size controls', () => assert.match(css, /@media print[\s\S]*?\.sw-home-store__sizes,[\s\S]*?display:\s*none\s*!important/));
test('print mode hides store previews', () => assert.match(css, /@media print[\s\S]*?\.sw-home-store__preview,[\s\S]*?display:\s*none\s*!important/));
test('print mode keeps cards together', () => assert.match(css, /\.sw-home-store__card\s*\{[\s\S]*?break-inside:\s*avoid/));
test('print mode removes card shadows', () => assert.match(css, /\.sw-home-store__card\s*\{[\s\S]*?box-shadow:\s*none/));
test('print mode gives cards a neutral border', () => assert.match(css, /\.sw-home-store__card\s*\{[\s\S]*?border:\s*1px solid #888/));
test('print mode uses readable black text', () => assert.match(css, /\.sw-home-store__card\s*\{[\s\S]*?color:\s*#000/));
test('print mode uses white card background', () => assert.match(css, /\.sw-home-store__card\s*\{[\s\S]*?background:\s*#fff/));
test('card title block can shrink', () => assert.match(css, /\.sw-home-store__card-head[\s\S]*?> div \{ min-width:\s*0; \}/));
test('card title allows arbitrary wrapping', () => assert.match(css, /\.sw-home-store__card-head[\s\S]*?overflow-wrap:\s*anywhere/));
test('card summary has zero minimum width', () => assert.match(css, /\.sw-home-store__summary[\s\S]*?min-width:\s*0/));
test('card source metadata wraps flex children', () => assert.match(css, /\.sw-home-store__source-meta\s*\{[\s\S]*?flex-wrap:\s*wrap/));
test('card source chip is capped to container width', () => assert.match(css, /\.sw-home-store__source-chip\s*\{[\s\S]*?max-width:\s*100%/));
test('mobile tab strip contains horizontal overscroll', () => assert.match(css, /\.sw-home-store__tabs\s*\{[\s\S]*?overscroll-behavior-x:\s*contain/));
test('mobile layout preserves safe-area bottom inset somewhere in UI', () => assert.match(css, /padding[^;]*env\(safe-area-inset-bottom,\s*0px\)/));
test('mobile settings body preserves safe-area bottom inset', () => assert.match(css, /\.sw-settings-dialog[\s\S]*?padding-bottom:\s*env\(safe-area-inset-bottom,\s*0px\)/));
test('mobile card preview is overflow clipped', () => assert.match(mobile, /\.sw-home-store__preview\s*\{[^}]*overflow:\s*hidden/));
test('mobile card source metadata cannot exceed viewport width', () => assert.match(mobile, /\.sw-home-store__source-meta,[\s\S]*?max-width:\s*100%/));
test('mobile empty state supports arbitrary wrapping', () => assert.match(mobile, /\.sw-home-store__filter-empty\s*\{[^}]*overflow-wrap:\s*anywhere/));

// T-3665~T-3694: store semantics, focus restoration and state announcements.
test('store root initializes active tab state', () => assert.match(source, /root\.dataset\.activeTab = storeTab/));
test('store root initializes aria busy state', () => assert.match(source, /root\.setAttribute\("aria-busy", "false"\)/));
test('store render announces busy state before loading', () => assert.match(source, /root\.setAttribute\("aria-busy", "true"\)/));
test('store render clears busy state after loading', () => assert.match(source, /root\.setAttribute\("aria-busy", "false"\)/));
test('store tabs expose selected state', () => assert.match(source, /btn\.setAttribute\("aria-selected", String\(tab\.key === storeTab\)\)/));
test('store tabs expose current page state', () => assert.match(source, /btn\.setAttribute\("aria-current", tab\.key === storeTab \? "page" : "false"\)/));
test('store tabs use roving tabindex', () => assert.match(source, /btn\.setAttribute\("tabindex", tab\.key === storeTab \? "0" : "-1"\)/));
test('store tabs control the result summary', () => assert.match(source, /btn\.setAttribute\("aria-controls", "sw-home-store-result-summary"\)/));
test('store result summary has status role', () => assert.match(source, /resultSummary\.setAttribute\("role", "status"\)/));
test('store result summary uses polite live updates', () => assert.match(source, /resultSummary\.setAttribute\("aria-live", "polite"\)/));
test('store result summary is atomic', () => assert.match(source, /resultSummary\.setAttribute\("aria-atomic", "true"\)/));
test('store result summary exposes state data', () => assert.match(source, /resultSummary\.dataset\.state = summary\.visible > 0 \? "results" : "empty"/));
test('store result summary exposes visible count', () => assert.match(source, /resultSummary\.dataset\.visible = String\(summary\.visible\)/));
test('store result summary exposes total count', () => assert.match(source, /resultSummary\.dataset\.total = String\(summary\.total\)/));
test('store result summary exposes added count', () => assert.match(source, /resultSummary\.dataset\.added = String\(summary\.added\)/));
test('store cards reference the live result summary', () => assert.match(source, /button\.setAttribute\("aria-describedby", resultSummary\?\.id \|\| "sw-home-store-result-summary"\)/));
test('store tab activation updates root active tab', () => assert.match(source, /root\.dataset\.activeTab = storeTab/));
test('store tab activation reapplies filtering', () => assert.match(source, /storeTab = button\.dataset\.tabKey \|\| "all";[\s\S]*?applyFilter\(\)/));
test('store tab keyboard navigation focuses target', () => assert.match(source, /buttons\[next\]\.focus\(\)/));
test('store card keyboard navigation focuses target', () => assert.match(source, /cards\[next\]\.focus\(\)/));
test('store card navigation prevents default page movement', () => assert.match(source, /event\.preventDefault\(\);\s*cards\[next\]\.focus\(\)/));
test('store card navigation returns focus to search when empty', () => assert.match(source, /else searchInput\.focus\(\{preventScroll: true\}\)/));
test('store filter empty state has status role', () => assert.match(source, /filterEmptyState\.setAttribute\("role", "status"\)/));
test('store filter empty state uses polite live updates', () => assert.match(source, /filterEmptyState\.setAttribute\("aria-live", "polite"\)/));
test('store filter empty state is atomic', () => assert.match(source, /filterEmptyState\.setAttribute\("aria-atomic", "true"\)/));
test('store clear filters is a typed button', () => assert.match(source, /clearFilters\.type = "button"/));
test('store clear filters exposes an action key', () => assert.match(source, /clearFilters\.dataset\.action = "clear-filters"/));
test('store clear filters restores active tab selection', () => assert.match(source, /storeTab = "all";[\s\S]*?button\.setAttribute\("aria-selected", String\(active\)\)/));
test('store clear filters restores roving tabindex', () => assert.match(source, /button\.setAttribute\("tabindex", active \? "0" : "-1"\)/));
test('store clear filters returns focus to search', () => assert.match(source, /searchInput\.focus\(\)/));
test('store group toggle exposes expanded state', () => assert.match(source, /groupToggle\.setAttribute\("aria-expanded", String\(!collapsedGroups\.has\(label\)\)\)/));
test('store group toggle controls a stable grid id', () => assert.match(source, /groupToggle\.setAttribute\("aria-controls", groupId\)/));
test('store group headings expose heading semantics', () => assert.match(source, /groupHeading\.setAttribute\("role", "heading"\)/));
test('store group headings expose level three', () => assert.match(source, /groupHeading\.setAttribute\("aria-level", "3"\)/));
test('store card size controls expose orientation', () => assert.match(source, /tiles\.setAttribute\("aria-orientation", "horizontal"\)/));
test('store size buttons expose selected state', () => assert.match(source, /tile\.setAttribute\("aria-pressed", String\(tile === selectedTile\)\)/));
test('store size group records module id', () => assert.match(source, /tiles\.dataset\.moduleId = moduleId/));
test('store action buttons preserve operation metadata', () => assert.match(source, /addButton\.dataset\.action = added \? "apply-size" : "add"/));
test('store preview button preserves operation metadata', () => assert.match(source, /previewButton\.dataset\.action = "preview"/));
test('store configure button preserves operation metadata', () => assert.match(source, /configButton\.dataset\.action = "configure"/));
test('store remove button preserves operation metadata', () => assert.match(source, /removeButton\.dataset\.action = "remove"/));
test('store dialog close restores opener focus', () => assert.match(source, /if \(opener\?\.isConnected\) opener\.focus\(\)/));

// T-3695~T-3724: loading, availability and graceful-degradation contracts.
test('store render version starts at zero', () => assert.match(source, /root\.dataset\.renderVersion = "0"/));
test('store render version increments on refresh', () => assert.match(source, /root\.dataset\.renderVersion = String\(Number\(root\.dataset\.renderVersion \|\| "0"\) \+ 1\)/));
test('store records ready module count', () => assert.match(source, /root\.dataset\.readyCount = String\(activeIds\.size\)/));
test('store search restores persisted query value', () => assert.match(source, /searchInput\.value = storeQuery/));
test('store clear search is a typed button', () => assert.match(source, /clearSearchButton\.type = "button"/));
test('store clear search exposes an action key', () => assert.match(source, /clearSearchButton\.dataset\.action = "clear-search"/));
test('store clear search hides when query is empty', () => assert.match(source, /clearSearchButton\.hidden = !storeQuery/));
test('store clear search returns focus to input', () => assert.match(source, /clearSearchButton\.addEventListener\("click", \(\) => \{[\s\S]*?searchInput\.focus\(\)/));
test('store sort control exposes an action key', () => assert.match(source, /sortSelect\.dataset\.action = "sort"/));
test('store sort control references result summary', () => assert.match(source, /sortSelect\.setAttribute\("aria-controls", "sw-home-store-result-summary"\)/));
test('store sort change normalizes selected value', () => assert.match(source, /storeSort = normalizeHomeStoreSort\(sortSelect\.value\)/));
test('store guide is a typed button', () => assert.match(source, /guideButton\.type = "button"/));
test('store guide exposes an action key', () => assert.match(source, /guideButton\.dataset\.action = "open-guide"/));
test('store guide announces dialog popup', () => assert.match(source, /guideButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('store filtering normalizes query input', () => assert.match(source, /const query = normalizeHomeStoreQuery\(searchInput\.value\)/));
test('store filtering records active filter', () => assert.match(source, /root\.dataset\.activeFilter = filter\.tab/));
test('store filtering records sort state', () => assert.match(source, /root\.dataset\.sort = storeSort/));
test('store filtering toggles card visibility class', () => assert.match(source, /card\.classList\.toggle\("fn__none", !visible\)/));
test('store filtering exposes card aria-hidden state', () => assert.match(source, /card\.setAttribute\("aria-hidden", String\(!visible\)\)/));
test('store filtering records card match state', () => assert.match(source, /card\.dataset\.filterMatch = String\(visible\)/));
test('store filtering hides empty groups', () => assert.match(source, /heading\.classList\.toggle\("fn__none", !visible\)/));
test('store filtering exposes group aria-hidden state', () => assert.match(source, /heading\.setAttribute\("aria-hidden", String\(!visible\)\)/));
test('store filtering preserves collapsed grid state', () => assert.match(source, /grid\.setAttribute\("aria-hidden", String\(!visible \|\| heading\.dataset\.collapsed === "true"\)\)/));
test('store filtered focus falls back to first visible card', () => assert.match(source, /root\.querySelector<HTMLElement>\("\.sw-home-store__card:not\(\.fn__none\)"\)/));
test('store filtered focus falls back to search input', () => assert.match(source, /else searchInput\.focus\(\{preventScroll: true\}\)/));
test('store tabs expose collection size', () => assert.match(source, /btn\.setAttribute\("aria-setsize", String\(tabs\.length\)\)/));
test('store tabs expose collection position', () => assert.match(source, /btn\.setAttribute\("aria-posinset", String\(tabIndex \+ 1\)\)/));
test('store pending section uses level two heading', () => assert.match(source, /pendingHeading\.setAttribute\("aria-level", "2"\)/));
test('store pending section has stable id', () => assert.match(source, /pendingHeading\.id = "sw-home-store-section-pending"/));
test('store pending grid uses group role', () => assert.match(source, /pendingGrid\.setAttribute\("role", "group"\)/));
test('store pending grid labels from section heading', () => assert.match(source, /pendingGrid\.setAttribute\("aria-labelledby", pendingHeading\.id\)/));
test('store unavailable card has unavailable status', () => assert.match(source, /card\.dataset\.status = unavailable \? "unavailable" : "requires-provider"/));
test('store unavailable card uses warning tone', () => assert.match(source, /card\.dataset\.statusTone = unavailable \? "warning" : "info"/));
test('store pending card records external availability', () => assert.match(source, /card\.dataset\.availability = "external"/));
test('store pending card labels its title', () => assert.match(source, /card\.setAttribute\("aria-labelledby", title\.id\)/));
test('store unavailable removal is a typed button', () => assert.match(source, /removeButton\.type = "button"/));
test('store unavailable removal exposes an action key', () => assert.match(source, /removeButton\.dataset\.action = "remove-unavailable"/));
test('store unavailable removal guards missing instance', () => assert.match(source, /const instance = instanceStateByModule\.get\(entry\.moduleId\);\s*if \(!instance\) return/));
test('store empty catalog resets ready and pending counts', () => assert.match(source, /root\.dataset\.readyCount = "0";\s*root\.dataset\.pendingCount = "0"/));
test('store empty catalog clears busy state', () => assert.match(source, /root\.textContent = this\.i18n\.homeNoMoreModules;[\s\S]*?root\.setAttribute\("aria-busy", "false"\)/));
test('store rescan timer is cancelled on destroy', () => assert.match(source, /window\.clearTimeout\(rescanTimer\)/));
test('store change listener is removed on destroy', () => assert.match(source, /this\.homeModuleChangeListeners\.delete\(handleModuleChange\)/));

// T-3735~T-3774: guide, live preview and configuration-dialog contracts.
test('store guide dialog uses localized title', () => assert.match(source, /title: this\.i18n\.homeStoreGuideTitle/));
test('store guide dialog mounts a dedicated root', () => assert.match(source, /content: '<div class="speed-switch sw-home-store-guide"><\/div>'/));
test('store guide mobile width is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(520px, 94vw\)"/));
test('store guide mobile height is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(640px, 82vh\)"/));
test('store guide links to the canonical document', () => assert.match(source, /link\.href = "https:\/\/github\.com\/ai68298100\/siyuan-speed-switch\/blob\/main\/docs\/component-store-guide\.md"/));
test('store guide opens documentation in a new tab', () => assert.match(source, /link\.target = "_blank"/));
test('store guide external link prevents opener access', () => assert.match(source, /link\.rel = "noopener noreferrer"/));
test('store guide exposes the local document path', () => assert.match(source, /note\.textContent = "docs\/component-store-guide\.md"/));
test('store preview captures its opener', () => assert.match(source, /const opener = document\.activeElement instanceof HTMLElement \? document\.activeElement : null/));
test('store preview falls back to medium size list', () => assert.match(source, /def\.sizes\.length > 0 \? def\.sizes : \["medium"\]/));
test('store preview prefers a declared medium size', () => assert.match(source, /const sizeKey = sizes\.includes\("medium"\) \? "medium" : sizes\[0\]/));
test('store preview dialog includes component title', () => assert.match(source, /title: `\$\{this\.i18n\.homeStorePreview\} · \$\{def\.title \|\| moduleId\}`/));
test('store preview mobile width is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(420px, 92vw\)"/));
test('store preview mobile height is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(560px, 80vh\)"/));
test('store preview root records module id', () => assert.match(source, /container\.dataset\.moduleId = moduleId/));
test('store preview root records device', () => assert.match(source, /container\.dataset\.device = device/));
test('store preview root records resolved size', () => assert.match(source, /container\.dataset\.size = sizeKey/));
test('store preview root uses region semantics', () => assert.match(source, /container\.setAttribute\("role", "region"\)/));
test('store preview root has a component label', () => assert.match(source, /container\.setAttribute\("aria-label", `\$\{this\.i18n\.homeStorePreview\} · \$\{def\.title \|\| moduleId\}`\)/));
test('store preview announces initial busy state', () => assert.match(source, /container\.setAttribute\("aria-busy", "true"\)/));
test('store preview records direct integration fallback', () => assert.match(source, /container\.dataset\.integration = sourceInfo\?\.integration \|\| "direct"/));
test('store preview records no-privacy fallback', () => assert.match(source, /container\.dataset\.privacy = sourceInfo\?\.privacy \|\| "none"/));
test('store preview metadata uses note role', () => assert.match(source, /meta\.setAttribute\("role", "note"\)/));
test('store preview metadata chips record tone', () => assert.match(source, /chip\.dataset\.tone = tone/));
test('store preview metadata chips expose labels', () => assert.match(source, /chip\.setAttribute\("aria-label", label\)/));
test('store preview body uses status role', () => assert.match(source, /body\.setAttribute\("role", "status"\)/));
test('store preview body uses polite live updates', () => assert.match(source, /body\.setAttribute\("aria-live", "polite"\)/));
test('store preview body updates atomically', () => assert.match(source, /body\.setAttribute\("aria-atomic", "true"\)/));
test('store preview body starts busy', () => assert.match(source, /body\.setAttribute\("aria-busy", "true"\)/));
test('store preview body is keyboard focusable', () => assert.match(source, /body\.tabIndex = 0/));
test('store preview body references metadata', () => assert.match(source, /body\.setAttribute\("aria-describedby", meta\.id\)/));
test('store preview read passes resolved size', () => assert.match(source, /this\.homeRuntime\.read\(moduleId, device, config \|\| \{\}, \{\.\.\.readOptions, size: sizeKey\}\)/));
test('store preview controller provides error label', () => assert.match(source, /error: this\.i18n\.homeModuleError/));
test('store preview controller provides retry label', () => assert.match(source, /retry: this\.i18n\.homeRetry/));
test('store preview item activation closes dialog', () => assert.match(source, /this\.handleHomeItemAction\(item, \(\) => dialog\.destroy\(\)\)/));
test('store preview task failure is surfaced', () => assert.match(source, /if \(!ok\) showMessage\(this\.i18n\.homeTaskToggleFailed\)/));
test('store preview task toggle refreshes content', () => assert.match(source, /await controller\?\.refresh\(\)/));
test('store preview disposal is idempotent', () => assert.match(source, /if \(disposed\) return;\s*disposed = true/));
test('store preview disposal releases controller', () => assert.match(source, /controller\?\.dispose\(\)/));
test('store preview disposal clears interval', () => assert.match(source, /if \(disposeTimer\) window\.clearInterval\(disposeTimer\)/));
test('store preview first refresh is forced', () => assert.match(source, /controller\.refresh\(\{\}, \{force: true\}\)/));
test('store preview clears busy on success and failure', () => assert.match(source, /\.then\(markPreviewReady, markPreviewReady\)/));
test('store preview disconnect watcher is bounded', () => assert.match(source, /window\.setInterval\(\(\) => \{[\s\S]*?disposePreview\(\);[\s\S]*?\}, 1500\)/));
test('home config mobile width is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(480px, 92vw\)"/));
test('home config mobile height is viewport bounded', () => assert.match(source, /this\.isMobile \? "min\(420px, 80vh\)"/));
test('home config edits a detached draft', () => assert.match(source, /const draft: Record<string, unknown> = \{\.\.\.inst\.config\}/));
test('home config reset is a typed button', () => assert.match(source, /reset\.type = "button"/));
test('home config cancel is a typed button', () => assert.match(source, /cancel\.type = "button"/));
test('home config save is a typed button', () => assert.match(source, /save\.type = "button"/));
test('home config invalid control reports validity', () => assert.match(source, /invalid\.reportValidity\(\)/));
test('home config invalid control receives focus', () => assert.match(source, /invalid\.focus\(\)/));
test('home config save copies the draft', () => assert.match(source, /instance\.config = \{\.\.\.draft\}/));
test('home config save persists normalized state', () => assert.match(source, /instance\.config = \{\.\.\.draft\};\s*this\.saveHomeState\(next\)/));
test('home config save closes dialog', () => assert.match(source, /this\.saveHomeState\(next\);[\s\S]*?dialog\.destroy\(\)/));
test('home config save invokes refresh callback', () => assert.match(source, /dialog\.destroy\(\);\s*onSaved\(\)/));

// T-3775~T-3814: configuration field semantics and preview metadata details.
test('home config mounts a dedicated root', () => assert.match(source, /content: '<div class="speed-switch sw-home-config"><\/div>'/));
test('home config clears stale root content', () => assert.match(source, /root\.innerHTML = ""/));
test('home config tracks controls by field key', () => assert.match(source, /const controls = new Map<string, HTMLInputElement \| HTMLSelectElement>\(\)/));
test('home config tracks reset keys', () => assert.match(source, /const resetKeys = new Set<string>\(\)/));
test('home config number defaults use finite values', () => assert.match(source, /Number\.isFinite\(field\.defaults\)/));
test('home config select defaults stay within options', () => assert.match(source, /\(field\.options \|\| \[\]\)\.includes\(field\.defaults as string\)/));
test('home config reset updates draft state', () => assert.match(source, /draft\[field\.key\] = field\.type === "number" \? Number\(value\) : value/));
test('home config reset marks fields for reset', () => assert.match(source, /resetKeys\.add\(field\.key\)/));
test('home config labels target generated controls', () => assert.match(source, /label\.htmlFor = controlId/));
test('home config select controls use block styling', () => assert.match(source, /select\.className = "b3-select fn__block"/));
test('home config select fields render declared options', () => assert.match(source, /\(field\.options \|\| \[\]\)\.forEach\(\(option\) =>/));
test('home config select changes update draft', () => assert.match(source, /select\.addEventListener\("change", \(\) => \{ draft\[field\.key\] = select\.value; \}\)/));
test('home config notebook controls start disabled', () => assert.match(source, /select\.disabled = true;[\s\S]*?notebookLoading/));
test('home config notebook controls expose loading option', () => assert.match(source, /loading\.textContent = this\.i18n\.notebookLoading/));
test('home config notebook fill exposes empty option', () => assert.match(source, /emptyOption\.textContent = this\.i18n\.notebookPlaceholder/));
test('home config notebook preserves stale values', () => assert.match(source, /homeConfigUnavailableValue/));
test('home config notebook controls enable after fill', () => assert.match(source, /select\.disabled = false/));
test('home config document input uses bounded length', () => assert.match(source, /input\.maxLength = 64/));
test('home config document input validates block id shape', () => assert.match(source, /input\.pattern = "\[0-9\]\{14\}-\[0-9a-zA-Z\]\+"/));
test('home config document input has suggestions list', () => assert.match(source, /input\.setAttribute\("list", suggestions\.id\)/));
test('home config document suggestions are capped', () => assert.match(source, /currentDocumentSetEntries\(\)\.slice\(0, 40\)/));
test('home config document changes are bounded', () => assert.match(source, /draft\[field\.key\] = input\.value\.slice\(0, 64\)/));
test('home config numeric fields use number input', () => assert.match(source, /input\.type = "number"/));
test('home config numeric fields expose minimum', () => assert.match(source, /input\.min = String\(field\.min \?\? 0\)/));
test('home config numeric fields expose maximum', () => assert.match(source, /input\.max = String\(field\.max \?\? 100\)/));
test('home config numeric changes clamp to range', () => assert.match(source, /Math\.min\(max, Math\.max\(min, Math\.trunc\(parsed\)\)\)/));
test('home config date fields use date input', () => assert.match(source, /input\.type = "date"/));
test('home config date fields have lower bound', () => assert.match(source, /input\.min = "1900-01-01"/));
test('home config date fields have upper bound', () => assert.match(source, /input\.max = "2100-12-31"/));
test('home config text fields are bounded', () => assert.match(source, /input\.maxLength = 128/));
test('home config reset action applies every schema default', () => assert.match(source, /schema\.forEach\(\(field\) => applyDefault\(field\)\)/));
test('home config cancel action destroys dialog', () => assert.match(source, /cancel\.addEventListener\("click", \(\) => dialog\.destroy\(\)\)/));
test('home config save searches invalid controls', () => assert.match(source, /root\.querySelector<HTMLInputElement \| HTMLSelectElement>\("input:invalid, select:invalid"\)/));
test('home config save finds the persisted instance', () => assert.match(source, /find\(\(candidate\) => candidate\.instanceId === inst\.instanceId\)/));
test('home config save preserves unrelated instances', () => assert.match(source, /const next = this\.getHomeState\(\)/));
test('home config save closes only after persistence', () => assert.match(source, /this\.saveHomeState\(next\);\s*\}\s*dialog\.destroy\(\)/));
test('preview ready clears container busy state', () => assert.match(source, /container\.setAttribute\("aria-busy", "false"\)/));
test('preview ready clears body busy state', () => assert.match(source, /body\.setAttribute\("aria-busy", "false"\)/));
test('preview disposal restores opener focus', () => assert.match(source, /if \(opener\?\.isConnected\) opener\.focus\(\)/));
test('preview metadata receives stable id', () => assert.match(source, /meta\.id = `\$\{previewId\}-meta`/));
test('preview body receives stable id', () => assert.match(source, /body\.id = `\$\{previewId\}-body`/));
test('preview body records component and device metadata', () => assert.match(source, /body\.dataset\.moduleId = moduleId;\s*body\.dataset\.device = device/));
test('preview surface metadata is rendered', () => assert.match(source, /homeStorePreviewSurface\.replace\("\{surface\}", surfaceLabels\[device\] \|\| device\)/));
test('preview size metadata is rendered', () => assert.match(source, /homeStorePreviewSize\.replace\("\{size\}", sizeKey\)/));
test('preview controller receives cached-source label', () => assert.match(source, /sourceCached: this\.i18n\.homeSourceCached/));
test('preview controller receives stale-source label', () => assert.match(source, /sourceStale: this\.i18n\.homeSourceStale/));
test('preview disconnect watcher checks dialog connectivity', () => assert.match(source, /if \(!dialog\.element\.isConnected\)/));

// T-3855~T-3894: field accessibility, async notebook safety and preview provenance.
test('config title includes module id', () => assert.match(source, /title: `\$\{this\.i18n\.homeConfig\} · \$\{inst\.moduleId\}`/));
test('config dialog content uses home-config root', () => assert.match(source, /sw-home-config/));
test('config field labels expose field text', () => assert.match(source, /label\.textContent = field\.label/));
test('config generated control id includes instance id', () => assert.match(source, /sw-home-config-\$\{inst\.instanceId\}/));
test('config generated control id includes field key', () => assert.match(source, /\$\{field\.key\}`\.replace/));
test('config select control receives generated id', () => assert.match(source, /select\.id = controlId/));
test('config notebook control receives generated id', () => assert.match(source, /select\.id = controlId[\s\S]*?notebook/));
test('config document control receives generated id', () => assert.match(source, /input\.id = controlId/));
test('config label and control are placed in same row', () => assert.match(source, /row\.appendChild\(label\)[\s\S]*?row\.appendChild\((select|input)\)/));
test('config select value starts from draft', () => assert.match(source, /select\.value = current/));
test('config select draft starts from selected value', () => assert.match(source, /draft\[field\.key\] = select\.value/));
test('config notebook current value reads draft', () => assert.match(source, /typeof draft\[field\.key\] === "string"/));
test('config notebook current value is bounded by option list', () => assert.match(source, /!options\.some\(\(nb\) => nb\.id === current\)/));
test('config stale notebook option uses current id', () => assert.match(source, /stale\.value = current/));
test('config stale notebook option is labelled unavailable', () => assert.match(source, /stale\.textContent = `\$\{current\} · \$\{this\.i18n\.homeConfigUnavailableValue\}`/));
test('config notebook selects restored value after fill', () => assert.match(source, /select\.value = resetKeys\.has\(field\.key\) \? "" : current/));
test('config notebook change listener is installed', () => assert.match(source, /select\.addEventListener\("change", \(\) => \{ draft\[field\.key\] = select\.value; \}\)/));
test('config notebook promise checks field options', () => assert.match(source, /void this\.loadNotebooks\(\)\.then\(\(notebooks\) => \{\s*fill\(notebooks\)/));
test('config document input has placeholder', () => assert.match(source, /input\.placeholder = this\.i18n\.homeConfigDocumentPlaceholder/));
test('config document input starts from draft', () => assert.match(source, /input\.value = typeof draft\[field\.key\] === "string"/));
test('config document input records initial draft', () => assert.match(source, /draft\[field\.key\] = input\.value/));
test('config document suggestions use root ids', () => assert.match(source, /option\.value = entry\.rootId/));
test('config document suggestions use titles', () => assert.match(source, /option\.label = entry\.title/));
test('config document input references datalist', () => assert.match(source, /input\.setAttribute\("list", suggestions\.id\)/));
test('config date input has bounded year range', () => assert.match(source, /1900-01-01[\s\S]*2100-12-31/));
test('config numeric input stores numeric draft', () => assert.match(source, /draft\[field\.key\] = field\.type === "number" \? Number\(input\.value\) : input\.value/));
test('config numeric change rejects non-finite values', () => assert.match(source, /Number\.isFinite\(parsed\) \? Math\.min/));
test('config numeric invalid fallback uses default', () => assert.match(source, /: field\.defaults \?\? min/));
test('config text change truncates to protocol bound', () => assert.match(source, /input\.value\.slice\(0, 128\)/));
test('config default helper handles null defaults', () => assert.match(source, /return field\.defaults == null \? "" : String\(field\.defaults\)/));
test('config default helper truncates number defaults', () => assert.match(source, /return Math\.trunc\(fallback\)/));
test('config reset updates control only when present', () => assert.match(source, /const control = controls\.get\(field\.key\);\s*if \(!control\) return/));
test('config reset writes string control values', () => assert.match(source, /control\.value = String\(value\)/));
test('config reset button iterates schema', () => assert.match(source, /reset\.addEventListener\("click", \(\) => \{\s*schema\.forEach/));
test('config cancel button has localized label', () => assert.match(source, /cancel\.textContent = this\.i18n\.cancel/));
test('config save button has localized label', () => assert.match(source, /save\.textContent = this\.i18n\.homeConfigSave/));
test('config save validates before reading home state', () => assert.match(source, /if \(invalid\) \{[\s\S]*?return;\s*\}\s*const next = this\.getHomeState\(\)/));
test('config save copies only draft fields', () => assert.match(source, /instance\.config = \{\.\.\.draft\}/));
test('preview source fallback provider is SiYuan', () => assert.match(source, /sourceInfo\?\.providerName \|\| "SiYuan"/));
test('preview integration fallback is offline-safe', () => assert.match(source, /sourceInfo\?\.integration === "http" \? "network" : sourceInfo\?\.integration === "local-bridge" \? "local" : "offline"/));
test('preview privacy metadata is always emitted', () => assert.match(source, /addMeta\(privacy, "privacy"\)/));
test('preview surface map covers desktop', () => assert.match(source, /desktop: this\.i18n\.homeStoreDeviceDesktop/));
test('preview surface map covers sidebar', () => assert.match(source, /sidebar: this\.i18n\.homeStoreDeviceSidebar/));
test('preview surface map covers mobile', () => assert.match(source, /mobile: this\.i18n\.homeStoreDeviceMobile/));
test('preview body labels source freshness', () => assert.match(source, /sourceFresh: this\.i18n\.homeSourceFresh/));
test('preview body labels updated time', () => assert.match(source, /updated: this\.i18n\.homeUpdated/));

// T-3895~T-3934: ready-card metadata, size controls and action-state contracts.
test('ready card uses section semantics', () => assert.match(source, /card\.className = "sw-home-store__card"/));
test('ready card keyboard binding is installed', () => assert.match(source, /bindStoreCardKeyboard\(card\)/));
test('ready card records module id', () => assert.match(source, /card\.dataset\.moduleId = moduleId/));
test('ready card search text includes provider', () => assert.match(source, /buildHomeStoreSearchText\(def, moduleId\).*externalInfo\?\.providerName/));
test('ready card records normalized category', () => assert.match(source, /card\.dataset\.category = def\.category === "siyuan" \? "builtin" : "plugin"/));
test('ready card records availability', () => assert.match(source, /card\.dataset\.availability = def\.availability \|\| "ready"/));
test('ready card maps direct widgets offline', () => assert.match(source, /externalInfo\?\.integration === "direct" \|\| def\.category === "siyuan" \? "offline"/));
test('ready card falls back to medium size', () => assert.match(source, /Array\.isArray\(def\.sizes\) && def\.sizes\.length > 0 \? def\.sizes : \["medium"\]/));
test('ready card records supported sizes', () => assert.match(source, /card\.dataset\.supportedSizes = supported\.join\(","\)/));
test('ready card records current size', () => assert.match(source, /card\.dataset\.currentSize = added\?\.size \|\| ""/));
test('ready card records added state', () => assert.match(source, /card\.dataset\.added = added \? "true" : "false"/));
test('ready card records status tone', () => assert.match(source, /card\.dataset\.statusTone = resolveHomeStoreStatusTone\(card\.dataset\)/));
test('ready card records integration tone', () => assert.match(source, /card\.dataset\.integrationTone = resolveHomeStoreIntegrationTone\(card\.dataset\)/));
test('ready card exposes accessible summary label', () => assert.match(source, /card\.setAttribute\("aria-label", resolveHomeStoreCardA11y/));
test('ready card icon has viewBox', () => assert.match(source, /icon\.setAttribute\("viewBox", "0 0 24 24"\)/));
test('ready card icon is hidden from assistive tech', () => assert.match(source, /icon\.setAttribute\("aria-hidden", "true"\)/));
test('ready card title uses fallback module id', () => assert.match(source, /title\.textContent = def\.title \|\| moduleId/));
test('ready card title has stable id', () => assert.match(source, /title\.id = `sw-home-store-title-\$\{moduleId\}`/));
test('ready card references title with aria-labelledby', () => assert.match(source, /card\.setAttribute\("aria-labelledby", title\.id\)/));
test('conditional badge exposes accessible label', () => assert.match(source, /badge\.setAttribute\("aria-label", badge\.textContent\)/));
test('conditional badge exposes tooltip', () => assert.match(source, /badge\.title = badge\.textContent/));
test('ready card support text has accessible label', () => assert.match(source, /support\.setAttribute\("aria-label", this\.i18n\.homeStoreSupportedSurfaces\)/));
test('ready card support text has tooltip', () => assert.match(source, /support\.title = support\.textContent/));
test('ready card status has stable id', () => assert.match(source, /status\.id = `sw-home-store-status-\$\{moduleId\}`/));
test('ready card status records added state', () => assert.match(source, /status\.dataset\.state = added \? "added" : "available"/));
test('ready card status is polite live', () => assert.match(source, /status\.setAttribute\("aria-live", "polite"\)/));
test('ready card status is atomic', () => assert.match(source, /status\.setAttribute\("aria-atomic", "true"\)/));
test('ready card describes status', () => assert.match(source, /card\.setAttribute\("aria-describedby", status\.id\)/));
test('source metadata uses note role', () => assert.match(source, /sourceMeta\.setAttribute\("role", "note"\)/));
test('source metadata uses guide hint label', () => assert.match(source, /sourceMeta\.setAttribute\("aria-label", this\.i18n\.homeStoreGuideHint\)/));
test('source chip records kind', () => assert.match(source, /chip\.dataset\.kind = kind/));
test('source chip exposes label', () => assert.match(source, /chip\.setAttribute\("aria-label", label\)/));
test('card preview records kind', () => assert.match(source, /preview\.dataset\.kind = kind/));
test('card preview is decorative', () => assert.match(source, /preview\.setAttribute\("aria-hidden", "true"\)/));
test('card preview records module id', () => assert.match(source, /preview\.dataset\.moduleId = moduleId/));
test('preview size rail is presentational', () => assert.match(source, /sizesRow\.setAttribute\("role", "presentation"\)/));
test('preview size boxes record size', () => assert.match(source, /box\.dataset\.size = sizeKey/));
test('preview size boxes expose title', () => assert.match(source, /box\.title = HOME_WIDGET_SIZE_LABELS/));
test('size group has stable module id', () => assert.match(source, /tiles\.dataset\.moduleId = moduleId/));
test('size group has selected size state', () => assert.match(source, /tiles\.dataset\.selectedSize = added\?\.size \|\| supported\[0\]/));
test('size label has stable id', () => assert.match(source, /sizeLabel\.id = `sw-home-store-size-label-\$\{moduleId\}`/));
test('size group references its label', () => assert.match(source, /tiles\.setAttribute\("aria-labelledby", sizeLabel\.id\)/));
test('size button has accessible hint', () => assert.match(source, /tile\.setAttribute\("aria-label", this\.i18n\.homeStoreSizeHint/));
test('size button controls action', () => assert.match(source, /tile\.setAttribute\("aria-controls", actionId\)/));
test('size button exposes set size', () => assert.match(source, /tile\.setAttribute\("aria-setsize", String\(supported\.length\)\)/));
test('size button exposes position', () => assert.match(source, /tile\.setAttribute\("aria-posinset", String\(sizeIndex \+ 1\)\)/));
test('size selection updates action label', () => assert.match(source, /addButton\.setAttribute\("aria-label", `\$\{added \? this\.i18n\.homeStoreApplySize : this\.i18n\.homeStoreAdd\}/));
test('add action describes size label', () => assert.match(source, /addButton\.setAttribute\("aria-describedby", sizeLabel\.id\)/));
test('preview action announces dialog', () => assert.match(source, /previewButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('preview action invokes live preview', () => assert.match(source, /previewButton\.onclick = \(\) => this\.openStoreWidgetPreview\(moduleId, def, device\)/));

// T-3935~T-3974: add/apply/configure/remove transition contracts.
test('size selection removes previous selected class', () => assert.match(source, /selectedTile\?\.classList\.remove\("is-selected"\)/));
test('size selection clears previous pressed state', () => assert.match(source, /selectedTile\?\.setAttribute\("aria-pressed", "false"\)/));
test('size selection clears previous data state', () => assert.match(source, /selectedTile\.dataset\.selected = "false"/));
test('size selection assigns new selected tile', () => assert.match(source, /selectedTile = tile/));
test('size selection applies selected class', () => assert.match(source, /tile\.classList\.add\("is-selected"\)/));
test('size selection sets pressed state', () => assert.match(source, /tile\.setAttribute\("aria-pressed", "true"\)/));
test('size selection sets data state', () => assert.match(source, /tile\.dataset\.selected = "true"/));
test('size selection records selected size on group', () => assert.match(source, /tiles\.dataset\.selectedSize = sizeKey/));
test('size selection records selected size on action', () => assert.match(source, /addButton\.dataset\.selectedSize = sizeKey/));
test('size selection updates action accessible label', () => assert.match(source, /addButton\.setAttribute\("aria-label", `\$\{added \? this\.i18n\.homeStoreApplySize : this\.i18n\.homeStoreAdd/));
test('size buttons support ArrowLeft', () => assert.match(source, /\["ArrowLeft", "ArrowRight", "Home", "End"\]/));
test('size buttons support ArrowRight', () => assert.match(source, /event\.key === "ArrowLeft" \? -1 : 1/));
test('size buttons support Home', () => assert.match(source, /event\.key === "Home" \? 0/));
test('size buttons support End', () => assert.match(source, /event\.key === "End" \? tilesForCard\.length - 1/));
test('size button navigation prevents default', () => assert.match(source, /event\.preventDefault\(\);\s*const nextIndex/));
test('size button navigation focuses next tile', () => assert.match(source, /tilesForCard\[nextIndex\]\?\.focus\(\)/));
test('add action reads selected tile size', () => assert.match(source, /const sizeKey = selectedTile!\.dataset\.size/));
test('add action resolves widget dimensions', () => assert.match(source, /const \{w, h\} = HOME_WIDGET_SIZES\[sizeKey as HomeWidgetSize\]!/));
test('add action reads fresh home state', () => assert.match(source, /const next = this\.getHomeState\(\)/));
test('add action scopes layout to device', () => assert.match(source, /const layoutList = \(next\.layouts\[device\] \|\| \[\]\)/));
test('apply action locates existing instance layout', () => assert.match(source, /layoutList\.find\(\(candidate\) => candidate\.instanceId === added\.instanceId\)/));
test('apply action updates size and dimensions', () => assert.match(source, /Object\.assign\(entry, \{size: sizeKey, w, h\}\)/));
test('add action creates instance with module id', () => assert.match(source, /createdInstance = \{instanceId: moduleId, moduleId, config: \{\}\}/));
test('add action enables new instance', () => assert.match(source, /\{\.\.\.createdInstance, enabled: true\}/));
test('add action starts layout at origin', () => assert.match(source, /layoutList\.push\(\{instanceId: moduleId, x: 0, y: 0/));
test('add action preserves collapsed default', () => assert.match(source, /collapsed: false, size: sizeKey/));
test('add action writes device layout', () => assert.match(source, /next\.layouts\[device\] = layoutList/));
test('add action persists home state', () => assert.match(source, /this\.saveHomeState\(next\)/));
test('conditional add announces prerequisite', () => assert.match(source, /if \(!added && def\.availability === "conditional"\)/));
test('conditional add uses localized hint', () => assert.match(source, /homeStoreConditionalHint/));
test('add action rerenders store', () => assert.match(source, /this\.saveHomeState\(next\);[\s\S]*?renderStore\(\)/));
test('add action notifies parent change', () => assert.match(source, /renderStore\(\);\s*onChanged\(\)/));
test('new configurable instance opens config form', () => assert.match(source, /if \(createdInstance && Array\.isArray\(def\.configSchema\)/));
test('new config form receives created instance', () => assert.match(source, /this\.openHomeConfigForm\(createdInstance, def\.configSchema/));
test('new config save rerenders store', () => assert.match(source, /this\.openHomeConfigForm\(createdInstance, def\.configSchema, \(\) => \{\s*renderStore\(\)/));
test('existing configurable card renders configure action', () => assert.match(source, /if \(addedInstance && Array\.isArray\(def\.configSchema\)/));
test('configure action uses added instance', () => assert.match(source, /this\.openHomeConfigForm\(addedInstance, def\.configSchema/));
test('configure action rerenders after save', () => assert.match(source, /openHomeConfigForm\(addedInstance, def\.configSchema, \(\) => \{\s*renderStore\(\)/));
test('remove action only renders for added cards', () => assert.match(source, /if \(added\) \{\s*const removeButton/));
test('remove action calls instance removal', () => assert.match(source, /this\.removeHomeInstance\(added\.instanceId\)/));
test('remove action rerenders store', () => assert.match(source, /this\.removeHomeInstance\(added\.instanceId\); renderStore\(\)/));
test('remove action notifies parent change', () => assert.match(source, /renderStore\(\); onChanged\(\); \};\s*tiles\.appendChild\(removeButton\)/));
test('configure action announces dialog', () => assert.match(source, /configButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('remove action label includes module title', () => assert.match(source, /removeButton\.setAttribute\("aria-label", `\$\{this\.i18n\.homeStoreRemove\} · \$\{def\.title \|\| moduleId\}`\)/));

// T-3815~T-3854: dialog content, field labels and async configuration contracts.
test('guide hint uses localized content', () => assert.match(source, /hint\.textContent = this\.i18n\.homeStoreGuideHint/));
test('guide hint has a dedicated class', () => assert.match(source, /hint\.className = "sw-home-store-guide__hint"/));
test('guide link has button styling', () => assert.match(source, /link\.className = "b3-button b3-button--outline sw-home-store-guide__link"/));
test('guide link uses localized label', () => assert.match(source, /link\.textContent = this\.i18n\.homeStoreGuide/));
test('guide note has a dedicated class', () => assert.match(source, /note\.className = "sw-home-store-guide__note"/));
test('guide note is appended after link', () => assert.match(source, /root\.appendChild\(link\);[\s\S]*?root\.appendChild\(note\)/));
test('preview id sanitizes module identifiers', () => assert.match(source, /moduleId\.replace\(\//));
test('preview metadata records module id', () => assert.match(source, /meta\.dataset\.moduleId = moduleId/));
test('preview metadata uses guide hint label', () => assert.match(source, /meta\.setAttribute\("aria-label", this\.i18n\.homeStoreGuideHint\)/));
test('preview metadata chip title mirrors label', () => assert.match(source, /chip\.title = label/));
test('preview metadata adds source chip', () => assert.match(source, /addMeta\(this\.i18n\.homeStoreSource\.replace\("\{source\}"/));
test('preview metadata adds integration chip', () => assert.match(source, /addMeta\(integration, sourceInfo\?\.integration === "http"/));
test('preview metadata adds privacy chip', () => assert.match(source, /addMeta\(privacy, "privacy"\)/));
test('preview metadata adds surface chip', () => assert.match(source, /addMeta\(this\.i18n\.homeStorePreviewSurface/));
test('preview metadata adds size chip', () => assert.match(source, /addMeta\(this\.i18n\.homeStorePreviewSize/));
test('preview read preserves caller read options', () => assert.match(source, /\{\.\.\.readOptions, size: sizeKey\}/));
test('preview task toggle keeps item done metadata', () => assert.match(source, /onToggleItem: \(item: \{ label\?: string; value\?: string; done\?: boolean \}\)/));
test('preview task toggle is asynchronous', () => assert.match(source, /onToggleItem:[\s\S]*?void \(async \(\) =>/));
test('preview task toggle calls host adapter', () => assert.match(source, /const ok = await this\.toggleHomeTaskBlock\(item\)/));
test('preview task toggle refreshes after attempt', () => assert.match(source, /await controller\?\.refresh\(\);/));
test('preview dispose guards repeated calls', () => assert.match(source, /if \(disposed\) return;/));
test('preview destroy wraps original dialog destroy', () => assert.match(source, /const originalDestroy = dialog\.destroy\.bind\(dialog\)/));
test('preview destroy invokes original dialog destroy', () => assert.match(source, /disposePreview\(\);\s*originalDestroy\(\)/));
test('preview busy marker only clears while mounted', () => assert.match(source, /if \(!disposed\) \{\s*container\.setAttribute\("aria-busy", "false"\)/));
test('preview watcher interval is assigned', () => assert.match(source, /disposeTimer = window\.setInterval/));
test('preview watcher interval is cleared during dispose', () => assert.match(source, /window\.clearInterval\(disposeTimer\)/));
test('config field rows use dedicated class', () => assert.match(source, /row\.className = "sw-home-config__field"/));
test('config labels use dedicated class', () => assert.match(source, /label\.className = "sw-home-config__label"/));
test('config control ids sanitize unsafe characters', () => assert.match(source, /const controlId = .*\.replace\(\//));
test('config controls are registered after creation', () => assert.match(source, /controls\.set\(field\.key, (select|input)\)/));
test('config notebook fill clears loading options', () => assert.match(source, /select\.innerHTML = ""/));
test('config notebook fill appends available notebooks', () => assert.match(source, /options\.forEach\(\(nb\) =>/));
test('config notebook fill restores current value', () => assert.match(source, /select\.value = resetKeys\.has\(field\.key\) \? "" : current/));
test('config notebook fill updates draft value', () => assert.match(source, /draft\[field\.key\] = select\.value/));
test('config notebook reset key is consumed', () => assert.match(source, /resetKeys\.delete\(field\.key\)/));
test('config notebook loading is asynchronous', () => assert.match(source, /void this\.loadNotebooks\(\)\.then\(\(notebooks\) =>/));
test('config document datalist has stable id', () => assert.match(source, /suggestions\.id = `\$\{controlId\}-options`/));
test('config document datalist appends options', () => assert.match(source, /suggestions\.appendChild\(option\)/));
test('config document input listener updates draft', () => assert.match(source, /input\.addEventListener\("input", \(\) => \{ draft\[field\.key\]/));
test('config number listener reads numeric input', () => assert.match(source, /const parsed = Number\(input\.value\)/));
test('config number listener writes clamped value', () => assert.match(source, /input\.value = String\(draft\[field\.key\]\)/));
test('config non-number text listener truncates value', () => assert.match(source, /draft\[field\.key\] = input\.value\.slice\(0, 128\)/));
test('config controls append inside field row', () => assert.match(source, /root\.appendChild\(row\)/));
test('config actions use dedicated class', () => assert.match(source, /actions\.className = "sw-home-config__actions"/));
test('config actions append reset cancel save order', () => assert.match(source, /actions\.append\(reset, cancel, save\)/));
test('config reset updates existing controls', () => assert.match(source, /if \(!control\) return;\s*control\.value = String\(value\)/));
test('config save only applies when instance exists', () => assert.match(source, /if \(instance\) \{\s*instance\.config/));
test('config save invokes callback after destroy', () => assert.match(source, /dialog\.destroy\(\);\s*onSaved\(\)/));

// T-3975~T-4014: store grouping, pending and unavailable catalog contracts.
test('store declares built-in group metadata', () => assert.match(source, /const BUILTIN_GROUPS: Array<\{label: string; moduleIds: string\[\]\}> = \[/));
test('store groups journal modules explicitly', () => assert.match(source, /homeStoreGroupJournal, moduleIds: \["today-journal", "journal-monthly"/));
test('store groups task modules explicitly', () => assert.match(source, /homeStoreGroupTasks, moduleIds: \["today-tasks"\]/));
test('store groups document modules explicitly', () => assert.match(source, /homeStoreGroupDocuments, moduleIds: \["recent-documents", "favorites"/));
test('store groups insight modules explicitly', () => assert.match(source, /homeStoreGroupInsights, moduleIds: \["note-stats", "year-progress"/));
test('store groups life modules explicitly', () => assert.match(source, /homeStoreGroupLife, moduleIds: \["external-local-time", "external-weather-open-meteo"/));
test('store groups news modules explicitly', () => assert.match(source, /homeStoreGroupNews, moduleIds: \["external-hot-news-dailyhot", "external-news-newsnow"\]/));
test('store groups focus modules explicitly', () => assert.match(source, /homeStoreGroupFocus, moduleIds: \["external-activitywatch-time"\]/));
test('store groups learning modules explicitly', () => assert.match(source, /homeStoreGroupLearning, moduleIds: \["flashcard-due", "random-review"\]/));
test('store groups capture modules explicitly', () => assert.match(source, /homeStoreGroupCapture, moduleIds: \["quick-capture", "clipped-unread"\]/));
test('store groups system modules explicitly', () => assert.match(source, /homeStoreGroupSystem, moduleIds: \["tags", "bookmarks", "plugin-commands"\]/));
test('store resolves built-in group by module id', () => assert.match(source, /const hit = BUILTIN_GROUPS\.find\(\(group\) => group\.moduleIds\.includes\(moduleId\)\)/));
test('store has an explicit other built-in group fallback', () => assert.match(source, /return hit \? hit\.label : this\.i18n\.homeStoreGroupOther/));
test('store resolves plugin group by author', () => assert.match(source, /return def\.author\s*\?\s*this\.i18n\.homeStoreGroupPluginAuthor\.replace\("\{author\}", def\.author\)/));
test('store has a generic plugin group fallback', () => assert.match(source, /: this\.i18n\.homeStoreGroupPlugin/));
test('store builds ready groups from ready cards', () => assert.match(source, /const readyGroups = new Map<string, HTMLElement\[\]>\(\);[\s\S]*?ready\.forEach/));
test('store creates missing ready group buckets', () => assert.match(source, /if \(!readyGroups\.has\(label\)\) readyGroups\.set\(label, \[\]\)/));
test('store appends cards into matching group', () => assert.match(source, /readyGroups\.get\(label\)!\.push\(buildReadyCard\(moduleId, def\)\)/));
test('store orders built-in groups before plugin groups', () => assert.match(source, /\.\.\.BUILTIN_GROUPS\.map\(\(group\) => group\.label\)\.filter\(\(label\) => readyGroups\.has\(label\)\)/));
test('store retains unknown groups after built-in groups', () => assert.match(source, /\.\.\.\[\.\.\.readyGroups\.keys\(\)\]\.filter\(\(label\) => !BUILTIN_GROUPS\.some/));
test('store renders one heading per group', () => assert.match(source, /orderedGroups\.forEach\(\(label\) => \{\s*const cards = readyGroups\.get\(label\)!/));
test('store group heading uses level three', () => assert.match(source, /groupHeading\.setAttribute\("aria-level", "3"\)/));
test('store group heading has stable positional id', () => assert.match(source, /groupHeading\.id = `sw-home-store-group-heading-\$\{orderedGroups\.indexOf\(label\)\}`/));
test('store group heading records group key', () => assert.match(source, /groupHeading\.dataset\.group = label/));
test('store group heading exposes item count', () => assert.match(source, /groupHeading\.setAttribute\("aria-label", `\$\{label\} · \$\{cards\.length\}`\)/));
test('store group label exposes item count', () => assert.match(source, /groupLabel\.textContent = `\$\{label\} · \$\{cards\.length\}`/));
test('store group toggle tracks collapsed state', () => assert.match(source, /groupHeading\.dataset\.collapsed = String\(collapsedGroups\.has\(label\)\)/));
test('store group toggle tracks expanded state', () => assert.match(source, /groupToggle\.setAttribute\("aria-expanded", String\(!collapsedGroups\.has\(label\)\)\)/));
test('store group toggle has stable group key', () => assert.match(source, /groupToggle\.dataset\.group = label/));
test('store group toggle controls its grid', () => assert.match(source, /groupToggle\.setAttribute\("aria-controls", groupId\)/));
test('store group grid has stable id', () => assert.match(source, /const groupId = `sw-home-store-group-\$\{orderedGroups\.indexOf\(label\)\}`/));
test('store group grid uses group role', () => assert.match(source, /groupGrid\.setAttribute\("role", "group"\)/));
test('store group grid references heading', () => assert.match(source, /groupGrid\.setAttribute\("aria-labelledby", groupHeading\.id\)/));
test('store pending state comes from catalog resolver', () => assert.match(source, /const pending = resolveWidgetCatalogState\(\[\.\.\.activeIds\], \[\.\.\.instanceByModule\.keys\(\)\]\)/));
test('store pending state excludes ready entries', () => assert.match(source, /\.filter\(\(item: any\) => item\.status !== "ready"\)/));
test('store records pending count on root', () => assert.match(source, /root\.dataset\.pendingCount = String\(pending\.length\)/));
test('store pending section has stable id', () => assert.match(source, /pendingHeading\.id = "sw-home-store-section-pending"/));
test('store pending section records section key', () => assert.match(source, /pendingHeading\.dataset\.section = "pending"/));
test('store pending grid has stable id', () => assert.match(source, /pendingGrid\.id = "sw-home-store-pending-grid"/));
test('store pending grid references section heading', () => assert.match(source, /pendingGrid\.setAttribute\("aria-labelledby", pendingHeading\.id\)/));
test('store pending card records provider search text', () => assert.match(source, /card\.dataset\.search = `\$\{entry\.title\} \$\{entry\.description\} \$\{entry\.providerName\}`\.toLowerCase\(\)/));
test('store pending card records requires-provider state', () => assert.match(source, /card\.dataset\.status = unavailable \? "unavailable" : "requires-provider"/));
test('store pending card exposes provider name', () => assert.match(source, /\.replace\("\{plugin\}", entry\.providerName\)/));
test('store unavailable card gets warning tone', () => assert.match(source, /card\.dataset\.statusTone = unavailable \? "warning" : "info"/));
test('store unavailable card gets dedicated class', () => assert.match(source, /\+ \(unavailable \? " sw-home-store__card--unavailable" : ""\)/));
test('store unavailable card renders removal action', () => assert.match(source, /removeButton\.dataset\.action = "remove-unavailable"/));
test('store unavailable removal resolves instance by module', () => assert.match(source, /const instance = instanceStateByModule\.get\(entry\.moduleId\)/));
test('store unavailable removal rerenders and notifies', () => assert.match(source, /this\.removeHomeInstance\(instance\.instanceId\);\s*renderStore\(\);\s*onChanged\(\)/));
test('store empty state resets both counters', () => assert.match(source, /if \(ready\.length === 0 && pending\.length === 0\) \{\s*root\.dataset\.readyCount = "0";\s*root\.dataset\.pendingCount = "0"/));

// T-4024~T-4063: filtered group visibility, count synchronization and empty-state contracts.
test('store ready section has a stable id', () => assert.match(source, /readyHeading\.id = "sw-home-store-section-ready"/));
test('store ready section records section key', () => assert.match(source, /readyHeading\.dataset\.section = "ready"/));
test('store ready section uses level two heading', () => assert.match(source, /readyHeading\.setAttribute\("aria-level", "2"\)/));
test('store ready section uses heading role', () => assert.match(source, /readyHeading\.setAttribute\("role", "heading"\)/));
test('store ready section uses localized label', () => assert.match(source, /readyHeading\.textContent = this\.i18n\.homeStoreReady/));
test('store render initializes query dataset', () => assert.match(source, /root\.dataset\.query = normalizeHomeStoreQuery\(searchInput\.value\)/));
test('store filter records active filter dataset', () => assert.match(source, /root\.dataset\.activeFilter = filter\.tab/));
test('store filter records sort dataset', () => assert.match(source, /root\.dataset\.sort = storeSort/));
test('store card filter uses normalized query and model', () => assert.match(source, /const visible = matchesHomeStoreTokens\(card\.dataset, query, filter\)/));
test('store card filter toggles hidden class', () => assert.match(source, /card\.classList\.toggle\("fn__none", !visible\)/));
test('store card filter exposes aria hidden', () => assert.match(source, /card\.setAttribute\("aria-hidden", String\(!visible\)\)/));
test('store card filter records match state', () => assert.match(source, /card\.dataset\.filterMatch = String\(visible\)/));
test('store group filter derives visibility from child cards', () => assert.match(source, /Array\.from\(grid\.children\)\.some\(\(card\) => !card\.classList\.contains\("fn__none"\)\)/));
test('store group filter hides empty group heading', () => assert.match(source, /heading\.classList\.toggle\("fn__none", !visible\)/));
test('store group filter hides empty group grid', () => assert.match(source, /grid\.classList\.toggle\("fn__none", !visible\)/));
test('store group filter preserves collapsed state', () => assert.match(source, /grid\.classList\.toggle\("fn__none", heading\.dataset\.collapsed === "true"\)/));
test('store group filter exposes heading aria hidden', () => assert.match(source, /heading\.setAttribute\("aria-hidden", String\(!visible\)\)/));
test('store group filter exposes grid aria hidden', () => assert.match(source, /grid\.setAttribute\("aria-hidden", String\(!visible \|\| heading\.dataset\.collapsed === "true"\)\)/));
test('store section filter handles ready groups', () => assert.match(source, /heading\.dataset\.section === "ready"\s*\? Array\.from\(root\.querySelectorAll<HTMLElement>\("\.sw-home-store__group"\)\)/));
test('store section filter handles pending cards', () => assert.match(source, /: Array\.from\(section\.children\)\.some\(\(card\) => !card\.classList\.contains\("fn__none"\)\)/));
test('store section filter hides empty section heading', () => assert.match(source, /heading\.classList\.toggle\("fn__none", !visible\);\s*heading\.setAttribute\("aria-hidden"/));
test('store section filter hides non-ready section grid', () => assert.match(source, /if \(heading\.dataset\.section !== "ready"\) section\.classList\.toggle\("fn__none", !visible\)/));
test('store visible card summary scans all cards', () => assert.match(source, /Array\.from\(root\.querySelectorAll<HTMLElement>\("\.sw-home-store__card"\)\)\s*\.some\(\(card\) => !card\.classList\.contains\("fn__none"\)\)/));
test('store filtered card focus detects hidden card', () => assert.match(source, /const focusedCard = focusedBeforeFilter\?\.closest<HTMLElement>\("\.sw-home-store__card"\)/));
test('store filtered focus skips hidden cards', () => assert.match(source, /if \(focusedCard && focusedCard\.classList\.contains\("fn__none"\)\)/));
test('store filtered focus chooses visible card', () => assert.match(source, /root\.querySelector<HTMLElement>\("\.sw-home-store__card:not\(\.fn__none\)"\)/));
test('store filtered focus falls back to search', () => assert.match(source, /else searchInput\.focus\(\{preventScroll: true\}\)/));
test('store empty filter toggles visibility from card presence', () => assert.match(source, /filterEmptyState\?\.classList\.toggle\("fn__none", hasVisibleCards\)/));
test('store empty filter announces hidden state', () => assert.match(source, /filterEmptyState\?\.setAttribute\("aria-hidden", String\(hasVisibleCards\)\)/));
test('store result summary is recomputed from card datasets', () => assert.match(source, /const summary = summarizeHomeStoreCards\(cards\.map\(\(card\) => card\.dataset\), query, filter\)/));
test('store result summary localizes visible count', () => assert.match(source, /homeStoreResultSummary[\s\S]*?replace\("\{visible\}", String\(summary\.visible\)\)/));
test('store result summary localizes total count', () => assert.match(source, /replace\("\{total\}", String\(summary\.total\)\)/));
test('store result summary localizes added count', () => assert.match(source, /replace\("\{added\}", String\(summary\.added\)\)/));
test('store result summary records visible dataset', () => assert.match(source, /resultSummary\.dataset\.visible = String\(summary\.visible\)/));
test('store result summary records total dataset', () => assert.match(source, /resultSummary\.dataset\.total = String\(summary\.total\)/));
test('store result summary records added dataset', () => assert.match(source, /resultSummary\.dataset\.added = String\(summary\.added\)/));
test('store result summary records empty state', () => assert.match(source, /resultSummary\.dataset\.state = summary\.visible > 0 \? "results" : "empty"/));
test('store root records visible count', () => assert.match(source, /root\.dataset\.visibleCount = String\(summary\.visible\)/));
test('store root records total count', () => assert.match(source, /root\.dataset\.totalCount = String\(summary\.total\)/));
test('store root records added count', () => assert.match(source, /root\.dataset\.addedCount = String\(summary\.added\)/));
test('store tab counts derive from card datasets', () => assert.match(source, /const tabCounts = buildHomeStoreTabCounts\(Array\.from\(root\.querySelectorAll<HTMLElement>\("\.sw-home-store__card"\)\)\.map\(\(card\) => card\.dataset\)\)/));
test('store tab count label includes count', () => assert.match(source, /button\.textContent = `\$\{button\.dataset\.tabLabel \|\| ""\} · \$\{count\}`/));
test('store tab count dataset stays synchronized', () => assert.match(source, /button\.dataset\.count = String\(count\)/));
test('store tab count aria label stays synchronized', () => assert.match(source, /button\.setAttribute\("aria-label", `\$\{button\.dataset\.tabLabel \|\| ""\} · \$\{count\}`\)/));
test('store tab count describes live summary', () => assert.match(source, /button\.setAttribute\("aria-describedby", resultSummary\?\.id \|\| "sw-home-store-result-summary"\)/));
test('store clear filters resets query', () => assert.match(source, /storeQuery = "";\s*storeTab = "all";\s*root\.dataset\.query = ""/));
test('store clear filters resets active tab dataset', () => assert.match(source, /root\.dataset\.activeTab = "all"/));
test('store clear filters clears search input', () => assert.match(source, /searchInput\.value = "";\s*clearSearchButton\.hidden = true/));
test('store clear filters restores active tab aria state', () => assert.match(source, /button\.setAttribute\("aria-selected", String\(active\)\);\s*button\.setAttribute\("aria-current", active \? "page" : "false"\)/));
test('store clear filters reapplies model before focus', () => assert.match(source, /applyFilter\(\);\s*searchInput\.focus\(\)/));
