const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const storeUiSource = fs.readFileSync(path.join(root, 'src', 'home-store-ui.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');
const zh = JSON.parse(fs.readFileSync(path.join(root, 'src', 'i18n', 'zh-CN.json'), 'utf8'));
const en = JSON.parse(fs.readFileSync(path.join(root, 'src', 'i18n', 'en.json'), 'utf8'));

test('clear search button is created', () => assert.match(storeUiSource, /const clearSearchButton = document\.createElement\("button"\)/));
test('clear search button uses button type', () => assert.match(storeUiSource, /clearSearchButton\.type = "button"/));
test('clear search button has stable class', () => assert.match(storeUiSource, /sw-home-store__clear-search/));
test('clear search button has localized aria label', () => assert.match(storeUiSource, /homeStoreClearSearch/));
test('clear search button starts hidden when empty', () => assert.match(storeUiSource, /clearSearchButton\.hidden = !storeQuery/));
test('clear search button clears store query', () => assert.match(storeUiSource,/storeQuery = ""/));
test('clear search button clears input', () => assert.match(storeUiSource, /searchInput\.value = ""/));
test('clear search button reapplies filter', () => assert.match(storeUiSource, /clearSearchButton[\s\S]*?applyFilter\(\)/));
test('clear search button restores focus', () => assert.match(storeUiSource, /clearSearchButton[\s\S]*?searchInput\.focus\(\)/));
test('input updates clear button visibility', () => assert.match(storeUiSource, /clearSearchButton\.hidden = !normalizeHomeStoreQuery\(storeQuery\)/));
test('search input handles keydown', () => assert.match(storeUiSource,/searchInput\.addEventListener\("keydown"/));
test('Escape key is recognized', () => assert.match(source, /event\.key !== "Escape"/));
test('Escape prevents browser default', () => assert.match(storeUiSource, /event\.preventDefault\(\)/));
test('Escape triggers clear action', () => assert.match(storeUiSource, /clearSearchButton\.click\(\)/));
test('empty search Escape is ignored', () => assert.match(storeUiSource, /!searchInput\.value/));
test('clear search button is appended to search bar', () => assert.match(storeUiSource,/searchBar\.appendChild\(clearSearchButton\)/));
test('clear search button has circular width', () => assert.match(css, /\.sw-home-store__clear-search[\s\S]*?width: 32px/));
test('clear search button has compact height', () => assert.match(css, /\.sw-home-store__clear-search[\s\S]*?height: 32px/));
test('clear search button has compact minimum height', () => assert.match(css, /\.sw-home-store__clear-search[\s\S]*?min-height: 32px/));
test('clear search button has circular radius', () => assert.match(css, /\.sw-home-store__clear-search[\s\S]*?border-radius: 50%/));
test('clear search button has readable glyph size', () => assert.match(css, /\.sw-home-store__clear-search[\s\S]*?font-size: 20px/));
test('mobile clear button overlaps input edge', () => assert.match(css, /\.sw-home-store__clear-search \{ margin-left: -40px/));
test('mobile clear button stays above input', () => assert.match(css, /z-index: 1/));
test('Chinese clear search label exists', () => assert.equal(zh.homeStoreClearSearch, '清空搜索'));
test('English clear search label exists', () => assert.equal(en.homeStoreClearSearch, 'Clear search'));
test('clear search label is non-empty', () => assert.ok(zh.homeStoreClearSearch.length > 0 && en.homeStoreClearSearch.length > 0));
test('search state remains bounded by normalizer', () => assert.match(storeUiSource,/normalizeHomeStoreQuery\(storeQuery\)/));
test('clear action preserves sort controls', () => assert.match(storeUiSource, /sortSelect/));
test('clear action preserves tab state', () => assert.match(storeUiSource, /storeTab/));
test('clear action does not remove card DOM contract', () => assert.match(storeUiSource, /filterEmptyState/));
test('clear button is independent of filter reset', () => assert.match(storeUiSource,/homeStoreClearFilters/));
