const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('filter records the active tab', () => assert.match(source, /root\.dataset\.activeFilter = filter\.tab/));
test('filter records the current sort', () => assert.match(source, /root\.dataset\.sort = storeSort/));
test('filter remembers the focused element', () => assert.match(source, /const focusedBeforeFilter = document\.activeElement instanceof HTMLElement/));
test('filter records match state on cards', () => assert.match(source, /card\.dataset\.filterMatch = String\(visible\)/));
test('filter detects a focused card', () => assert.match(source, /const focusedCard = focusedBeforeFilter\?\.closest<HTMLElement>\("\.sw-home-store__card"\)/));
test('filter restores focus to the next visible card', () => assert.match(source, /const nextCard = root\.querySelector<HTMLElement>\("\.sw-home-store__card:not\(\.fn__none\)"\)/));
test('filter focuses search when no card remains', () => assert.match(source, /else searchInput\.focus\(\{preventScroll: true\}\)/));
test('tab activation records aria current', () => assert.match(source, /candidate\.setAttribute\("aria-current", active \? "page" : "false"\)/));
test('tabs initialize aria current', () => assert.match(source, /btn\.setAttribute\("aria-current", tab\.key === storeTab \? "page" : "false"\)/));
test('clear filters resets aria current', () => assert.match(source, /button\.setAttribute\("aria-current", active \? "page" : "false"\)/));
test('size tiles support horizontal arrows', () => assert.match(source, /\["ArrowLeft", "ArrowRight", "Home", "End"\]/));
test('size tiles compute a focused index', () => assert.match(source, /const tilesForCard = Array\.from\(tiles\.querySelectorAll/));
test('size tiles support Home', () => assert.match(source, /event\.key === "Home" \? 0/));
test('size tiles support End', () => assert.match(source, /event\.key === "End" \? tilesForCard\.length - 1/));
test('size tiles wrap forward', () => assert.match(source, /event\.key === "ArrowLeft" \? -1 : 1\) \+ tilesForCard\.length/));
test('size tiles focus the next tile', () => assert.match(source, /tilesForCard\[nextIndex\]\?\.focus\(\)/));
test('store root records active filter in source', () => assert.match(source, /dataset\.activeFilter/));
test('store root records sort in source', () => assert.match(source, /dataset\.sort = storeSort/));
test('store cards keep filter match metadata', () => assert.match(source, /card\.dataset\.filterMatch = String\(visible\)/));
test('store cards preserve focus preventScroll', () => assert.match(source, /nextCard\.focus\(\{preventScroll: true\}\)/));
test('store search focus preserves preventScroll', () => assert.match(source, /searchInput\.focus\(\{preventScroll: true\}\)/));
test('store tabs expose page current state', () => assert.match(source, /aria-current/));
test('store size controls keep touch semantics', () => assert.match(css, /\.sw-home-store__size[\s\S]*?touch-action: manipulation/));
test('store add action keeps touch semantics', () => assert.match(css, /\.sw-home-store__add[\s\S]*?touch-action: manipulation/));
test('store configure action keeps touch semantics', () => assert.match(css, /\.sw-home-store__configure[\s\S]*?touch-action: manipulation/));
test('store remove action keeps touch semantics', () => assert.match(css, /\.sw-home-store__remove[\s\S]*?touch-action: manipulation/));
test('store group toggle keeps touch semantics', () => assert.match(css, /\.sw-home-store__group-toggle,[\s\S]*?touch-action: manipulation/));
test('store search clear keeps touch semantics', () => assert.match(css, /\.sw-home-store__clear-search,[\s\S]*?touch-action: manipulation/));
test('store filter clear keeps touch semantics', () => assert.match(css, /\.sw-home-store__clear-filters,[\s\S]*?touch-action: manipulation/));
test('store guide keeps touch semantics', () => assert.match(css, /\.sw-home-store__guide,[\s\S]*?touch-action: manipulation/));
test('store unavailable removal keeps touch semantics', () => assert.match(css, /\.sw-home-store__remove-unavailable[\s\S]*?touch-action: manipulation/));
test('store tabs preserve numeric count typography', () => assert.match(css, /&\[aria-current="page"\][\s\S]*?font-variant-numeric: tabular-nums/));
test('store hidden card CSS stays scoped', () => assert.match(css, /\.sw-home-store__card\[aria-hidden="true"\]/));
test('store card hidden state remains content-visibility bounded', () => assert.match(css, /content-visibility: hidden/));
test('store focus navigation stays in store scope', () => assert.match(source, /\.sw-home-store__card:not\(\.fn__none\)/));
test('store tile navigation prevents native scrolling', () => assert.match(source, /event\.preventDefault\(\);\s*const nextIndex/));
test('store tile navigation ignores unrelated keys', () => assert.match(source, /if \(index < 0 \|\| !\["ArrowLeft"/));
test('store filter focus handling only moves from cards', () => assert.match(source, /if \(focusedCard && focusedCard\.classList\.contains\("fn__none"\)\)/));
test('store filter keeps search focus when visible', () => assert.match(source, /focusedBeforeFilter\?\.closest<HTMLElement>/));
test('store keyboard controls use button focus', () => assert.match(source, /tilesForCard\[nextIndex\]\?\.focus/));
test('store touch controls avoid gesture delay', () => assert.match(css, /touch-action: manipulation/));
