const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
// R3 重构（D-377）：配置表单方法体在 home-config-form.ts。
const configFormSource = fs.readFileSync(path.join(root, 'src', 'home-config-form.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('preview captures its opener', () => assert.match(source, /const opener = document\.activeElement instanceof HTMLElement/));
test('preview exposes module id', () => assert.match(source, /container\.dataset\.moduleId = moduleId/));
test('preview exposes device', () => assert.match(source, /container\.dataset\.device = device/));
test('preview exposes selected size', () => assert.match(source, /container\.dataset\.size = sizeKey/));
test('preview container is a region', () => assert.match(source, /container\.setAttribute\("role", "region"\)/));
test('preview container has an accessible label', () => assert.match(source, /container\.setAttribute\("aria-label", `\$\{this\.i18n\.homeStorePreview\}/));
test('preview starts busy', () => assert.match(source, /container\.setAttribute\("aria-busy", "true"\)/));
test('preview body keeps its scoped class', () => assert.match(source, /body\.className = "sw-store-preview__body"/));
test('preview body is a status region', () => assert.match(source, /body\.setAttribute\("role", "status"\)/));
test('preview body is live', () => assert.match(source, /body\.setAttribute\("aria-live", "polite"\)/));
test('preview creates a home controller', () => assert.match(source, /controller = createHomeModuleController\(\{/));
test('preview read stays on the selected module', () => assert.match(source, /this\.homeRuntime\.read\(moduleId, device/));
test('preview read carries the selected size', () => assert.match(source, /\{\.\.\.readOptions, size: sizeKey\}/));
test('preview forces a fresh read', () => assert.match(source, /controller\.refresh\(\{\}, \{force: true\}\)/));
test('preview tracks disposed state', () => assert.match(source, /let disposed = false/));
test('preview exposes one cleanup helper', () => assert.match(source, /const disposePreview = \(\) =>/));
test('preview cleanup disposes controller', () => assert.match(source, /controller\?\.dispose\(\)/));
test('preview cleanup clears polling', () => assert.match(source, /window\.clearInterval\(disposeTimer\)/));
test('preview cleanup restores opener focus', () => assert.match(source, /if \(opener\?\.isConnected\) opener\.focus\(\)/));
test('preview wraps dialog destroy', () => assert.match(source, /const originalDestroy = dialog\.destroy\.bind\(dialog\)/));
test('preview destroy invokes cleanup', () => assert.match(source, /dialog\.destroy = \(\) => \{\s*disposePreview\(\);/));
test('preview destroy invokes original destroy', () => assert.match(source, /disposePreview\(\);\s*originalDestroy\(\);/));
test('preview mounts before refreshing', () => assert.match(source, /controller\.mount\(\);\s*const markPreviewReady =/));
test('preview clears busy state after refresh', () => assert.match(source, /container\.setAttribute\("aria-busy", "false"\)/));
test('preview refresh cleanup handles success and failure', () => assert.match(source, /controller\.refresh\(\{\}, \{force: true\}\)\.then\(markPreviewReady, markPreviewReady\)/));
test('preview polls dialog connectivity', () => assert.match(source, /disposeTimer = window\.setInterval/));
test('preview checks dialog connection', () => assert.match(source, /if \(!dialog\.element\.isConnected\)/));
test('preview polling uses shared cleanup', () => assert.match(source, /if \(!dialog\.element\.isConnected\) \{\s*disposePreview\(\);/));
test('preview has a bounded mobile width', () => assert.match(source, /width: this\.isMobile \? "min\(420px, 92vw\)"/));
test('preview has a bounded mobile height', () => assert.match(source, /height: this\.isMobile \? "min\(560px, 80vh\)"/));
test('preview styles remain scoped', () => assert.match(css, /\.sw-store-preview/));

// T-4971~T-5016: component-store DOM action, accessibility and focus lifecycle contracts.
test('store search exposes search role', () => assert.match(source, /searchBar\.setAttribute\("role", "search"\)/));
test('store search exposes searchbox role', () => assert.match(source, /searchInput\.setAttribute\("role", "searchbox"\)/));
test('store search uses enter key hint', () => assert.match(source, /searchInput\.setAttribute\("enterkeyhint", "search"\)/));
test('clear search has explicit action metadata', () => assert.match(source, /clearSearchButton\.dataset\.action = "clear-search"/));
test('clear search restores input focus', () => assert.match(source, /searchInput\.focus\(\)/));
test('store sort exposes action metadata', () => assert.match(source, /sortSelect\.dataset\.action = "sort"/));
test('store sort controls result summary', () => assert.match(source, /sortSelect\.setAttribute\("aria-controls", "sw-home-store-result-summary"\)/));
test('guide button exposes dialog semantics', () => assert.match(source, /guideButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('guide button invokes guide opener', () => assert.match(source, /guideButton\.addEventListener\("click", \(\) => this\.openHomeWidgetGuide\(\)\)/));
test('store tabs expose tablist role', () => assert.match(source, /tabBar\.setAttribute\("role", "tablist"\)/));
test('store tab buttons expose tab role', () => assert.match(source, /btn\.setAttribute\("role", "tab"\)/));
test('store tabs expose roving tabindex', () => assert.match(source, /btn\.setAttribute\("tabindex", tab\.key === storeTab \? "0" : "-1"\)/));
test('store tab activation updates selected state', () => assert.match(source, /candidate\.setAttribute\("aria-selected", String\(active\)\)/));
test('store tab activation updates current page state', () => assert.match(source, /candidate\.setAttribute\("aria-current", active \? "page" : "false"\)/));
test('store tab count is persisted in dataset', () => assert.match(source, /button\.dataset\.count = String\(count\)/));
test('store result summary is a status region', () => assert.match(source, /resultSummary\.setAttribute\("role", "status"\)/));
test('store result summary is live', () => assert.match(source, /resultSummary\.setAttribute\("aria-live", "polite"\)/));
test('store result summary is atomic', () => assert.match(source, /resultSummary\.setAttribute\("aria-atomic", "true"\)/));
test('ready section is level two heading', () => assert.match(source, /readyHeading\.setAttribute\("aria-level", "2"\)/));
test('pending section is level two heading', () => assert.match(source, /pendingHeading\.setAttribute\("aria-level", "2"\)/));
test('store cards carry module ids', () => assert.match(source, /card\.dataset\.moduleId = moduleId/));
test('store cards expose labels', () => assert.match(source, /card\.setAttribute\("aria-label",/));
test('size controls are buttons', () => assert.match(source, /tile\.type = "button"/));
test('size controls expose pressed state', () => assert.match(source, /tile\.setAttribute\("aria-pressed", String\(tile === selectedTile\)\)/));
test('size controls point at action button', () => assert.match(source, /tile\.setAttribute\("aria-controls", actionId\)/));
test('add button is explicit action', () => assert.match(source, /addButton\.dataset\.action = added \? "apply-size" : "add"/));
test('add button carries module id', () => assert.match(source, /addButton\.dataset\.moduleId = moduleId/));
test('add button tracks selected size', () => assert.match(source, /addButton\.dataset\.selectedSize = selectedTile\?\.dataset\.size \|\| supported\[0\]/));
test('add button describes size label', () => assert.match(source, /addButton\.setAttribute\("aria-describedby", sizeLabel\.id\)/));
test('add action persists home state', () => assert.match(source, /this\.saveHomeState\(next\)/));
test('add action rerenders store', () => assert.match(source, /this\.saveHomeState\(next\);\s*if \(!added && def\.availability === "conditional"\)/));
test('conditional add shows setup hint', () => assert.match(source, /homeStoreConditionalHint/));
test('configure button exposes dialog semantics', () => assert.match(source, /configButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('configure button opens config form', () => assert.match(source, /configButton\.onclick = \(\) => \{\s*openHomeConfigForm\.call\(this/));
test('remove button carries remove action', () => assert.match(source, /removeButton\.dataset\.action = "remove"/));
test('remove button invokes instance removal', () => assert.match(source, /removeButton\.onclick = \(\) => \{ this\.removeHomeInstance\(added\.instanceId\)/));
test('preview button exposes dialog semantics', () => assert.match(source, /previewButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('preview button opens selected module', () => assert.match(source, /previewButton\.onclick = \(\) => this\.openStoreWidgetPreview\(moduleId, def, device\)/));
test('group toggle exposes expanded state', () => assert.match(source, /groupToggle\.setAttribute\("aria-expanded", String\(!collapsedGroups\.has\(label\)\)\)/));
test('group toggle controls group grid', () => assert.match(source, /groupToggle\.setAttribute\("aria-controls", groupId\)/));
test('unavailable pending cards expose explicit removal', () => assert.match(source, /removeButton\.dataset\.action = "remove-unavailable"/));
test('unavailable removal rerenders store', () => assert.match(source, /this\.removeHomeInstance\(instance\.instanceId\);\s*renderStore\(\);\s*onChanged\(\)/));
test('filter updates hidden state accessibly', () => assert.match(source, /card\.setAttribute\("aria-hidden", String\(!visible\)\)/));
test('filter restores focus to visible card', () => assert.match(source, /nextCard\.focus\(\{preventScroll: true\}\)/));
test('filter restores focus to search when no cards', () => assert.match(source, /else searchInput\.focus\(\{preventScroll: true\}\)/));
test('empty store exposes dedicated state', () => assert.match(source, /root\.textContent = this\.i18n\.homeNoMoreModules/));
