const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('store cards are programmatically focusable', () => assert.match(source, /card\.tabIndex = -1/));
test('store cards expose group semantics', () => assert.match(source, /card\.setAttribute\("role", "group"\)/));
test('store card keydown handler exists', () => assert.match(source, /card\.addEventListener\("keydown"/));
test('card navigation queries visible cards', () => assert.match(source, /\.sw-home-store__card:not\(\.fn__none\)/));
test('card navigation handles ArrowRight', () => assert.match(source, /event\.key === "ArrowRight"/));
test('card navigation handles ArrowLeft', () => assert.match(source, /event\.key === "ArrowLeft"/));
test('card navigation handles ArrowDown', () => assert.match(source, /event\.key === "ArrowDown"/));
test('card navigation handles ArrowUp', () => assert.match(source, /event\.key === "ArrowUp"/));
test('card navigation handles Home', () => assert.match(source, /if \(event\.key === "Home"\) next = 0/));
test('card navigation handles End', () => assert.match(source, /if \(event\.key === "End"\) next = cards\.length - 1/));
test('card navigation prevents default', () => assert.match(source, /event\.preventDefault\(\)/));
test('card navigation moves focus', () => assert.match(source, /cards\[next\]\.focus\(\)/));
test('card navigation wraps forward', () => assert.match(source, /\(index \+ 1\) % cards\.length/));
test('card navigation wraps backward', () => assert.match(source, /\(index - 1 \+ cards\.length\) % cards\.length/));
test('card navigation starts from current card', () => assert.match(source, /const index = cards\.indexOf\(card\)/));
test('card navigation ignores hidden cards', () => assert.match(source, /:not\(\.fn__none\)/));
test('card focus style has outline', () => assert.match(css, /\.sw-home-store__card[\s\S]*?&:focus-visible[\s\S]*?outline: 2px solid/));
test('card focus style uses primary color', () => assert.match(css, /outline: 2px solid var\(--b3-theme-primary\)/));
test('card focus style offsets outline', () => assert.match(css, /outline-offset: 2px/));
test('card remains section element', () => assert.match(source, /const card = document\.createElement\("section"\)/));
test('card keeps aria label', () => assert.match(source, /card\.setAttribute\("aria-label"/));
test('card controls remain nested buttons', () => assert.match(source, /const addButton = tiles\.lastElementChild as HTMLButtonElement/));
test('card navigation is separate from tab navigation', () => assert.match(source, /const cards = Array\.from\(root\.querySelectorAll/));
test('card navigation only runs for recognized keys', () => assert.match(source, /if \(next < 0\) return/));
test('card navigation supports empty list safely', () => assert.match(source, /if \(index < 0\) return/));
test('card navigation preserves focus order after filtering', () => assert.match(source, /querySelectorAll<HTMLElement>\("\.sw-home-store__card:not\(\.fn__none\)"\)/));
test('card focus ring is keyboard-visible', () => assert.match(css, /&:focus-visible/));
test('card role is bounded to group', () => assert.match(source, /role", "group/));
test('card tabindex is not positive', () => assert.doesNotMatch(source, /card\.tabIndex = [1-9]/));
test('card navigation uses local card listener', () => assert.match(source, /card\.addEventListener\("keydown"/));
