const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const {readSourceText}=require('./source-scan.cjs');
const {declaresIn}=require('./css-block-scan.cjs');

// 2026-09-16（T-6280 / D-396 第二十批）：7 条窗口断言迁移为块级；TS 源码读取改走 readSourceText。
const source = readSourceText('src/index.ts');
const storeUiSource = readSourceText('src/home-store-ui.ts');
const css = readSourceText('src/index.scss');
const base={topLevel: true};

test('store size controls use a labelled group', () => assert.match(storeUiSource, /tiles\.setAttribute\("role", "group"\)/));
test('store size controls keep their module id', () => assert.match(storeUiSource, /tiles\.dataset\.moduleId = moduleId/));
test('store size controls expose selected size', () => assert.match(storeUiSource, /tiles\.dataset\.selectedSize = added\?\.size \|\| supported\[0\]/));
test('store size label has a stable id', () => assert.match(storeUiSource, /sizeLabel\.id = `sw-home-store-size-label-\$\{moduleId\}`/));
test('store size group references its label', () => assert.match(storeUiSource, /tiles\.setAttribute\("aria-labelledby", sizeLabel\.id\)/));
test('store size buttons declare button type', () => assert.match(storeUiSource, /const tile = document\.createElement\("button"\);\s*tile\.type = "button"/));
test('store size buttons expose selected state data', () => assert.match(storeUiSource, /tile\.dataset\.selected = String\(sizeKey ===/));
test('store size buttons expose tooltips', () => assert.match(storeUiSource, /tile\.title = tile\.getAttribute\("aria-label"\)/));
test('store size buttons control the main action', () => assert.match(storeUiSource, /tile\.setAttribute\("aria-controls", actionId\)/));
test('store size selection updates group state', () => assert.match(storeUiSource, /tiles\.dataset\.selectedSize = sizeKey/));
test('store size selection updates action state', () => assert.match(storeUiSource,/addButton\.dataset\.selectedSize = sizeKey/));
test('store add action is created as a button', () => assert.match(source, /const addButton = document\.createElement\("button"\)/));
test('store add action declares button type', () => assert.match(storeUiSource, /addButton\.type = "button"/));
test('store add action has a stable id', () => assert.match(storeUiSource, /addButton\.id = actionId/));
test('store add action records operation', () => assert.match(storeUiSource, /addButton\.dataset\.action = added \? "apply-size" : "add"/));
test('store add action records selected size', () => assert.match(storeUiSource, /addButton\.dataset\.selectedSize = selectedTile\?\.dataset\.size/));
test('store add action references the size label', () => assert.match(storeUiSource, /addButton\.setAttribute\("aria-describedby", sizeLabel\.id\)/));
test('store add action includes selected size in its label', () => assert.match(storeUiSource, /addButton\.setAttribute\("aria-label", `\$\{added \? this\.i18n\.homeStoreApplySize : this\.i18n\.homeStoreAdd\}/));
test('store add action has a tooltip', () => assert.match(storeUiSource, /addButton\.title = addButton\.getAttribute\("aria-label"\)/));
test('store source metadata is a note', () => assert.match(storeUiSource, /sourceMeta\.setAttribute\("role", "note"\)/));
test('store source metadata has an accessible label', () => assert.match(storeUiSource, /sourceMeta\.setAttribute\("aria-label", this\.i18n\.homeStoreGuideHint\)/));
test('store source chips expose their kind', () => assert.match(storeUiSource, /chip\.dataset\.kind = kind/));
test('store source chips have accessible labels', () => assert.match(storeUiSource, /chip\.setAttribute\("aria-label", label\)/));
test('store card records supported sizes', () => assert.match(storeUiSource, /card\.dataset\.supportedSizes = supported\.join\(","\)/));
test('store card records current size', () => assert.match(storeUiSource, /card\.dataset\.currentSize = added\?\.size \|\| ""/));
test('store card status has stable id', () => assert.match(storeUiSource, /status\.id = `sw-home-store-status-\$\{moduleId\}`/));
test('store card status records state', () => assert.match(storeUiSource, /status\.dataset\.state = added \? "added" : "available"/));
test('store card status is live', () => assert.match(storeUiSource, /status\.setAttribute\("aria-live", "polite"\)/));
test('store card references status description', () => assert.match(storeUiSource, /card\.setAttribute\("aria-describedby", status\.id\)/));
test('store preview records module id', () => assert.match(storeUiSource, /preview\.dataset\.moduleId = moduleId/));
test('store preview action declares button type', () => assert.match(storeUiSource, /previewButton\.type = "button"/));
test('store preview action records operation', () => assert.match(storeUiSource, /previewButton\.dataset\.action = "preview"/));
test('store preview action announces dialog', () => assert.match(storeUiSource, /previewButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('store configure action records operation', () => assert.match(storeUiSource, /configButton\.dataset\.action = "configure"/));
test('store configure action announces dialog', () => assert.match(storeUiSource, /configButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('store remove action records operation', () => assert.match(storeUiSource, /removeButton\.dataset\.action = "remove"/));
test('store remove action keeps tooltip', () => assert.match(storeUiSource,/removeButton\.title = removeButton\.getAttribute\("aria-label"\)/));
test('store size row cannot shrink below content', () => assert.ok(declaresIn(css, '.sw-home-store__sizes', /min-width: 0/, base)));
test('store add action has a minimum width', () => assert.ok(declaresIn(css, '.sw-home-store__add', /min-width: 88px/, base)));
test('store add action has stronger emphasis', () => assert.ok(declaresIn(css, '.sw-home-store__add', /font-weight: 600/, base)));
test('store selected size has a data-state ring', () => assert.ok(declaresIn(css, /(^| )\.sw-home-store__size\[data-selected="true"]$/, /box-shadow/, base)));
test('store add action focus keeps a visible ring', () => assert.ok(declaresIn(css, '.sw-home-store__add:focus-visible', /box-shadow: var\(--sw-focus-ring/, base)));
test('store configure action preserves labels', () => assert.ok(declaresIn(css, '.sw-home-store__configure', /white-space: nowrap/, base)));
test('store remove action preserves labels', () => assert.ok(declaresIn(css, '.sw-home-store__remove', /white-space: nowrap/, base)));
