const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('preview captures its opener', () => assert.match(source, /const opener = document\.activeElement instanceof HTMLElement/));
test('preview exposes module id', () => assert.match(source, /container\.dataset\.moduleId = moduleId/));
test('preview exposes device', () => assert.match(source, /container\.dataset\.device = device/));
test('preview exposes selected size', () => assert.match(source, /container\.dataset\.size = sizeKey/));
test('preview container is a region', () => assert.match(source, /container\.setAttribute\("role", "region"\)/));
test('preview container has an accessible label', () => assert.match(source, /container\.setAttribute\("aria-label", `\$\{this\.i18n\.homeStorePreview\}/));
test('preview starts busy', () => assert.match(source, /container\.setAttribute\("aria-busy", "true"\)/));
test('preview body keeps its scoped class', () => assert.match(source, /body\.className = "sw-store-preview__body"/));
test('preview body is a status region', () => assert.match(source, /body\.setAttribute\("role", "status"\)/));
test('preview body is live', () => assert.match(source, /body\.setAttribute\("aria-live", "polite"\)/));
test('preview creates a home controller', () => assert.match(source, /controller = createHomeModuleController\(\{/));
test('preview read stays on the selected module', () => assert.match(source, /this\.homeRuntime\.read\(moduleId, device/));
test('preview read carries the selected size', () => assert.match(source, /\{\.\.\.readOptions, size: sizeKey\}/));
test('preview forces a fresh read', () => assert.match(source, /controller\.refresh\(\{\}, \{force: true\}\)/));
test('preview tracks disposed state', () => assert.match(source, /let disposed = false/));
test('preview exposes one cleanup helper', () => assert.match(source, /const disposePreview = \(\) =>/));
test('preview cleanup disposes controller', () => assert.match(source, /controller\?\.dispose\(\)/));
test('preview cleanup clears polling', () => assert.match(source, /window\.clearInterval\(disposeTimer\)/));
test('preview cleanup restores opener focus', () => assert.match(source, /if \(opener\?\.isConnected\) opener\.focus\(\)/));
test('preview wraps dialog destroy', () => assert.match(source, /const originalDestroy = dialog\.destroy\.bind\(dialog\)/));
test('preview destroy invokes cleanup', () => assert.match(source, /dialog\.destroy = \(\) => \{\s*disposePreview\(\);/));
test('preview destroy invokes original destroy', () => assert.match(source, /disposePreview\(\);\s*originalDestroy\(\);/));
test('preview mounts before refreshing', () => assert.match(source, /controller\.mount\(\);\s*const markPreviewReady =/));
test('preview clears busy state after refresh', () => assert.match(source, /container\.setAttribute\("aria-busy", "false"\)/));
test('preview refresh cleanup handles success and failure', () => assert.match(source, /controller\.refresh\(\{\}, \{force: true\}\)\.then\(markPreviewReady, markPreviewReady\)/));
test('preview polls dialog connectivity', () => assert.match(source, /disposeTimer = window\.setInterval/));
test('preview checks dialog connection', () => assert.match(source, /if \(!dialog\.element\.isConnected\)/));
test('preview polling uses shared cleanup', () => assert.match(source, /if \(!dialog\.element\.isConnected\) \{\s*disposePreview\(\);/));
test('preview has a bounded mobile width', () => assert.match(source, /width: this\.isMobile \? "min\(420px, 92vw\)"/));
test('preview has a bounded mobile height', () => assert.match(source, /height: this\.isMobile \? "min\(560px, 80vh\)"/));
test('preview styles remain scoped', () => assert.match(css, /\.sw-store-preview/));
