const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const storeUiSource = fs.readFileSync(path.join(root, 'src', 'home-store-ui.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('preview disclosure resolves source metadata', () => assert.match(storeUiSource, /const sourceInfo = resolveHomeStoreSourceInfo\(moduleId\)/));
test('preview disclosure has a scoped meta wrapper', () => assert.match(storeUiSource, /meta\.className = "sw-store-preview__meta"/));
test('preview disclosure is a note region', () => assert.match(storeUiSource, /meta\.setAttribute\("role", "note"\)/));
test('preview disclosure uses a bounded chip helper', () => assert.match(storeUiSource, /const addMeta = \(label: string, tone: string\)/));
test('preview disclosure chips have a scoped class', () => assert.match(storeUiSource, /chip\.className = `sw-store-preview__meta-chip is-\$\{tone\}`/));
test('preview disclosure chips expose tooltips', () => assert.match(storeUiSource, /chip\.title = label/));
test('preview disclosure marks remote integration', () => assert.match(storeUiSource, /sourceInfo\?\.integration === "http"/));
test('preview disclosure marks local integration', () => assert.match(storeUiSource, /sourceInfo\?\.integration === "local-bridge"/));
test('preview disclosure falls back to offline', () => assert.match(storeUiSource, /this\.i18n\.homeStoreNetworkOffline/));
test('preview disclosure explains location privacy', () => assert.match(storeUiSource, /this\.i18n\.homeStorePrivacyLocation/));
test('preview disclosure explains local privacy', () => assert.match(storeUiSource, /this\.i18n\.homeStorePrivacyLocal/));
test('preview disclosure explains endpoint privacy', () => assert.match(storeUiSource, /this\.i18n\.homeStorePrivacyEndpoint/));
test('preview disclosure explains no-content privacy', () => assert.match(storeUiSource, /this\.i18n\.homeStorePrivacyNone/));
test('preview disclosure renders source text', () => assert.match(storeUiSource, /this\.i18n\.homeStoreSource\.replace\("\{source\}"/));
test('preview disclosure has a provider fallback', () => assert.match(storeUiSource, /sourceInfo\?\.providerName \|\| "SiYuan"/));
test('preview disclosure adds source tone', () => assert.match(storeUiSource, /addMeta\(this\.i18n\.homeStoreSource[\s\S]*?"source"\)/));
test('preview disclosure adds network tone', () => assert.match(storeUiSource, /sourceInfo\?\.integration === "http" \? "network"/));
test('preview disclosure adds local tone', () => assert.match(storeUiSource, /sourceInfo\?\.integration === "local-bridge" \? "local"/));
test('preview disclosure adds offline tone', () => assert.match(storeUiSource, /: "offline"\);/));
test('preview disclosure adds privacy tone', () => assert.match(storeUiSource, /addMeta\(privacy, "privacy"\)/));
test('preview disclosure is mounted before preview body', () => assert.match(storeUiSource,/container\.appendChild\(meta\);\s*const body = document\.createElement\("div"\)/));
test('preview meta uses flex layout', () => assert.match(css, /\.sw-store-preview[\s\S]*?&__meta[\s\S]*?display: flex/));
test('preview meta wraps on narrow surfaces', () => assert.match(css, /&__meta[\s\S]*?flex-wrap: wrap/));
test('preview meta keeps bounded gaps', () => assert.match(css, /&__meta[\s\S]*?gap: 5px/));
test('preview chips have visible borders', () => assert.match(css, /&__meta-chip[\s\S]*?border: 1px solid/));
test('preview chips allow long source names', () => assert.match(css, /&__meta-chip[\s\S]*?overflow-wrap: anywhere/));
test('preview chips keep legacy word-break fallback', () => assert.match(css, /&__meta-chip[\s\S]*?word-break: break-word/));
test('preview chips remain selectable', () => assert.match(css, /&__meta-chip[\s\S]*?user-select: text/));
test('preview network tone is scoped', () => assert.match(css, /&\.is-network/));
test('preview privacy tone is scoped', () => assert.match(css, /&\.is-privacy/));
test('preview disclosure styles remain store-preview scoped', () => assert.match(css, /\.sw-store-preview/));
