const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('store size controls use a labelled group', () => assert.match(source, /tiles\.setAttribute\("role", "group"\)/));
test('store size controls keep their module id', () => assert.match(source, /tiles\.dataset\.moduleId = moduleId/));
test('store size controls expose selected size', () => assert.match(source, /tiles\.dataset\.selectedSize = added\?\.size \|\| supported\[0\]/));
test('store size label has a stable id', () => assert.match(source, /sizeLabel\.id = `sw-home-store-size-label-\$\{moduleId\}`/));
test('store size group references its label', () => assert.match(source, /tiles\.setAttribute\("aria-labelledby", sizeLabel\.id\)/));
test('store size buttons declare button type', () => assert.match(source, /const tile = document\.createElement\("button"\);\s*tile\.type = "button"/));
test('store size buttons expose selected state data', () => assert.match(source, /tile\.dataset\.selected = String\(sizeKey ===/));
test('store size buttons expose tooltips', () => assert.match(source, /tile\.title = tile\.getAttribute\("aria-label"\)/));
test('store size buttons control the main action', () => assert.match(source, /tile\.setAttribute\("aria-controls", actionId\)/));
test('store size selection updates group state', () => assert.match(source, /tiles\.dataset\.selectedSize = sizeKey/));
test('store size selection updates action state', () => assert.match(source, /addButton\.dataset\.selectedSize = sizeKey/));
test('store add action is created as a button', () => assert.match(source, /const addButton = document\.createElement\("button"\)/));
test('store add action declares button type', () => assert.match(source, /addButton\.type = "button"/));
test('store add action has a stable id', () => assert.match(source, /addButton\.id = actionId/));
test('store add action records operation', () => assert.match(source, /addButton\.dataset\.action = added \? "apply-size" : "add"/));
test('store add action records selected size', () => assert.match(source, /addButton\.dataset\.selectedSize = selectedTile\?\.dataset\.size/));
test('store add action references the size label', () => assert.match(source, /addButton\.setAttribute\("aria-describedby", sizeLabel\.id\)/));
test('store add action includes selected size in its label', () => assert.match(source, /addButton\.setAttribute\("aria-label", `\$\{added \? this\.i18n\.homeStoreApplySize : this\.i18n\.homeStoreAdd\}/));
test('store add action has a tooltip', () => assert.match(source, /addButton\.title = addButton\.getAttribute\("aria-label"\)/));
test('store source metadata is a note', () => assert.match(source, /sourceMeta\.setAttribute\("role", "note"\)/));
test('store source metadata has an accessible label', () => assert.match(source, /sourceMeta\.setAttribute\("aria-label", this\.i18n\.homeStoreGuideHint\)/));
test('store source chips expose their kind', () => assert.match(source, /chip\.dataset\.kind = kind/));
test('store source chips have accessible labels', () => assert.match(source, /chip\.setAttribute\("aria-label", label\)/));
test('store card records supported sizes', () => assert.match(source, /card\.dataset\.supportedSizes = supported\.join\(","\)/));
test('store card records current size', () => assert.match(source, /card\.dataset\.currentSize = added\?\.size \|\| ""/));
test('store card status has stable id', () => assert.match(source, /status\.id = `sw-home-store-status-\$\{moduleId\}`/));
test('store card status records state', () => assert.match(source, /status\.dataset\.state = added \? "added" : "available"/));
test('store card status is live', () => assert.match(source, /status\.setAttribute\("aria-live", "polite"\)/));
test('store card references status description', () => assert.match(source, /card\.setAttribute\("aria-describedby", status\.id\)/));
test('store preview records module id', () => assert.match(source, /preview\.dataset\.moduleId = moduleId/));
test('store preview action declares button type', () => assert.match(source, /previewButton\.type = "button"/));
test('store preview action records operation', () => assert.match(source, /previewButton\.dataset\.action = "preview"/));
test('store preview action announces dialog', () => assert.match(source, /previewButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('store configure action records operation', () => assert.match(source, /configButton\.dataset\.action = "configure"/));
test('store configure action announces dialog', () => assert.match(source, /configButton\.setAttribute\("aria-haspopup", "dialog"\)/));
test('store remove action records operation', () => assert.match(source, /removeButton\.dataset\.action = "remove"/));
test('store remove action keeps tooltip', () => assert.match(source, /removeButton\.title = removeButton\.getAttribute\("aria-label"\)/));
test('store size row cannot shrink below content', () => assert.match(css, /\.sw-home-store__sizes[\s\S]*?min-width: 0/));
test('store add action has a minimum width', () => assert.match(css, /\.sw-home-store__add[\s\S]*?min-width: 88px/));
test('store add action has stronger emphasis', () => assert.match(css, /\.sw-home-store__add[\s\S]*?font-weight: 600/));
test('store selected size has a data-state ring', () => assert.match(css, /&\[data-selected="true"\][\s\S]*?box-shadow/));
test('store add action focus keeps a visible ring', () => assert.match(css, /\.sw-home-store__add[\s\S]*?&:focus-visible \{ box-shadow: var\(--sw-focus-ring\)/));
test('store configure action preserves labels', () => assert.match(css, /\.sw-home-store__configure[\s\S]*?white-space: nowrap/));
test('store remove action preserves labels', () => assert.match(css, /\.sw-home-store__remove[\s\S]*?white-space: nowrap/));
