const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const source = fs.readFileSync(path.join(__dirname, '..', 'src', 'index.ts'), 'utf8');

test('store tablist has activation helper', () => assert.match(source, /const activateStoreTab =/));
test('store tabs use roving tabindex', () => assert.match(source, /setAttribute\("tabindex", active \? "0" : "-1"\)/));
test('initial active tab is focusable', () => assert.match(source, /btn\.setAttribute\("tabindex", tab\.key === storeTab \? "0" : "-1"\)/));
test('store tabs click uses activation helper', () => assert.match(source, /btn\.addEventListener\("click", \(\) => activateStoreTab\(btn\)\)/));
test('store tabs handle ArrowRight', () => assert.match(source, /event\.key === "ArrowRight"/));
test('store tabs handle ArrowLeft', () => assert.match(source, /event\.key === "ArrowLeft"/));
test('store tabs handle ArrowDown', () => assert.match(source, /event\.key === "ArrowDown"/));
test('store tabs handle ArrowUp', () => assert.match(source, /event\.key === "ArrowUp"/));
test('store tabs handle Home', () => assert.match(source, /event\.key === "Home"/));
test('store tabs handle End', () => assert.match(source, /event\.key === "End"/));
test('store tab navigation prevents default', () => assert.match(source, /event\.preventDefault\(\)/));
test('store tab navigation moves focus', () => assert.match(source, /buttons\[next\]\.focus\(\)/));
test('store tab selection updates aria-selected', () => assert.match(source, /candidate\.setAttribute\("aria-selected", String\(active\)\)/));
test('store summary is a live region', () => assert.match(source, /resultSummary\.setAttribute\("aria-live", "polite"\)/));
test('store groups have stable ids', () => assert.match(source, /const groupId = `sw-home-store-group-/));
test('store groups expose ids on grids', () => assert.match(source, /groupGrid\.id = groupId/));
test('group toggles reference controlled grids', () => assert.match(source, /groupToggle\.setAttribute\("aria-controls", groupId\)/));
test('add action has an accessible label', () => assert.match(source, /addButton\.setAttribute\("aria-label"/));
test('preview action has an accessible label', () => assert.match(source, /previewButton\.setAttribute\("aria-label"/));
test('tab activation stores selected key', () => assert.match(source, /storeTab = button\.dataset\.tabKey/));
test('tab activation reapplies filter', () => assert.match(source, /activateStoreTab[\s\S]*?applyFilter\(\)/));
test('tab focus order uses only visible tab controls', () => assert.match(source, /querySelectorAll<HTMLElement>\("\.sw-home-store__tab"\)/));
test('keyboard navigation wraps forward', () => assert.match(source, /\(index \+ 1\) % buttons\.length/));
test('keyboard navigation wraps backward', () => assert.match(source, /\(index - 1 \+ buttons\.length\) % buttons\.length/));
test('home key selects first tab', () => assert.match(source, /if \(event\.key === "Home"\) next = 0/));
test('end key selects last tab', () => assert.match(source, /if \(event\.key === "End"\) next = buttons\.length - 1/));
test('group toggle remains a button', () => assert.match(source, /groupToggle\.type = "button"/));
test('add action remains a button', () => assert.match(source, /tiles\.insertAdjacentHTML\("beforeend", `<button/));
test('preview action remains a button', () => assert.match(source, /previewButton\.className = "sw-home-store__size sw-home-store__preview-btn"/));
test('store tabs remain tab role', () => assert.match(source, /btn\.setAttribute\("role", "tab"\)/));
test('store tablist remains tablist role', () => assert.match(source, /tabBar\.setAttribute\("role", "tablist"\)/));
test('aria controls value is deterministic', () => assert.match(source, /orderedGroups\.indexOf\(label\)/));
