const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src', 'index.ts'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src', 'index.scss'), 'utf8');

test('store captures the opener element', () => assert.match(source, /const opener = document\.activeElement instanceof HTMLElement/));
test('clear search has a tooltip', () => assert.match(source, /clearSearchButton\.title = this\.i18n\.homeStoreClearSearch/));
test('sort control has a tooltip', () => assert.match(source, /sortSelect\.title = this\.i18n\.homeStoreSortLabel/));
test('store tablist keeps tab semantics', () => assert.match(source, /tabBar\.setAttribute\("role", "tablist"\)/));
test('store tablist has an accessible label', () => assert.match(source, /tabBar\.setAttribute\("aria-label", this\.i18n\.homeStoreTitle\)/));
test('result summary has a stable id', () => assert.match(source, /resultSummary\.id = "sw-home-store-result-summary"/));
test('result summary remains a status region', () => assert.match(source, /resultSummary\.setAttribute\("role", "status"\)/));
test('result summary remains live', () => assert.match(source, /resultSummary\.setAttribute\("aria-live", "polite"\)/));
test('ready section has a stable id', () => assert.match(source, /readyHeading\.id = "sw-home-store-section-ready"/));
test('group headings have stable ids', () => assert.match(source, /groupHeading\.id = `sw-home-store-group-heading-/));
test('group grids expose group role', () => assert.match(source, /groupGrid\.setAttribute\("role", "group"\)/));
test('group grids reference their heading', () => assert.match(source, /groupGrid\.setAttribute\("aria-labelledby", groupHeading\.id\)/));
test('pending section has a stable id', () => assert.match(source, /pendingHeading\.id = "sw-home-store-section-pending"/));
test('pending grid has a stable id', () => assert.match(source, /pendingGrid\.id = "sw-home-store-pending-grid"/));
test('pending grid exposes group role', () => assert.match(source, /pendingGrid\.setAttribute\("role", "group"\)/));
test('pending grid references its heading', () => assert.match(source, /pendingGrid\.setAttribute\("aria-labelledby", pendingHeading\.id\)/));
test('clear filters uses a scoped class', () => assert.match(source, /clearFilters\.className = "b3-button b3-button--text sw-home-store__clear-filters"/));
test('clear filters has an accessible label', () => assert.match(source, /clearFilters\.setAttribute\("aria-label", this\.i18n\.homeStoreClearFilters\)/));
test('clear filters has a tooltip', () => assert.match(source, /clearFilters\.title = this\.i18n\.homeStoreClearFilters/));
test('clear filters clears the query model', () => assert.match(source, /storeQuery = ""/));
test('clear filters hides the search clear action', () => assert.match(source, /clearSearchButton\.hidden = true/));
test('clear filters resets the selected tab key', () => assert.match(source, /storeTab = "all"/));
test('clear filters selects the all tab by key', () => assert.match(source, /const active = button\.dataset\.tabKey === "all"/));
test('clear filters restores roving tabindex', () => assert.match(source, /button\.setAttribute\("tabindex", active \? "0" : "-1"\)/));
test('clear filters restores search focus', () => assert.match(source, /applyFilter\(\);\s*searchInput\.focus\(\);/));
test('store destroy restores opener focus', () => assert.match(source, /if \(opener\?\.isConnected\) opener\.focus\(\)/));
test('filter empty state remains a status region', () => assert.match(source, /filterEmptyState\.setAttribute\("role", "status"\)/));
test('clear filters cannot be accidentally selected', () => assert.match(css, /\.sw-home-store__clear-filters[\s\S]*?user-select: none/));
test('forced colors cover clear filters', () => assert.match(css, /\.sw-home-store__clear-filters/));
test('clear filters remains scoped to the store', () => assert.match(css, /sw-home-store__clear-filters/));
